### ISSUE TITLE
Repo automatically add doesn’t work

### ISSUE THREAD

**Issue by motoissa** [wstyres/Zebra#94] opened 2019-05-16 07:26 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 
12.1.2
1.0 beta 11
iPhone 7 plus
**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

**Additional context**

**Comment by wstyres** [comment] 2019-05-16 16:48
Not sure what the problem is here, could you be more descriptive? Maybe provide what steps you're taking?

**Comment by motoissa** [comment] 2019-05-16 23:57
When I copy a repo and it asks me if I want to add it and I press add I get this error   
  

  

  
  

  
  

  
  

  
  
>

**Comment by wstyres** [comment] 2019-05-17 00:00
What is the error?

**Comment by motoissa** [comment] 2019-05-17 00:01
I attached 2 pictures u didn’t get them?

**Comment by wstyres** [comment] 2019-05-17 00:02
No they did not attach, you might have to upload them to Imgur first and then paste a link.

**Comment by motoissa** [comment] 2019-05-17 00:06
https://imgur.com/a/wZrfnt8

**Comment by wstyres** [comment] 2019-05-17 00:08
What repo are you trying to add or does this problem occur with every repo you try to add from your clipboard?

**Comment by motoissa** [comment] 2019-05-17 00:09
Every repo

**Comment by wstyres** [comment] 2019-05-17 00:16
Ok, I'll take a look at see if I can reproduce the problem

**Comment by motoissa** [comment] 2019-05-17 00:17
Ok thank you

**Comment by wstyres** [comment] 2019-05-17 19:28
Fixed as of e68ff26. It will be in the next beta.

**Closed by wstyres** 2019-05-17 19:28 UTC
Labels: bug

**Comment by motoissa** [comment] 2019-05-17 22:29
Ok thank you

**Comment by motoissa** [comment] 2019-06-01 15:58
I found another weird bug in the new version of zebra   
  

  
  

  
  
>
