### ISSUE TITLE
 Dark mode problem

### ISSUE THREAD

**Issue by kaloody99** [wstyres/Zebra#1258] opened 2020-05-19 09:45 UTC
![1959AEF8-97E1-4905-A6A8-30DB513CBB1B](https://user-images.githubusercontent.com/48293343/82311493-c86c3b80-9993-11ea-9931-34a5d879351c.png)

iPhone 6 Plus running ios 12.4.6

**Comment by wstyres** [comment] 2020-05-19 16:32
Duplicate of #1173

**Closed by wstyres** 2020-05-19 16:32 UTC
Labels: bug
