### ISSUE TITLE
A number next to repos to show how many tweaks/packages we have from that repo

### ISSUE THREAD

**Issue by oxi0de69** [wstyres/Zebra#1069] opened 2020-04-13 18:14 UTC
**Is your feature request related to a problem? Please describe.**
I have a lot of repos and clearing away repos is hard when i have to search through each repo.

**Describe the solution you'd like**
I would like a number next the repo that says how many tweaks/pacages there are installed from that repo. You could also make a red cross if you have no tweaks/packages from that repo.

**Comment by wstyres** [comment] 2020-04-13 18:54
Duplicate of #956

**Closed by wstyres** 2020-04-13 18:54 UTC
Labels: suggestion
