### ISSUE TITLE
Dark Mode broken

### ISSUE THREAD

**Issue by AllStars101-sudo** [wstyres/Zebra#332] opened 2019-09-07 11:20 UTC
As seen in the attachment, upon clicking the dark mode toggle within zebra (I’m on an iPhone 6s running iOS 12.4 on unc0ver), the top part, or the title bar or whatever it’s called (seen in the attachment) remains to be dark even after clicking the light mode toggle.

**Expected behavior**
Title bar/top bar supposed to be light like the rest of the UI

**Screenshots**
Attached

**Device Information (please complete the following information):**
 - iOS Version [12.4]: 
 - Zebra Version [e.g. 1.0\~beta 20-3]: 
 - Device Type: iPhone 6s;
![68AD34B8-20F5-4906-BEF6-E6541CD63E83](https://user-images.githubusercontent.com/53670363/64474204-7c31f000-d1a4-11e9-8a25-5b1f45d7fb06.png)

**Comment by wstyres** [comment] 2019-10-27 15:13
Not able to reproduce anymore as of latest commit, because this is an outdated bug I'm going to close the issue.

**Comment by wstyres** [comment] 2019-10-27 15:30
I can reproduce on the OLED and 13 dark mode settings so I'll take another look

**Comment by wstyres** [comment] 2019-10-27 16:59
Should be fixed as of f8ff4af7c17c83af51dd3479f54853aa5d1e6ca4.

**Comment by AllStars101-sudo** [comment] 2019-10-31 12:23
Okay, cool. Thanks for all the work you’re doing! Have a great day!

**Closed** 2019-11-02 00:12 UTC
Labels: bug, scheduled
