### ISSUE TITLE
Update packages 

### ISSUE THREAD

**Issue by Nadjibg** [wstyres/Zebra#1328] opened 2020-05-28 12:44 UTC
![BE64DF69-A855-4B1B-B359-31D103C3BADC](https://user-images.githubusercontent.com/41592827/83142724-c9fed780-a0e8-11ea-9791-68d3a640173e.png)
**Describe the bug**
I have these to pakago that keep showing up even when I install themm.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <INSERT-HERE>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <INSERT-HERE>
 - Device Type [e.g. iPhone or iPad]: <INSERT-HERE>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <INSERT-HERE>

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by absidue** [comment] 2020-05-28 12:50
Duplicate of #1310

**Closed** 2020-05-30 04:15 UTC
Labels: bug
