### ISSUE TITLE
Language switch

### ISSUE THREAD

**Issue by Alhowity** [wstyres/Zebra#885] opened 2020-02-23 07:37 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Hi my iPhone language is Arabic and Zebra directly using system language now i want to use Zebra with  English can you add future to change app language?

**Comment by eve0415** [comment] 2020-02-23 07:46
Duplicate of #680

**Closed** 2020-02-23 15:32 UTC
Labels: suggestion
