### ISSUE TITLE
[BUG] Upgrading substitute removes all tweaks

### ISSUE THREAD

**Issue by gmanc2** [wstyres/Zebra#610] opened 2019-11-22 23:11 UTC
**Describe the bug**
Apparently, the bug is still around where it will delete all your tweaks when Zebra forgets to dependency correctly.
Zebra removed all my tweaks when trying to update Substitute.

**To Reproduce**
Update Substitute 
**Expected behavior**
Substitute Updates
**Screenshots**
N/a Couldn't screenshot in time
**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: Beta 1
 - Device Type [e.g. iPhone or iPad]: Iphone XS Max
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Unc0ver

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.
N/a
**Additional context**
N/a

**Comment by wstyres** [comment] 2019-11-23 00:05
I'm not able to reproduce this, it is possible that it has already been fixed in #600 but it is not available in a beta yet. I'll see if I can remove the fix in order to reproduce the bug.

**Comment by wstyres** [comment] 2019-11-23 00:17
Not able to reproduce on the simulator at all. I'll see if I can get a device on unc0ver to investigate further.

**Comment by wstyres** [comment] 2019-11-23 00:42
Was able to reproduce. This looks like it was a unique situation that applies only to substitute due to how it handled the mobile substrate dummy package before version 0.1.0. I'm investigating a fix now.

**Comment by wstyres** [comment] 2019-11-23 01:39
Should be fixed as of b09ab44644a2b8795f0f4ac4cc48be87cd5e3cc3. Zebra now properly removes the conflict that was provided in the new Substitute update but since it also provides that package it will keep all of its dependencies. 
![Simulator Screen Shot - iPhone 11 - 2019-11-22 at 20 36 37](https://user-images.githubusercontent.com/19736790/69470914-24992e80-0d68-11ea-9831-2e5ee6288d36.png)

**Closed** 2019-11-23 02:13 UTC
Labels: bug, scheduled
