### ISSUE TITLE
Zebra's sources.list should support apt

### ISSUE THREAD

**Issue by Kyondev** [wstyres/Zebra#1444] opened 2020-06-28 18:02 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like to be able to update packages through the command line interface with apt.
One easy step to get closer to this goal is that apt can read Zebra's sources list. I could successfully do this by creating a symlink from "Zebra's sources.list" to "/etc/apt/sources.list.d/" kinda like Cydia seems to do. It would be just nice if Zebra did this out of the box. 

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by eve0415** [comment] 2020-06-29 01:20
Duplicate of #1369

**Closed** 2020-06-29 12:45 UTC
Labels: suggestion
