### ISSUE TITLE
Zebra reset ignored updates after update of zebra

### ISSUE THREAD

**Issue by nicolaspatate** [wstyres/Zebra#1025] opened 2020-04-01 17:49 UTC
**Describe the bug**
Ignored updates are not ignored after a Zebra update

**To Reproduce**
Update zebra with ignored updates

**Expected behavior**
Ignored updates stay ignored

**Device Information (please complete the following information):**
 - iOS 13.3
 - Zebra 1.1\~beta4
 - iPhone 6s
 - checkra1n

**Comment by PoomSmart** [comment] 2020-04-04 11:21
Duplicate of #972

**Closed by PoomSmart** 2020-04-04 11:21 UTC
Labels: medium, purchases, settings
