### ISSUE TITLE
Zebra doesnt show feauture package on my home

### ISSUE THREAD

**Issue by HarryVn1188** [wstyres/Zebra#1082] opened 2020-04-14 01:56 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <INSERT-HERE>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <INSERT-HERE>
 - Device Type [e.g. iPhone or iPad]: <INSERT-HERE>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <INSERT-HERE>

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by eve0415** [comment] 2020-04-14 01:57
Duplicate of #1077

**Comment by HarryVn1188** [comment] 2020-04-14 01:58
![E2C371BA-2659-4262-8034-5B1925C146D9](https://user-images.githubusercontent.com/61400347/79177888-fe1a8380-7e2d-11ea-9164-215579589e31.png)

**Comment by HarryVn1188** [comment] 2020-04-14 01:59
![939ACD2A-39ED-46D2-871F-A85789FF262C](https://user-images.githubusercontent.com/61400347/79178013-49cd2d00-7e2e-11ea-8284-473d9ca3235c.png)

**Comment by wstyres** [comment] 2020-04-14 16:19
Duplicate of #1077

**Closed by wstyres** 2020-04-14 16:19 UTC
Labels: bug
