### ISSUE TITLE
Can’t add new sources, see screenshot. 

### ISSUE THREAD

**Issue by hotDoggey** [wstyres/Zebra#11] opened 2019-04-11 23:15 UTC
I get this when I click to add the source: https://imgur.com/gallery/evl635o

**Device Information (please complete the following information):**
 - iOS Version [12.1.1]
 - AUPM Version [1.0~beta1]
 - Device Type [iPhone 7]

**Comment by wstyres** [comment] 2019-04-11 23:31
Duplicate of #10, move discussion to there

**Closed by wstyres** 2019-04-11 23:31 UTC
