### ISSUE TITLE
Changes tab shows old packages

### ISSUE THREAD

**Issue by yur1xpp** [wstyres/Zebra#1055] opened 2020-04-07 14:32 UTC
**Describe the bug**
The changes tab sometimes showing old packages, alphabetically.

**To Reproduce**
Random issue, sometimes it shows the new packages, sometimes the old packages. But mostly can be reproduce by keep dragging the changes table to keep refreshing one after another.

**Expected behavior**
Show new packages.

**Screenshots**
This shows the old packages. Mostly from big boss. We all know Ryan didn’t update the package 😂
https://imgur.com/a/SRrj6ME

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: latest beta
 - Device Type [e.g. iPhone or iPad]: iPhone 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment] 2020-04-07 16:57
Duplicate of #996

**Closed by wstyres** 2020-04-07 16:57 UTC
Labels: bug
