### ISSUE TITLE
[BUG] [12.4] App crashes after attempting to search

### ISSUE THREAD

**Issue by jvyden420** [wstyres/Zebra#310] opened 2019-08-19 02:44 UTC
**Describe the bug**
App crashes after attempting to search
**To Reproduce**
1. Go to the search menu
2. Tap search

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]:  12.4 (upgraded from 12.0.1)
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0~beta19
 - Device Type [e.g. iPhone or iPad]: iPod Touch 6G

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.
```Aug 18 22:37:04 Jaydens-iPod-6G-1201-Jailbroken assertiond[59] <Notice>: [SpringBoard:5728] Attempting to acquire assertion for Zebra:6206: <BKProcessAssertion: 0x129d67c60; "com.apple.UIKit.KeyboardManagement.message" (finishTask:180s); id:\M-b\M^@\M-&B2E0FADAAABD>
Aug 18 22:37:04 Jaydens-iPod-6G-1201-Jailbroken assertiond[59] <Notice>: [Zebra:6206] Add assertion: <BKProcessAssertion: 0x129d67c60; id: 5728-21E7715E-1E11-49CD-A476-B2E0FADAAABD; name: com.apple.UIKit.KeyboardManagement.message; state: active; reason: finishTask; duration: 180.0s> {
Aug 18 22:37:04 Jaydens-iPod-6G-1201-Jailbroken assertiond[59] <Notice>: [Zebra:6206] Activate assertion: <BKProcessAssertion: 0x129d67c60; "com.apple.UIKit.KeyboardManagement.message" (finishTask:180s); id:\M-b\M^@\M-&B2E0FADAAABD>
Aug 18 22:37:04 Jaydens-iPod-6G-1201-Jailbroken Zebra(UIKitCore)[6206] <Notice>: activate generator <_UIKeyboardFeedbackGenerator: 0x282178a00: prepared=1> with style: TurnOn; activationCount: 0 -> 1; styleActivationCount: 0 -> 1
Aug 18 22:37:04 Jaydens-iPod-6G-1201-Jailbroken Zebra(UIKitCore)[6206] <Notice>: activate engine <_UIFeedbackSystemSoundEngine: 0x287597420>, clientCount: 0 -> 1
Aug 18 22:37:04 Jaydens-iPod-6G-1201-Jailbroken Zebra(UIKitCore)[6206] <Notice>: activating engine <_UIFeedbackSystemSoundEngine: 0x287597420>
Aug 18 22:37:04 Jaydens-iPod-6G-1201-Jailbroken Zebra(UIKitCore)[6206] <Notice>: engine <_UIFeedbackSystemSoundEngine: 0x287597420: state=0, numberOfClients=1, prewarmCount=0, _isSuspended=0> state changed: Inactive -> Activating
Aug 18 22:37:04 Jaydens-iPod-6G-1201-Jailbroken Zebra(UIKitCore)[6206] <Notice>: engine <_UIFeedbackSystemSoundEngine: 0x287597420: state=3, numberOfClients=1, prewarmCount=0, _isSuspended=0> state changed: Activating -> Running
Aug 18 22:37:04 Jaydens-iPod-6G-1201-Jailbroken assertiond[59] <Notice>: [Zebra:6206] Deactivate assertion: <BKProcessAssertion: 0x129d67c60; "com.apple.UIKit.KeyboardManagement.message" (finishTask:180s); id:\M-b\M^@\M-&B2E0FADAAABD>
Aug 18 22:37:04 Jaydens-iPod-6G-1201-Jailbroken assertiond[59] <Notice>: [Zebra:6206] Remove assertion: <BKProcessAssertion: 0x129d67c60; "com.apple.UIKit.KeyboardManagement.message" (finishTask:180s); id:\M-b\M^@\M-&B2E0FADAAABD>
Aug 18 22:37:04 Jaydens-iPod-6G-1201-Jailbroken mediaserverd(AudioToolbox)[3003] <Notice>: 1440: clientPID 6206(Zebra), flag 1, ssid 1155
Aug 18 22:37:04 Jaydens-iPod-6G-1201-Jailbroken mediaserverd(AudioToolbox)[3003] <Notice>: 1440: clientPID 6206(Zebra), flag 1, ssid 1156
Aug 18 22:37:04 Jaydens-iPod-6G-1201-Jailbroken assertiond[59] <Notice>: [Zebra:6206] Deactivate assertion: <BKProcessAssertion: 0x129e325b0; "systemAnimationFence" (finishTask:180s); id:\M-b\M^@\M-&663C75554EE9>
Aug 18 22:37:04 Jaydens-iPod-6G-1201-Jailbroken assertiond[59] <Notice>: [Zebra:6206] Setting jetsam priority to 10 [0x10100]
Aug 18 22:37:04 Jaydens-iPod-6G-1201-Jailbroken assertiond[59] <Notice>: [Zebra:6206] Remove assertion: <BKProcessAssertion: 0x129e325b0; "systemAnimationFence" (finishTask:180s); id:\M-b\M^@\M-&663C75554EE9>
Aug 18 22:37:04 Jaydens-iPod-6G-1201-Jailbroken Zebra(Foundation)[6206] <Notice>: *** Assertion failure in -[UITableView _configureCellForDisplay:forIndexPath:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore/UIKit-3698.140/UITableView.m:9655
Aug 18 22:37:04 Jaydens-iPod-6G-1201-Jailbroken Zebra(CoreFoundation)[6206] <Notice>: *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UITableView (<UITableView: 0x102125000; frame = (0 0; 320 519); clipsToBounds = YES; autoresize = W+H; tintColor = UIExtendedSRGBColorSpace 0.4 0.5 0.98 1; gestureRecognizers = <NSArray: 0x281e3e8e0>; animations = { bounds.origin=<CABasicAnimation: 0x2814c4bc0>; bounds.size=<CABasicAnimation: 0x2814c4ba0>; position=<CABasicAnimation: 0x2814c50c0>; bounds.origin-2=<CABasicAnimation: 0x2814c4760>; bounds.size-2=<CABasicAnimation: 0x2814c5200>; }; layer = <CALayer: 0x28103c5a0>; contentOffset: {0, -52}; contentSize: {320, 492}; adjustedContentInset: {52, 0, 167, 0}>) failed to obtain a cell from its dataSource (<ZBSearchViewController: 0x101242b50>)'
```

**Additional context**
Seems to be related to UITableView.
No main suspect in CrashReporter.
Only substrate dylibs are loaded.

**Comment by PoomSmart** [comment] 2019-08-19 12:15
Duplicate of #267

**Closed by PoomSmart** 2019-08-19 12:15 UTC
Labels: bug
