### ISSUE TITLE
3d-touch crashes zebra

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#340] opened 2019-09-07 17:44 UTC
**Describe the bug**

3d-touching on any Reddit article in the changes tab may cause zebra to crash. The further to the right they are the greater the chance of crashing. Example: the first article doesn't crash when 3dtouching, the second article sometimes crashes, but the third and so on always crashes.

**To Reproduce**

3d touch on Reddit links in changes tab.

**Expected behavior**

I expect peek and pop to work properly.

**Screenshots**

Screen recording is attached.

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.1 beta 3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: Zebra 1.0 ~ beta 21
 - Device Type [e.g. iPhone or iPad]: iPhone Xs

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

N/A

**Additional context**

https://imgur.com/gallery/1CD0sFs

**Comment by worldlydev** [comment] 2019-09-07 17:46
Seems somebody else also reported this issue 🤔🤔 no idea why the issue was closed tho 🤷‍♂️ #334

**Comment by wstyres** [comment] 2019-09-08 16:12
Duplicate of #337

**Closed by wstyres** 2019-09-08 16:12 UTC
Labels: bug
