### ISSUE TITLE
Litten's repo crashing Zebra

### ISSUE THREAD

**Issue by Greigh** [wstyres/Zebra#845] opened 2020-02-04 18:26 UTC
Zebra crash while refreshing sources. No culprits. 

**Device Information (please complete the following information):**
 - iOS Version: 12.4
 - Zebra Version: 1.0.6
 - Device Type: XS Max
 - Jailbreak Type: unc0ver 

**Crash Log or System Log**
https://ghostbin.co/paste/n3g9f

**Additional context**
Doesn’t happen every time.

**Comment by wstyres** [comment] 2020-02-04 19:07
Could I see a list of sources?

**Comment by Greigh** [comment] 2020-02-04 19:12
Sources: https://ghostbin.co/paste/unser

**Comment by Greigh** [comment] 2020-02-04 19:14
Now the crash is happening on open. 
Crash log: https://ghostbin.co/paste/8y3b7
Sources: https://ghostbin.co/paste/unser

**Comment by wstyres** [comment] 2020-02-04 20:04
It appears that this issue was caused by a Zalgo string in [https://repo.litten.sh](https://repo.litten.sh)'s Release file which in turn would cause Zebra to crash when trying to organize the user's sources into alphabetical order. The issue was mitigated by the owner of the repository by shortening the Origin string (which is used for sorting) and the repo should now be able to be used in Zebra.

If you are still experiencing this crash with Litten's repo installed, you might have to delete Zebra's database located at `/var/mobile/Library/Application Support/xyz.willy.zebra/zebra.db` so that Zebra will re-cache the information and be able to sort the new string.

I still plan to fix the underlying issue with Zebra so I'll leave the issue open but for now that is the temporary solution.

**Comment by wstyres** [comment] 2020-02-05 18:07
Put a small fix in 84839ecf5d66594d7005f4b21fc984112431f625 for 1.0.7 which will be released soon.

**Comment by wstyres** [comment] 2020-02-05 18:18
1.0.7 is out now, Zebra should be able to be updated from Cydia to 1.0.7 and the crashes will resolve. If not, please see the steps above to resolve the issue.

**Closed** 2020-02-05 18:18 UTC
Labels: bug, scheduled, sources
