### ISSUE TITLE
White bars on depictions through search

### ISSUE THREAD

**Issue by SlightlyPeckish** [wstyres/Zebra#1110] opened 2020-04-20 19:27 UTC
**Describe the bug**
White border on tweak pages through search

**To Reproduce**
Search for any tweak and once tapped on there are white bars at the left and right

**Expected behavior**
White bars at the left and right

**Screenshots**
![9F41518A-B23C-4748-88F2-DA64C58AFF89](https://user-images.githubusercontent.com/21175434/79791176-c9825c80-8344-11ea-98ab-94dfbf15132d.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1~beta6
 - Device Type [e.g. iPhone or iPad]: iPhone XR 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver 

**Crash Log or System Log**
It doesn’t crash

**Additional context**
This only occurs when looking at depictions through search when opening a tweaks depiction through the repo there are no white bars

**Comment by wstyres** [comment] 2020-04-20 19:31
Duplicate of #1109

**Closed by wstyres** 2020-04-20 19:31 UTC
Labels: bug
