### ISSUE TITLE
Filtering bug

### ISSUE THREAD

**Issue by aestheticsglowexe** [wstyres/Zebra#1052] opened 2020-04-06 20:55 UTC
**Describe the bug**
most of the authors i want to filter don't show up when i search.

**To Reproduce**
go to settings > filters > authors / add filter and then search for the authors you want to filter.

**Expected behavior**
the authors don't show up.

**Screenshots**
![5BB676DE-2D76-4D32-8015-1A534C88FA9A](https://user-images.githubusercontent.com/40965557/78604025-68915980-7859-11ea-8736-e83c76065869.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1~beta4
 - Device Type [e.g. iPhone or iPad]: iphone 8 plus
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Crash Log or System Log**
//

**Additional context**
//

**Comment by absidue** [comment] 2020-04-06 21:22
Duplicate of #1034

**Closed** 2020-04-06 21:31 UTC
Labels: bug
