### ISSUE TITLE
No payment required when using swipe actions

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#843] opened 2020-02-01 22:29 UTC
**Describe the bug**
I am logged in to Packix and the cost does show instead of Install button in depiction page. If I press that it will take me to authenticate and to paypal. However, if I didn’t go to depiction page, and just slide and press install, it would put into queue.

**Expected behavior**
Authenticate also.

**Additional context**
I hope it would be fix in 1.1

**Comment by wstyres** [comment] 2020-03-25 01:12
Is this issue fixed in 1.1?

**Comment by wstyres** [comment] 2020-03-29 03:11
Realized this is a duplicate of #739 so I'll consolidate this information there.

**Closed by wstyres** 2020-03-29 03:11 UTC
Labels: bug, purchases
