### ISSUE TITLE
"Update All" button not showing up

### ISSUE THREAD

**Issue by allendude51** [wstyres/Zebra#1552] opened 2020-09-14 15:30 UTC
**Describe the bug**

The botton to update all isn't there anymore

**To Reproduce**

Have a package that needs updating

**Expected behavior**

I expected the bittokbto be there so I can easily update multiple packages

**Screenshots**

![E36F1522-4636-482D-83D8-3FFD879DBB29](https://user-images.githubusercontent.com/51012842/93101632-21ad5880-f670-11ea-9662-3cecf5ff61c3.png)

**Device Information:** 

 - iOS Version: <13.7>
 - Zebra Version: <1.2-beta4c>
 - Device Type: <iPhone X>
 - Jailbreak Type: <checkra1n>

**Crash Log or System Log**

**Additional context**

**Comment by eve0415** [comment] 2020-09-14 15:31
Duplicate of #1535

**Closed** 2020-09-14 15:33 UTC
Labels: bug
