### ISSUE TITLE
Packages tab doesn't take update the available upgrades list even after I update the packages.

### ISSUE THREAD

**Issue by Davetheminion101** [wstyres/Zebra#165] opened 2019-06-10 03:21 UTC
I installed the tweaks Pluto and Improvify some time ago and since then both of those packages have received updates. I can't remember whether I upgraded them through cydia or Zebra but after that I went on Zebra and refreshed sources and it said that the upgrades were still available. So I again upgraded through Zebra but the list of available upgrades didn't change. Since then I have used Unc0ver's Restore RootFS feature and gone down to 3.0.0b49. But miraculously Zebra still said I had upgrades available for Pluto and Improvify even when I didn't have those tweaks installed. Recently today Eclipse Dark Mode and Axon got upgrades and now they also won't disappear from the upgrade list despite being upgraded already.

**Comment by wstyres** [comment] 2019-06-11 01:43
Duplicate of #149. A fix will be available in the next beta.

**Closed by wstyres** 2019-06-11 01:43 UTC
