### ISSUE TITLE
Search function not working

### ISSUE THREAD

**Issue by rohitwasnik** [wstyres/Zebra#1326] opened 2020-05-28 07:03 UTC
**Describe the bug**
Just installed zebra beta and while searching nothing populates but when i click done it shows

**To Reproduce**
Steps to reproduce the behavior: Upgarde from stable to beta. Open zebra and search for anything

**Expected behavior**
A clear and concise description of what you expected to happen. Something shows in search

**Screenshots**

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <INSERT-HERE>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <INSERT-HERE>
 - Device Type [e.g. iPhone or iPad]: <INSERT-HERE>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <INSERT-HERE>

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by absidue** [comment] 2020-05-28 07:19
Duplicate of #1313

**Closed** 2020-05-28 21:53 UTC
Labels: bug
