### ISSUE TITLE
no queue label when adding package by 3D touch

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#792] opened 2020-01-05 03:36 UTC
**Describe the bug**
as the title says. The queue label doesn’t update when adding queue by 3d touch only

**To Reproduce**
3D touch any package, add anything to queue

**Expected behavior**
label

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0.2
 - Device Type [e.g. iPhone or iPad]: iphone 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Comment by wstyres** [comment] 2020-04-20 03:47
Can't reproduce on latest beta.

**Comment by eve0415** [comment] 2020-04-20 03:57
Can reproduce on package and search tab, but no on changes tab.
Latest beta, iOS 13.3

**Comment by wstyres** [comment] 2020-04-20 04:01
I can't reproduce on any tab, all package cells show their queue labels after a context menu action

**Comment by eve0415** [comment] 2020-04-20 04:09
How about downgrade queue?

**Comment by wstyres** [comment] 2020-04-20 04:10
hm, yes. Downgrade seems to be the only one I can find with an issue. Is this the case for you as well?

**Comment by eve0415** [comment] 2020-04-20 04:17
Yes, it happens for all tab.

**Comment by wstyres** [comment] 2020-04-20 04:18
But only for the downgrade queue correct?

**Comment by eve0415** [comment] 2020-04-20 04:18
yep

**Comment by eve0415** [comment] 2020-04-20 04:25
> Can reproduce on package and search tab, but no on changes tab.

Correction, can reproduce for paid packages

**Comment by wstyres** [comment] 2020-04-20 15:20
Alright, downgrades and purchased packages should be fixed as of d2464111ac1eb90324aa8c7da84f0218b5730220.

**Comment by wstyres** [comment] 2020-04-20 19:25
@eve0415 will leave this open for you to see if you can still reproduce, let me know or just close the issue

**Comment by eve0415** [comment] 2020-04-20 22:30
Can confirm that it has been fixed in beta 6, thx

**Closed** 2020-04-20 22:31 UTC
Labels: bug, low, queue, scheduled
