### ISSUE TITLE
Installed rweeks

### ISSUE THREAD

**Issue by D1mar0n** [wstyres/Zebra#89] opened 2019-05-15 05:13 UTC
Thank you for your work! I think the community will get an excellent manager for the final version! Please add to the installed tweaks section the tabs “recently installed”, “for professionals” as in Cydia - this is very convenient. Thank you in advance.

**Comment by wstyres** [comment] 2019-05-15 14:35
Duplicate of #49

**Closed by wstyres** 2019-05-15 14:35 UTC
Labels: enhancement
