### ISSUE TITLE
Unable to install packages. 

### ISSUE THREAD

**Issue by Jinpix** [wstyres/Zebra#316] opened 2019-08-30 07:05 UTC
**Describe the bug**
I am unable to install packages. After choosing one, tapping "install", then going to my queue and tapping "install" again, it shows the action log of the item being downloaded and installed, which appears to be successful. At the end, it gives me a "Done" button which takes me back to my package list. When I respring my device manually, nothing has changed and nothing has been installed. I've tried with tweaks, themes, and widgets. 

**To Reproduce**
Attempt to install a package. 

**Expected behavior**
I expect my desired packages to install. 

**Screenshots**
No screenshots available. 

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
   12.1.2
 - Zebra Version [e.g. 1.0\~beta1 or beta1]:
   beta20-2
 - Device Type [e.g. iPhone or iPad]:
   iPhone XS

**Crash Log or System Log**
No crash log available. 

**Additional context**

**Comment by wstyres** [comment] 2019-08-30 15:34
Could you provide a screenshot of the console page? Knowing what the log says will be useful.

**Comment by Jinpix** [comment] 2019-08-30 16:00
Yeah sorry about that.

**Comment by wstyres** [comment] 2019-08-30 16:19
If you attached an image on email I don't think it came through. I'd try uploading it to Imgur and pasting the link here.

**Comment by Jinpix** [comment] 2019-08-30 16:23
Here's the link:
https://imgur.com/a/CfleTE2

**Comment by PoomSmart** [comment] 2019-08-31 02:52
Possibly an issue with `apt` not being executed correctly.

**Comment by Jinpix** [comment] 2019-09-02 21:49
Any idea if I'd be able to fix that? Noticed the new version of Zebra
mentions something about APT compatibility, but I'm not able to download it
lol

**Comment by wstyres** [comment] 2019-09-03 12:57
Could you tell us which repo the tweak is on and also if this is a problem for this specific tweak or if it is every tweak?

**Comment by Jinpix** [comment] 2019-09-03 16:47
Actually the tweak that I sent a screenshot of was chosen at random just to
demonstrate the issue. That specific one is on the Nepeta repo (
http://repo.nepeta.me/), but the issue persists across all repos and all
tweaks that I try, including tweak updates.

**Comment by wstyres** [comment] 2019-09-04 21:09
Possibly to do with `supersling` not executing properly. We're not able to reproduce this. Could you uninstall Zebra and install again and see if the issue persists?

**Comment by Jinpix** [comment] 2019-09-04 21:15
I actually can't uninstall it. Sileo doesn't work for me either, meaning
nothing can be added to my queue or downloaded/uninstalled on there. I
contact support for Sileo and see if they can help fix that so that I can
move forward with fixing zebra. I'll get back to you when I get that worked
out.

**Comment by PoomSmart** [comment] 2019-09-07 11:15
Closed in favor of #328

**Closed by PoomSmart** 2019-09-07 11:15 UTC
Labels: bug, fixable
