### ISSUE TITLE
Clicking an “Add to Zebra” link does not work on the latest beta

### ISSUE THREAD

**Issue by Garydunlop00** [wstyres/Zebra#1518] opened 2020-08-28 11:00 UTC
**Describe the bug**
When you click on an “Add to Zebra” link it opens the zebra app but the pop up to add the source does not show

**To Reproduce**
Steps to reproduce the behavior: Find a repo with and “Add to Zebra” link and click it

**Expected behavior**
The zebra app should open and the add source pop up should show with the source url already in the box

**Screenshots**
If applicable, add screenshots to help explain your problem. N/A

**Device Information (please complete the following information):** iPhone X, IOS 13.5, OdysseyRa1n

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.5
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.2\~beta3b
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: OdysseyRa1n

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by eve0415** [comment] 2020-08-28 11:10
Duplicate of #1497

**Closed** 2020-08-28 13:06 UTC
Labels: bug
