### ISSUE TITLE
There is no update all option, and the tabs is staying in English even though My language is different. iPhone X iOS 13.5 checkra1n, zebra version 1.2~beta4a

### ISSUE THREAD

**Issue by TomerKILLer** [wstyres/Zebra#1537] opened 2020-09-10 10:15 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <INSERT-HERE>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <INSERT-HERE>
 - Device Type [e.g. iPhone or iPad]: <INSERT-HERE>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <INSERT-HERE>

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by absidue** [comment] 2020-09-10 11:16
Duplicate of #1535

Translations won't be added in the betas as a lot is still changing.

When reporting bugs please fill in the template instead of stuffing everything in the title. The template isn't just there for decoration, it's to provide structure, make it easier to read and prompt you for more detailed information.

**Comment by TomerKILLer** [comment] 2020-09-10 14:10
My bad. Thx

בתאריך יום ה׳, 10 בספט׳ 2020 ב-14:16 מאת absidue <notifications@github.com>:

**Closed** 2020-09-10 14:24 UTC
Labels: bug
