### ISSUE TITLE
Sources Blank When Opening/Refreshing & Search Crashes Unless Search History

### ISSUE THREAD

**Issue by jmillz369** [wstyres/Zebra#275] opened 2019-07-24 18:02 UTC
**Describe the bug**

When Zebra beta 19 is opened and it automatically refreshes the sources, the sources tab is blank until the refresh is finished. Only does this upon app opening. Refreshing manually does not reproduce this issue. Also when I upgraded from beta 18 to beta 19 the search field in the search tab would crash zebra when the keyboard is opened. This can be fixed though by clearing the search history. 

**To Reproduce**

Open Zebra and click the sources tab after opening. 

Use the search field under search tab when history is present and Zebra will crash if previous search history is present from beta 18.  

**Expected behavior**

The sources to appear during initial refresh when zebra is opened. For search history to be maybe cleared when upgrading from beta 18 (and maybe future beta releases if can not be resolved). 

**Screenshots**

https://imgur.com/a/7SZXlvf

**Device Information (please complete the following information):**

 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
iOS 12.2

 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
Beta 19

 - Device Type [e.g. iPhone or iPad]: 
iPhone 6s+

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

Unfortunately my crash log was deleted for the zebra crash from the search field crash. Sources refresh does not crash zebra.

**Comment by lol7344** [comment] 2019-07-25 14:38
I also reported the second issue a few days ago in #267. Wouldn't it be better to have two separate bug reports?

**Comment by jmillz369** [comment] 2019-07-25 18:17
Probably now that I think about. Will do going forward. Didn’t see your open issue before posting 🤷‍♂️

**Comment by Muirey03** [comment] 2019-07-26 01:55
I experience this issue too so can shed a little more light on it. The issue is purely UI based it would seem. The sources are actually still there (all the ZBRepo objects are active and working correctly), you can still search for packages, packages show the correct repo, etc. I've only been experiencing this since the latest beta release.

**Comment by wstyres** [comment] 2019-08-31 01:00
Is this issue still able to be reproduced as of beta 20? I'm not able to reproduce what you are describing.

**Comment by jmillz369** [comment] 2019-08-31 01:03
Nope. I can no longer reproduce these issues. I think these have been fixed with the recent updates.

**Comment by wstyres** [comment] 2019-08-31 01:03
Perfect, I will close the issue.

**Closed by wstyres** 2019-08-31 01:03 UTC
Labels: bug
