### ISSUE TITLE
Conflicts doesn’t gets handled properly (not adding to remove queue and can’t proceed with installation)

### ISSUE THREAD

**Issue by yur1xpp** [wstyres/Zebra#1406] opened 2020-06-08 05:24 UTC
**Describe the bug**
I think this bug was addressed in previous version, but somehow gets it way into v1.1.10. After installed FLEXing, installation of FLEXall will not be allowed as both package conflict with each other. FLEXing is not added to the remove queue.

**To Reproduce**
1. Install FLEXing
2. Install FLEXall

**Expected behavior**
FLEXing will be added to remove queue and automatically be removed, and allows the installation of FLEXall

**Screenshots**
https://imgur.com/a/E0Gsznk

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.5
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1.10
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by eve0415** [comment] 2020-06-09 23:35
Duplicate of #1143

**Closed** 2020-06-12 11:53 UTC
Labels: bug
