### ISSUE TITLE
Refresh spinner does not display correctly in OLED dark mode

### ISSUE THREAD

**Issue by mattp12** [wstyres/Zebra#681] opened 2019-12-10 01:37 UTC
Describe the bug:
In OLED dark mode, the spinner to refresh packages doesn't display correctly only on the packages tab. The other dark mode styles are not affected. Additionally, the spinner displays correctly in light mode.

1. Turn OLED dark mode on, tap the packages tab at the bottom, and swipe down.

Expected behavior:
For the spinner to display correctly.

Screenshots:
N/A, see videos below

Device Information (please complete the following information):
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.2.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0 beta 32
 - Device Type [e.g. iPhone or iPad]: iPhone 8+
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

Crash Log or System Log:
N/A

Additional context:
Video showing dark mode spinner: https://www.youtube.com/watch?v=Zsdda_G2QGk
Video showing light mode spinner behaving correctly: https://www.youtube.com/watch?v=ixSccnWZVuQ

**Comment by PoomSmart** [comment] 2019-12-14 04:21
Fixed as of 23cc886eddc0426d77ccd625537d1ad1d0383637

**Comment by wstyres** [comment] 2019-12-14 22:14
Please test in beta 33 to see if the issue is resolved.

**Comment by mattp12** [comment] 2019-12-15 04:46
> Please test in beta 33 to see if the issue is resolved.

This appears to be fixed as of beta 33.

**Closed** 2019-12-15 05:23 UTC
Labels: UI, bug, scheduled
