### ISSUE TITLE
Search does not work

### ISSUE THREAD

**Issue by doo3n** [wstyres/Zebra#1330] opened 2020-05-28 15:58 UTC
![251318BF-6C8C-4794-9AD4-F36B09DDC665](https://user-images.githubusercontent.com/42841021/83164334-c6814580-a114-11ea-85ef-66abc0dda9fe.png)
**Describe the bug**

Search does not work

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [13.5]:
 - Zebra Version [Beta 1 of Zebra 1.2]:
 - Device Type [iPhone x]:
 - Jailbreak Type [unc0ver 5.0.1]:

**Comment by absidue** [comment] 2020-05-28 16:50
Duplicate of #1313

**Closed** 2020-05-28 21:53 UTC
Labels: bug
