### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by aestheticsglowexe** [wstyres/Zebra#916] opened 2020-02-29 05:13 UTC
**Describe the bug**
repos/tweaks aren't loading correctly i guess.

**To Reproduce**
tap on any tweak to view it.

**Expected behavior**
no description just a blank space, it takes you to in-app web browser page to show you the tweak description and all the information instead of loading it all in zebra.

**Screenshots**
![20A658B2-1C42-4CA5-837F-1B23A62AF724](https://user-images.githubusercontent.com/40965557/75601220-c3e56480-5ac1-11ea-94d0-a549dc4f604e.jpeg)
![3D957421-13A4-4553-8D83-AFE507025FBC](https://user-images.githubusercontent.com/40965557/75601221-c6e05500-5ac1-11ea-8a06-20e8328a5e81.jpeg)

**Device Information (please complete the following information):**
 - iOS Version: 13.3
 - Zebra Version: 1.1~beta2
 - Device Type: iPhone 8 plus
 - Jailbreak Type: unc0ver

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**
this happened after i updated to the latest beta today.

**Comment by PoomSmart** [comment] 2020-02-29 05:58
Duplicate of #906

**Closed by PoomSmart** 2020-02-29 05:58 UTC
Labels: bug
