### ISSUE TITLE
Sources list appears blank while refreshing

### ISSUE THREAD

**Issue by lol7344** [wstyres/Zebra#278] opened 2019-07-25 10:02 UTC
**Description**
The Sources list appears as if it's empty and the loading icon keeps rotating.

**How to reproduce**
1. Open Zebra
2. Tap on "Sources"
3. Wait forever

**Expected behavior**
All sources should be shown with their respective loading icon until all repos have been updated.

**Screenshots**
Video showcasing the problem: https://youtu.be/K1ARuagVwPU

**Device Information (please complete the following information):**
 - iOS Version: 12.2
 - Zebra Version: 1.0 beta19
 - Device Type: iPhone 6

**Crash Log or System Log**
Not crashing

**Additional context**
Randomly tapping other bottom buttons, searching something and then coming back to sources list sometimes makes the sources appear again.

**Comment by Muirey03** [comment] 2019-07-25 12:05
I experience this issue too so can shed a little more light on it. The issue is purely UI based it would seem. The sources are actually still there (all the ZBRepo objects are active and working correctly), you can still search for packages, packages show the correct repo, etc. I've only been experiencing this since the latest beta release.

**Comment by PoomSmart** [comment] 2019-07-25 14:31
Closed in favor of #275

**Closed by PoomSmart** 2019-07-25 14:31 UTC
Labels: bug
