### ISSUE TITLE
Restart Springboard UI bug

### ISSUE THREAD

**Issue by gerbil-snot** [wstyres/Zebra#953] opened 2020-03-16 01:34 UTC
**Describe the bug**
The UI for the Restart Springboard button is completely whited out (see screenshot below)

**To Reproduce**
Preform any action with any tweak (install, reinstall, remove)

**Screenshots**
![99EBD0ED-617C-4008-BEF3-41677C482674](https://user-images.githubusercontent.com/29874563/76715863-1b0f4a00-66fc-11ea-8361-d56e4370f6b2.jpeg)

**Device Information**
 - iOS Version: 13.3
 - Zebra Version: 1.1~beta2-1
 - Device Type: iPhone Xs Max 
 - Jailbreak Type: unc0ver

**Comment by wstyres** [comment] 2020-03-16 02:25
Duplicate of #930

**Closed by wstyres** 2020-03-16 02:25 UTC
Labels: bug
