### ISSUE TITLE
More slight adjustments (consistency)

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#640] opened 2019-11-29 19:08 UTC
**Describe the solution you'd like**

There are quite a few slight changes I think should be made to Zebra for the sake of consistency. *This GitHub issue could be updated as I find more issues.

According to the Apple Human Interface Guidelines apps should use "uniform terminology" that behaves in a way that people expect. (https://developer.apple.com/design/human-interface-guidelines/ios/overview/themes/)

1. Therefore I recommend changing "Graphics" in settings to "Interface" as that's the term used by Apple throughout their operating systems. It's even in the name of the guidelines.
2. I suggest that you change "Search while Typing" to "Live Search" as it's simpler and the actual name of the feature.
3. I suggest that "Tint Color" be changed to "Accent Color" as the HIG suggests using uniform terminology and accent color is the term used by Apple in MacOS.
4. I suggest removing the icon in front of "Report a Bug" as the HIG suggests that graphics should only highlight important content. Currently it suggests that this setting is more important than the others. It also helps to harmonize the app as none of the other settings have icons while the cells on the homepage do have icons. Settings should be easy to read and removing the icon streamlines it.
5. The selected icon from the "change icon" setting should be moved to the right and aligned with all the other text options. This is because the HIG suggests interface elements should be consistent. Since all the other settings are set to the right this setting should be as well.
6. #636 & #637 
7. On the home page add an icon in front of the "Welcome to Zebra beta!" text as the homepage currently looks unbalanced as all the other options have icons. I suggest this for a similar reason I suggest removing an icon in point 4. Per the HIG graphics highlight important content. As the other cells on the homepage all have icons it is implying that this text is not as important. I suggest using the chosen alternative icon which should keep Zebra looking consistent.
8. I suggest changing the wishlist icon as it is currently the same as the stores icon. Per the HIG apps should behave the way people expect. I'd argue that the expected action for pressing elements with the exact same icon would be the exact same action. Perhaps a gift of some kind could function as an icon as that is something that is automatically associated with wishlists.
9. I suggest changing the icon for "Help translate Zebra!" for the same reason as point 8. Perhaps the Apple globe icon that is used for languages in Apple operating systems or "ABC" could be used as an icon.
10. I suggest moving the "Help translate Zebra!" element down below "Contributors" as the element has everything to do with contributing and nothing so do with social media. Per the HIG apps should behave the way people expect and be consistent. Grouping menu items together in an appropriate manner is just an extension of that.
11. "Enable Featured Packages" and "Enable News" should drop "enable" from their names to simplify the settings. Per the HIG apps should use uniform terminology. As settings in iOS and the settings available in Zebra don't have "enable" in their names, "enable" should be dropped from the two phrases that do include it. It is counterintuitive to turn off a setting with enable in it's name.

Screenshots:
![2F9F6E18-F73B-47C5-951D-DDEC75219F99](https://user-images.githubusercontent.com/51668635/69893213-816b8a80-130e-11ea-9881-79327fb163a7.jpeg)

![2312F887-A385-4515-BC61-B587904B9D63](https://user-images.githubusercontent.com/51668635/69889807-3d1ec100-12f3-11ea-8d54-503fb145c6df.jpeg)

**Comment by JakeValenzuela** [comment] 2019-12-01 04:47
Adding onto this... (Might have to read in numerical order for it to make sense)

## Graphic Bugs
1. From home screen, click settings, and return to home, and the screen is dragged down a bit.
2. Fix splash screen bug when application is loaded. Ignores if user is in dark mode, will flash white for a second then load the application.

## General Changes
1. Allow users to use the swipe gesture in settings.

## Home Graphic Changes
1. Completely remove the "Welcome to the ..." text and move everything up a bit.
2. Change order of the Info Section. Stores, Community Repos, Wish List, Changelog
3. Change icon of Wish List. Agreeing with worldlydev, it should be a present/gift logo of some sort.
4. Remove "Help me translate Zebra!" from the Community section and move it to where Credits are
5. Add Contribute on Github to the Community section (with a github logo)
6. Remove credits and put them under translate bar.
7. Change icon of Credits

## Setting Graphic Changes
1. In settings, remove the picture, zebra text, and version text. Replace with "Settings", follow same style as Home screen text.
2. Follow same font color/font size as home screen.
3. Remove the report a bug button and "information" section and move it all the way down.
4. First section should be "Interface", agreeing with worldlydev. Should go in this order "Change Icon" "Accent Color", then "Dark Mode". 
5. Change "Change Icon" to "Change App Icon". 
6. Move Icon to the right side
7. Space everything out similar to the home screen.
8. Remove "Enable" from Featured Packages and News.
9. Change "Search while Typing" to "Live Search", agreeing with worldlydev.
10. Move "Live Search" to Interface, below dark mode
11. Move Swipe Actions Display As below "Live Search" (swipe actions.. could use a better name)
12. Add a space between the news section and the advanced section.
13. Move all "Advanced" buttons into a separate menu once you click the "Advanced" button.
14. I would add an icon for each setting, but I'd have to see once all these changes are in place.

**Comment by worldlydev** [comment] 2019-12-03 15:01
> Adding onto this... (Might have to read in numerical order for it to make sense)....

Interesting how we share some opinions but not all.


Not sure what you mean in general changes 1. 

I think home graphics changes 1 (why?), 2 (why?), 7 (why and to what?) and settings graphics change 1 (why?) are unnecessary.

Settings graphic change 14 would be worse. No other iOS settings have icons and settings should be as easy to read as possible. It doesn't match the design of the OS. It would be more cluttered and less streamlined.

**Comment by JakeValenzuela** [comment] 2019-12-03 15:21
1. Swipe gestures are able to be used everywhere else in the app except settings.

1. Kinda pointless to have that text for the actual release, the big "Home" text at the top kinda does the job. 
2. Stuff should be in order of most important to least. Changelog placement is debatable.
7. Credits icon shows a URL link, when it isn't a link at all. The "Translate" button is, so it makes more sense to leave that. Change it to a list/notepad, heart, etc.

1. The top of settings is pretty useless and takes up a big chunk of space. Just remove it. Also would make it consistent with the home screen layout.

14. As I said before, I'd have to see once all the changes are done.

**Comment by worldlydev** [comment] 2019-12-03 15:39
> 1 - Swipe gestures are able to be used everywhere else in the app except settings....

Gotcha. Thanks for responding so fast.

General 1 - Pretty sure this is implemented natively in iOS 13. Except as a swipe down instead of swipe from left. Could see why you would want it. Think it should be left as is. DetailViewController is still the best type of page for the settings.

Home 1 & Settings 1 - Understand. You are probably right about it looking better. Personally I think it makes Zebra look unique and welcoming but I probably wouldn't care if they were removed. So after thinking a little about it I feel they could be removed. I generally prefer things streamlined and consistent and this would definitely do that.

Settings 14 - lol all I can say is no. 


Those are my takes. Other than what is written in this comment I'm in complete agreement. Thanks for your reasoning for the previous points of contention.

Would love to hear your opinions and takes on this @wstyres

**Comment by wstyres** [comment] 2019-12-04 01:22
Most of these suggestions are going to be implemented in the 1.1 version for Zebra (or 1.2 depending on how large the change is). 1.1 is meant to be a smaller UI update for usability and 1.2 is meant to be the larger redesign but we'll see how those numbers play out as the Zebra updates progress.

Andrew and I have talked about it and here are our thoughts on all of the issues. There were a lot of them so I've included the suggestions and my response in a sub-bullet.

For @worldlydev's comments:
- Changing "Graphics" in settings to "Interface" as that's the term used by Apple throughout their operating systems.
  - Easy enough, I'll change it in a future version.
- Change "Search while Typing" to "Live Search" as it's simpler and the actual name of the feature.
  - Hopefully I can do away with Search while Typing altogether and build a faster default search. For now, this can also be changed. It will also help with translations being shorter.
- "Tint Color" be changed to "Accent Color" as the HIG suggests using uniform terminology and accent color is the term used by Apple in MacOS.
  - Again, easy enough, will be changed in a future version.
- I suggest removing the icon in front of "Report a Bug"
  - Report a Bug will most likely be moved to the homepage again (if it even remains in the app at all). Doesn't make much sense for a user to go into settings to report an issue.
- The selected icon from the "change icon" setting should be moved to the right
  - Yep, makes sense to me
- #636 and #637 
  - For #636 I still think it could use some work, it is rounded but some extra padding would be nice
  - As for #637, I'm planning on redesigning this controller to allow for more credit to the authors so I'll change the names of the icons when I get around to that
- Add an icon in front of the "Welcome to Zebra beta!"
  - Not _too_ interested in changing this, the text will disappear for the redesign (and maybe in 1.1) but I'll see what I can work out. The box itself doesn't make much sense but the problem is what to replace it with.
  - I also don't think adding an icon will help a whole lot. The title isn't that important so I don't see a reason why an icon should be there to indicate which app icon you currently have selected.
- Change the wishlist icon as it is currently the same as the stores icon
  - Yep, whenever @aabosh is able to, we can do that.
- Change the icon for "Help translate Zebra!"
  - Yep, same as above, whenever @aabosh is available.
- Move the "Help translate Zebra!" element down below "Credits"
  - I see it more as a "Community" aspect and not so much a "Social" aspect. I don't really think it should be on the homepage at all to be honest and should either be in Settings or Credits as a submenu but I placed it there temporarily.
- "Enable Featured Packages" and "Enable News" should drop "enable" from their names
  - That makes sense, this will probably be done before 1.0

For @JakeValenzuela's comments:
- Navigation bar bug in home/settings
  - I know about this, still working on a way around it
- Launch Screen coloring
  - This will be fixed on iOS 13 once we adopt native dark mode (probably in 1.1) but theres no way to change the launch screen on anything below 13.
- Allow users to use the swipe gesture in settings
 - By Swipe Gestures do you mean like swiping on rows? Doesn't make much sense for this to be a setting selection feature. I haven't seen it anywhere else in iOS.
- Completely remove the "Welcome to the ..." text and move everything up a bit.
 - See my comment above from @worldlydev's suggestions
- Change order of the Info Section. Stores, Community Repos, Wish List, Change Log
  - How would you change the ordering? Stores, Wish List, and Community Repos are most likely to move with the redesign so for now I think they're fine where they are. We just haven't figured out where to put them in the redesign yet.
- Change icon of Wish List.
  - See my response to @worldlydev above
- Remove "Help me translate Zebra!" from the Community section and move it to where Credits are
  - See my response to @worldlydev above
- Add Contribute on Github to the Community section (with a github logo)
  - Not a bad idea, we'll consider this.
- Remove credits and put them under translate bar.
  - Remove credits?
- Change icon of Credits
  - See my response to @worldlydev above
- Remove the picture, zebra text, and version text. Replace with "Settings", follow same style as Home screen text.
  - Yeah, I think the header is quite ugly so it will be removed eventually as I've been meaning to for awhile.
- Follow same font color/font size as home screen.
  - This has to do with table view styles but can be easily changed to removing a lot of the theming that was done to it (for some reason)
- Remove the report a bug button and "information" section and move it all the way down.
  - See my response to @worldlydev above regarding the icon of the Report a Bug cell
- First section should be "Interface", agreeing with worldlydev. Should go in this order "Change Icon" "Accent Color", then "Dark Mode".
 - Is there any specific reasoning to this?
- Change "Change Icon" to "Change App Icon".
  - It would probably be somewhere along the lines of "Current Icon" if we change it along with @worldlydev's comment about "Enable" and switches, settings shouldn't be "actions" really and should rather state the settings and display its current value.
- Move Icon to the right side
  - See my response to @worldlydev above
- Space everything out similar to the home screen.
  - Again, has to do with table view styles, this can be changed
- Remove "Enable" from Featured Packages and News.
  - See my response to @worldlydev above
- Change "Search while Typing" to "Live Search", agreeing with worldlydev.
  - See my response to @worldlydev above
- Move "Live Search" to Interface, below dark mode
  - Again, any particular reasoning for the ordering here? If so, I'd like to hear it because I don't really see it. I agree there should be some reasoning to the settings placement if not taking most things and putting them in sub sections like iOS does it.
- Move Swipe Actions Display As below "Live Search" (swipe actions.. could use a better name)
  - See my previous response about "Live Search" I do agree that swipe actions could be worded better. It does cause some issues with translation
- Add a space between the news section and the advanced section.
  - That would probably go along with changing up the table view style
- Move all "Advanced" buttons into a separate menu once you click the "Advanced" button.
  - Great idea! Goes with my statement above about sub-sections in settings
- I would add an icon for each setting, but I'd have to see once all these changes are in place.
  - This doesn't make much sense, there isn't going to be an icon that will accurately describe each setting so the title does fine most of the time. I'm also thinking about adding more detailed descriptions to some settings that need it in their sub-menus.

Zebra 1.0 is mostly just a functional demo. The UI was an afterthought mostly. We do plan on redesigning it in a future update (hopefully that won't take forever) and you can see a sneak peak [here](https://twitter.com/getzebra/status/1168212560828686336?s=21)

That's all I can really think of for now. There are a TON of small changes that we're going to make to the UI of Zebra that I can't quite think of now but keep the suggestions coming. The worst case if you make a suggestion is we say no and move on but your suggestion could be something that we have not thought about before and we will implement to improve the UX.

**Comment by wstyres** [comment] 2019-12-06 05:14
Did a little bit of work on this today, let me know what you think.

![Simulator Screen Shot - iPhone 11 - 2019-12-06 at 00 12 36](https://user-images.githubusercontent.com/19736790/70297754-44474280-17bd-11ea-9124-dec91f530578.png)
![Simulator Screen Shot - iPhone 11 - 2019-12-06 at 00 12 40](https://user-images.githubusercontent.com/19736790/70297760-46a99c80-17bd-11ea-9e44-4438b16f3038.png)

**Comment by worldlydev** [comment] 2019-12-06 05:24
> Did a little bit of work on this today, let me know what you think.
> 
> ![Simulator Screen Shot - iPhone 11 - 2019-12-06 at 00 12 36](https://user-images.githubusercontent.com/19736790/70297754-44474280-17bd-11ea-9124-dec91f530578.png)
> ![Simulator Screen Shot - iPhone 11 - 2019-12-06 at 00 12 40](https://user-images.githubusercontent.com/19736790/70297760-46a99c80-17bd-11ea-9e44-4438b16f3038.png)

Looking good

**Comment by wstyres** [comment] 2020-01-12 00:29
App Icon is displayed next to "App Icon" on the right now as of 1f0393dc0704751b8ada8593052d3d7cea4d9367.

**Closed by wstyres** 2020-01-12 00:29 UTC
Labels: settings, suggestion
