### ISSUE TITLE
Packages not disappearing after upgrade

### ISSUE THREAD

**Issue by JamieBerghmans** [wstyres/Zebra#157] opened 2019-06-06 12:03 UTC
**Describe the bug**
After updating a tweak and respringing, it will still show it in the updates section ewen though it is up to date. Only fixable by manually doing a "Drop tables and refresh".

**To Reproduce**
Update any tweak, respring, and check for updates again.

**Expected behavior**
The packages should not be shown in the update screen after updating.

**Device Information (please complete the following information):**
 - iOS 12.1.1b3
 - latest Zebra version
 - iPhone

**Comment by PoomSmart** [comment] 2019-06-06 12:22
Duplicate of #149

**Closed by PoomSmart** 2019-06-06 12:22 UTC
Labels: bug
