### ISSUE TITLE
Packages show up too many times and tweak descriptions always load in a pop up safari browser

### ISSUE THREAD

**Issue by ivanchau14** [wstyres/Zebra#910] opened 2020-02-28 22:12 UTC
Newest Zebra version
iPhone XS Max iOS 13.3
All packages I search show up like 10 times
All packages show their description in a popular browser instead of in the actual Zebra app
![14994A50-8048-4098-B380-3C6F9560E8C3](https://user-images.githubusercontent.com/44682698/75591344-593a1780-5a34-11ea-9ffe-0adab13acb0e.png)
![419BE9B4-869D-4F00-A178-13D9812AF574](https://user-images.githubusercontent.com/44682698/75591379-71119b80-5a34-11ea-9fca-e8bc2b6d8d7b.png)

**Comment by wstyres** [comment] 2020-02-28 22:42
Duplicate of #909 and #906

**Closed by wstyres** 2020-02-28 22:42 UTC
Labels: bug
