### ISSUE TITLE
Auto uninstall

### ISSUE THREAD

**Issue by EagleStrike0** [wstyres/Zebra#158] opened 2019-06-08 16:49 UTC
**Describe the bug**
Whenever you install Zebra it automatically tries to uninstall and adds it to the queue.

**To Reproduce**
Step 1. Install Zebra 

**Expected behavior**
To not be in the the queue

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [ iOS 12.0]: 
 - Zebra Version [1.0\~beta13]: 
 - Device Type [iPhone]: 

**Crash Log or System Log**
Non existent

**Additional context**

**Comment by wstyres** [comment] 2019-06-11 01:44
I can't reproduce this, could you provide a video of what you're experiencing?

**Comment by Amplespencer** [comment] 2019-06-16 05:01
you have a tweak marked as conflicting with zebra. How? no clue. If you can’t provide any more info then it isn’t fixable.

**Closed** 2019-06-19 06:39 UTC
Labels: bug, invalid, question
