### ISSUE TITLE
[BUG] Zebra get unresponsive when trying to remove package 

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#641] opened 2019-11-30 00:08 UTC
**Describe the bug**

As the title says.

**To Reproduce**

Try to remove package in any way

**Expected behavior**

Make queue

**Screenshots**

![3D108FA3-F6C1-48E7-9D11-CF21CC98DE06](https://user-images.githubusercontent.com/40632436/69893167-c44e5200-1350-11ea-9870-f2ab5591e0c6.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta 30
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Additional context**

I don’t know if it’s only for me but it happen to me always.
Zebra isn’t freezing because the loading icon when loading sources are moving.

**Comment by wstyres** [comment] 2019-11-30 16:36
This is caused by the fix I implemented for #624. I'll see if I can work out another solution.

**Comment by wstyres** [comment] 2019-11-30 18:09
It is technically fixed as of f9881370395dbb429c03030124a204839942cf35 but calculating dependencies for removal is still a bit slow. I will continue to work on this before pushing out another beta.

**Comment by wstyres** [comment] 2019-11-30 18:41
Should be fixed (at about the same speed) as of 530e74e5a7776f1439074bf082cbed5715748784.

**Comment by eve0415** [comment] 2019-11-30 23:56
Can confirm it is fixed in beta 30-1

**Closed** 2019-11-30 23:55 UTC
Labels: bug, scheduled
