### ISSUE TITLE
“Upgradeable” packages persist even after upgrading

### ISSUE THREAD

**Issue by cmhaddox** [wstyres/Zebra#1335] opened 2020-05-29 01:33 UTC
**Describe the bug**
Packages update, yet stay in the update queue. When attempting to update them again, it says the newest version of these packages is installed, and it stays in the queue.

**To Reproduce**
1. Open Zebra
2. Refresh packages
3. diskdev-cmds and system-cmds remain in the upgrade queue
4. Attempt to upgrade packages
5. Packages still remain in queue

**Expected behavior**
Packages should upgrade normally or detect that the latest version of the packages is already installed and remove them from the queue.

**Screenshots**
I’ve added a screen recording here: 

https://gfycat.com/uniqueenchantedindianabat

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.5
 - Zebra Version [e.g. 1.0\~beta1 or beta1]:  1.2 beta1a
 - Device Type [e.g. iPhone or iPad]: iPhone 11 Pro Max
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Crash Log or System Log**
N/A

**Additional context**
None

**Comment by eve0415** [comment] 2020-05-29 01:34
Duplicate of #1310

**Closed** 2020-05-30 04:16 UTC
Labels: bug
