### ISSUE TITLE
/var/lib/dpkg/status error

### ISSUE THREAD

**Issue by iAzadx** [wstyres/Zebra#1008] opened 2020-03-30 09:53 UTC
**Describe the bug**
When I install any tweak or upgrade it I have the following error: parsing file /var/lib/dpkg/status near line 5568 package...
And then the tweak was not installed or upgrade.

**To Reproduce**
Choose a tweak
Install it

**Expected behavior**
I want to installation be successful

**Screenshots**
![C305D469-F5F3-40C7-97CE-B92C7B774F86](https://user-images.githubusercontent.com/62880069/77899337-da2b3f80-727c-11ea-94fe-feb43920c04d.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0.7
 - Device Type [e.g. iPhone or iPad]: iPhone 11
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Unc0ver 4.3.1

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by absidue** [comment] 2020-03-30 10:01
I have an idea what the cause is, to test my theory can you please run `cfversion` in MTerminal/NewTerm 2 or over ssh and tell me what the result is?

**Comment by iAzadx** [comment] 2020-03-30 10:28
Hi thanks for your Help !
I'm not able to install any tweak, so as MTerminal and NewTerm 2 😪
About over ssh, do you have any trick by usb câble from Mac OS ?

**Comment by iAzadx** [comment] 2020-03-30 10:37
I have Filza and it works fine, if it can be usefull

**Comment by oxi0de69** [comment] 2020-03-30 10:43
In future, i suggest you install OpenSSH and a terminal app straightaway in case you are in a similar situation. Since you cant install anything, you cant install OpenSSH or a terminal app, and unc0ver doesnt install OpenSSH by default. You could try rejailbreaking with the ssh only option in unc0ver to get SSH running on your device

**Comment by iAzadx** [comment] 2020-03-30 10:55
I resolve it.
I go to /var/lib/dpkg/status and edit it with filza
I go to the 5568 line where I find "Cy+lib corefoundation".
And I add a "1" in version section because it was empty, and know everything works.
Thanks Again.

**Comment by absidue** [comment] 2020-03-30 11:13
Now that you can install stuff again could you please follow the steps I outlined above, because it's a bug and should be fixed on Zebra's side so it doesn't happen to other people. I don't have an iPhone 11 so I can't test myself.

**Comment by iAzadx** [comment] 2020-03-30 11:17
Sure.
I do it with MTerminal.

![IMG_1536](https://user-images.githubusercontent.com/62880069/77906732-ba9a1400-7288-11ea-860f-e6ba77f4d8ac.png)

**Comment by absidue** [comment] 2020-03-30 11:20
Thank you

Weird not the result I was expecting.

Anyway you can replace the version number you set 1 before with the number output by that command to prevent other side effects from happening. (That is the number that is meant to be there.

**Comment by iAzadx** [comment] 2020-03-30 11:26
Ok perfect, 
Thanks Again

**Comment by absidue** [comment] 2020-04-03 23:45
I can confirm that the firmware.sh rewrite sets the core foundation version even if it's empty to at the start. Keep in mind though that firmware.sh and by extension the rewrite only gets automatically triggered when Zebra's startup daemon gets loaded. Manually running `/usr/libexec/zebra/firmware` in a terminal(MTerminal, NewTerm2, ...) or over ssh fixes the issue.

**Closed** 2020-04-14 00:27 UTC
Labels: bug, high, scheduled
