### ISSUE TITLE
Crash after import sources

### ISSUE THREAD

**Issue by iluwQaa** [wstyres/Zebra#147] opened 2019-06-02 17:09 UTC
App crashes when you try to open the tab with sources
Crash log:
Date: 2019-06-02 17:01:59 +0000
Process: Zebra
Bundle id: xyz.willy.Zebra
Exception type: NSInvalidArgumentException
Reason: A nil string was passed for sorting.
Culprit: Unknown
Device: iPhone 5s, iOS 12.1.1
Call stack:
0   CoreFoundation                      0x00000001b0820edc __exceptionPreprocess
1   libobjc.A.dylib                     0x00000001af9f1a40 objc_exception_throw
2   CoreFoundation                      0x00000001b0727594 -[NSCache init]
3   UIKitCore                           0x00000001ddb9d788 localizedObjectSort
4   CoreFoundation                      0x00000001b07bbb60 __CFSimpleMergeSort
5   CoreFoundation                      0x00000001b07bb6c8 CFSortIndexes
6   CoreFoundation                      0x00000001b0709a0c -[NSArray sortedArrayFromRange:options:usingComparator:]
7   CoreFoundation                      0x00000001b0710634 -[NSMutableArray sortedArrayFromRange:options:usingComparator:]
8   CoreFoundation                      0x00000001b0713030 -[NSArray sortedArrayUsingFunction:context:]
9   UIKitCore                           0x00000001ddb9d66c -[UILocalizedIndexedCollation sortedArrayFromArray:collationStringSelector:]
10  Zebra                               0x0000000100584cec Zebra + 281836
11  Zebra                               0x0000000100583024 Zebra + 274468
12  Zebra                               0x0000000100582fbc Zebra + 274364
13  libdispatch.dylib                   0x00000001b02596c8 _dispatch_call_block_and_release
14  libdispatch.dylib                   0x00000001b025a484 _dispatch_client_callout
15  libdispatch.dylib                   0x00000001b02069a4 _dispatch_main_queue_callback_4CF$VARIANT$mp
16  CoreFoundation                      0x00000001b07b0df4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
17  CoreFoundation                      0x00000001b07abcbc __CFRunLoopRun
18  CoreFoundation                      0x00000001b07ab1f0 CFRunLoopRunSpecific
19  GraphicsServices                    0x00000001b2a24584 GSEventRunModal
20  UIKitCore                           0x00000001dd9b34c0 UIApplicationMain
21  Zebra                               0x0000000100553ca0 Zebra + 81056
22  libdyld.dylib                       0x00000001b026abb4 start

**Comment by PoomSmart** [comment] 2019-06-02 17:13
Duplicate of #138

**Closed by PoomSmart** 2019-06-02 17:13 UTC
Labels: bug
