### ISSUE TITLE
Connection 

### ISSUE THREAD

**Issue by kmokhtar79** [wstyres/Zebra#1382] opened 2020-06-04 16:07 UTC
The issue I have is that the pop up for wireless data permission never appears after installing Zebra and opening the app for the first time. To fix this, I have to install a tweak - network disabler, and enable WiFi access for zebra, from the tweak. Then Zebra can connect normally right away.

**Comment by wstyres** [comment] 2020-06-07 20:53
Is this on a device purchased in China?

**Comment by kmokhtar79** [comment] 2020-06-13 04:14
Right

**Comment by wstyres** [comment] 2020-06-22 14:32
Duplicate of #1356

**Closed by wstyres** 2020-06-22 14:32 UTC
Labels: bug, question
