### ISSUE TITLE
No packages file for ...... repo

### ISSUE THREAD

**Issue by exodia9610** [wstyres/Zebra#878] opened 2020-02-22 02:32 UTC
**Describe the bug**
Whenever Zebra automatically refreshes sources upon opening the app, it shows this error for all sources. However, manually refreshing the sources after it refreshes the first time (by dragging down to refresh), no errors are produced.

**To Reproduce**
Wait 15 minutes then open Zebra so it refreshes sources automatically when it opens.

**Expected behavior**
To not show these errors.

**Screenshots**
![B3919EA2-1F37-4950-828E-E98F229589D0](https://user-images.githubusercontent.com/25361391/75084882-8fc8eb80-5577-11ea-89d5-86d3d6fd8350.png)

**Device Information (please complete the following information):**
 - iOS Version: 13.3
 - Zebra Version: 1.1~beta1 
 - Device Type: iPhone XR
 - Jailbreak Type: Unc0ver

**Comment by Greigh** [comment] 2020-02-22 02:42
![3094C003-57ED-4C1D-B598-364FA04EAE9D](https://user-images.githubusercontent.com/57759540/75085032-f952e680-54f2-11ea-8c55-7e5b4a2f2670.png)
Same issue.

**Comment by guifernandes27** [comment] 2020-02-22 13:30
![C61988AB-4353-4133-8B6E-9FC554B41608](https://user-images.githubusercontent.com/61352876/75093176-6059b500-555e-11ea-943e-ad30c2c2865e.png)

Same here.

**Comment by wstyres** [comment] 2020-02-27 18:15
I'm not able to reproduce with the repos shown in screenshots so it might be that Zebra is not reporting the correct errors properly.

**Comment by exodia9610** [comment] 2020-02-27 21:15
The errors seemed to have disappear over the past few days which is good, and also weird

**Comment by wstyres** [comment] 2020-02-28 02:44
Should be fixed as of 7f81558952529b2b513e4c8d492b57ce1e0ab471.

**Closed** 2020-02-28 19:42 UTC
Labels: bug, high, scheduled, sources
