### ISSUE TITLE
bug in packages 

### ISSUE THREAD

**Issue by RuTiC** [wstyres/Zebra#1341] opened 2020-05-29 07:34 UTC
![0977065C-EA5B-4944-B4A5-3CEFFC36954D](https://user-images.githubusercontent.com/55456982/83233665-b9596a80-a197-11ea-87bd-02d48346e732.png)
![0D22F27C-9028-4823-9A79-A491061983A9](https://user-images.githubusercontent.com/55456982/83233673-bbbbc480-a197-11ea-9f32-767f57649c04.png)
![E8B799F5-8BC1-4F27-9D59-6D11F056AEBD](https://user-images.githubusercontent.com/55456982/83233675-bc545b00-a197-11ea-8099-e94ef28cf7c7.png) 

-

there’s two tweaks still in packages page and everytime when im trying to update them nothing happen .. i aleardy have them when i was checking in cydia

**Comment by eve0415** [comment] 2020-05-29 07:34
Duplicate of #1310

**Closed** 2020-05-29 07:36 UTC
Labels: bug
