### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by TerMueNator** [wstyres/Zebra#1325] opened 2020-05-28 06:51 UTC
**Describe the bug**
Search returns no search result

**To Reproduce**
Search anything in search tab and nothing returns

**Expected behavior**
Return search result

**Screenshots**
![3E692300-3BEF-4834-BB0E-7F094C4F7ED3](https://user-images.githubusercontent.com/33093069/83108496-17c80f80-a0ea-11ea-8652-58a03c3b0154.png)

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.5
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.2 beta 1
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by absidue** [comment] 2020-05-28 07:19
Duplicate of #1313

**Closed** 2020-05-28 21:54 UTC
Labels: bug
