### ISSUE TITLE
Badges don’t disappear after upgrading and respringing

### ISSUE THREAD

**Issue by gerbil-snot** [wstyres/Zebra#876] opened 2020-02-22 01:49 UTC
**Describe the bug**
When updating packages that badge the Zebra app icon, the badges remain until after reopening Zebra and refreshing the sources. 

**To Reproduce**
1. Allow Zebra to check for updates
2. Optional: Exit app, see badge (if updates are available)
3. Update packages, respring
4. See error - badged icon remains

**Expected behavior**
Badges should disappear after the respring, and should not require an additional source refresh. 

**Screenshots**
N/A

**Device Information**
 - iOS Version: iOS 13.3
 - Zebra Version: 1.1~beta1
 - Device Type: iPhone Xs Max 
 - Jailbreak Type: unc0ver v4.0.3

**Comment by wstyres** [comment] 2020-02-22 01:55
Duplicate of #826

**Closed** 2020-02-22 03:43 UTC
Labels: bug
