### ISSUE TITLE
Ignore updates doesn’t work 

### ISSUE THREAD

**Issue by hamida321** [wstyres/Zebra#972] opened 2020-03-25 17:01 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by ry2x** [comment] 2020-03-25 17:48
Describe the bug
Ignore updates feature doesn't work under the specific conditions. 
I purchased and installed the package(lower version,it's called Muzik) and set the ignore updates  on other package manager(Cydia). 
I login other account on the Zebra, then Zebra says update available.
I don't want to update Musik, so I tap the Muzik cell and try to enable ignore updates.
Zebra display the only delete, I can't enable ignore update.

To Reproduce
Steps to reproduce the behavior:install the package needs purchase and downgrade, then logout the account on the Zebra. 

Expected behavior
A clear and concise description of what you expected to happen.

Screenshots
See: https://imgur.com/gallery/qlNeL0R
Device Information (please complete the following information):

iOS Version [e.g. 12.1.2 or 10.3.3]:13.3 and 13.3.1
Zebra Version [e.g. 1.0~beta1 or beta1]:
Device Type [e.g. iPhone or iPad]:iPhone and iPad
Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]:unc0ver and Checkra1n
Crash Log or System Log
Please provide a Crash Log to help us solve the issue.

Additional context
Add any other context about the problem here.

**Comment by wstyres** [comment] 2020-04-11 20:56
Looks like I fixed this at some point when re-doing the action system. Should be fixed in the next beta.

**Closed** 2020-04-14 00:28 UTC
Labels: bug, medium, packages, scheduled
