### ISSUE TITLE
[Bug] The respring button is missing

### ISSUE THREAD

**Issue by MrGcGamer** [wstyres/Zebra#812] opened 2020-01-11 16:58 UTC
**Describe the bug**
The respring button is missing when installing local debs 
**To Reproduce**
1. locate your deb
2. share it with Zebra
3. install
4. no respring button

**Expected behavior**
1. locate your deb
2. share it with Zebra
3. install
4. respring button

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]:  iOS 13.2.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0.5
 - Device Type [e.g. iPhone or iPad]: iPhone 6s
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: CheckRa1n

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment] 2020-01-11 16:59
Duplicate of #798

**Closed by wstyres** 2020-01-11 16:59 UTC
Labels: bug
