### ISSUE TITLE
Zebra crashes when adding repos from Clipboard

### ISSUE THREAD

**Issue by jmd-aKBar** [wstyres/Zebra#303] opened 2019-08-10 05:46 UTC
**Describe the bug**
Upon adding a Repo from the clipboard, the Zebra App (1.0~beta 20) crashes

**To Reproduce**
Step1. Copy a valid Repo address (e.g. https://repo.thireus.com/) to the clipboard
Step2. Go to the Sources tab. Upon being prompted to add the repo source, click yes. 

**Expected behavior**
Repo Source should be added and the repo packages should be displayed. 

**Screenshots**
N/A

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 11.3.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0~beta20
 - Device Type [e.g. iPhone or iPad]: iPhone 8 Plus (A1897)

**Crash Log or System Log**
CrashLog Saved at https://pastebin.com/4uY0FsYn

**Additional context**
After the crash, when you open the Zebra app and refresh sources, the newly added Repo is successfully added and the internal packages are shown properly after the refresh finishes.

**Comment by PoomSmart** [comment] 2019-08-10 06:18
Duplicate of #302

**Closed by PoomSmart** 2019-08-10 06:18 UTC
Labels: bug
