### ISSUE TITLE
[BUG] Zebra crashing when disabling featured packages after changing the type

### ISSUE THREAD

**Issue by absidue** [wstyres/Zebra#500] opened 2019-11-01 15:37 UTC
**Describe the bug**

Zebra crashes when disabling the featured packages setting after changing the featured type.

**To Reproduce**

1. Open Zebra's settings page
2. Toggle on the featured packages setting if it is switched off
3. Change the featured packages type
4.Toggle off featured packages

**Expected behavior**
It shouldn't crash

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 

- iOS Version: 12.4
- Zebra Version: Latest build of the master branch
- iPhone

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

Date: 01.11.19, 16:32
Process: Zebra
Bundle id: xyz.willy.Zebra
Device: iPhone X, iOS 12.4

Exception type: NSRangeException
Reason: *** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array
Culprit: Unknown
Call stack:
0   CoreFoundation                      0x0000000202f9a9a4 __exceptionPreprocess
1   libobjc.A.dylib                     0x00000002021739f8 objc_exception_throw
2   CoreFoundation                      0x0000000202f143f8 _CFArgv
3   CoreFoundation                      0x0000000202e85e44 -[__NSArrayM objectAtIndex:]
4   Zebra                               0x00000001007eb36c Zebra + 144236
5   UIKitCore                           0x000000022f1d5e44 -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:isFocused:notify:]
6   UIKitCore                           0x000000022f1d9efc -[UICollectionView _updateVisibleCellsNow:]
7   UIKitCore                           0x000000022f1de8bc -[UICollectionView layoutSubviews]
8   UIKitCore                           0x000000022fd7b170 -[UIView(CALayerDelegate) layoutSublayersOfLayer:]
9   QuartzCore                          0x00000002074d7c60 -[CALayer layoutSublayers]
10  QuartzCore                          0x00000002074dcc08 CA::Layer::layout_if_needed(CA::Transaction*)
11  UIKitCore                           0x000000022fd671a4 -[UIView(Hierarchy) layoutBelowIfNeeded]
12  UIKitCore                           0x000000022fd6d8f0 +[UIView(Animation) performWithoutAnimation:]
13  UIKitCore                           0x000000022fad53f4 __46-[UITableView _updateWithItems:updateSupport:]_block_invoke_2
14  UIKitCore                           0x000000022fd6f25c +[UIView(UIViewAnimationWithBlocks) _setupAnimationWithDuration:delay:view:options:factory:animations:start:animationStateGenerator:completion:]
15  UIKitCore                           0x000000022fd6f79c +[UIView(UIViewAnimationWithBlocks) animateWithDuration:delay:options:animations:completion:]
16  UIKitCore                           0x000000022fad4808 -[UITableView _updateWithItems:updateSupport:]
17  UIKitCore                           0x000000022facce28 -[UITableView _endCellAnimationsWithContext:]
18  UIKitCore                           0x000000022fae30c8 -[UITableView endUpdates]
19  Zebra                               0x00000001007eb024 Zebra + 143396
20  CoreFoundation                      0x0000000202f0ba28 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__
21  CoreFoundation                      0x0000000202f0b9f4 ___CFXRegistrationPost_block_invoke
22  CoreFoundation                      0x0000000202f0aee8 _CFXRegistrationPost
23  CoreFoundation                      0x0000000202f0ab94 ___CFXNotificationPost_block_invoke
24  CoreFoundation                      0x0000000202e84474 -[_CFXNotificationRegistrar find:object:observer:enumerator:]
25  CoreFoundation                      0x0000000202f0a644 _CFXNotificationPost
26  Foundation                          0x00000002038f36f4 -[NSNotificationCenter postNotificationName:object:userInfo:]
27  Zebra                               0x000000010080cfb4 Zebra + 282548
28  Zebra                               0x000000010080d2e4 Zebra + 283364
29  Zebra                               0x000000010080c13c Zebra + 278844
30  UIKitCore                           0x000000022fae6320 -[UITableView _selectRowAtIndexPath:animated:scrollPosition:notifyDelegate:]
31  UIKitCore                           0x000000022fae6584 -[UITableView _userSelectRowAtPendingSelectionIndexPath:]
32  UIKitCore                           0x000000022f8ef0ac _runAfterCACommitDeferredBlocks
33  UIKitCore                           0x000000022f8ddbfc _cleanUpAfterCAFlushAndRunDeferredBlocks
34  UIKitCore                           0x000000022f90aa6c _afterCACommitHandler
35  CoreFoundation                      0x0000000202f2bd08 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
36  CoreFoundation                      0x0000000202f26a30 __CFRunLoopDoObservers
37  CoreFoundation                      0x0000000202f26fac __CFRunLoopRun
38  CoreFoundation                      0x0000000202f267c0 CFRunLoopRunSpecific
39  GraphicsServices                    0x000000020512779c GSEventRunModal
40  UIKitCore                           0x000000022f8e3c38 UIApplicationMain
41  Zebra                               0x00000001007ec288 Zebra + 148104
42  libdyld.dylib                       0x00000002029ea8e0 start

**Additional context**

**Comment by absidue** [comment] 2019-11-01 15:45
Sorry, accidentally submitted it unfinished

**Comment by wstyres** [comment] 2019-11-01 19:13
I'm not able to reproduce the issue, could you provide a video?

**Comment by PoomSmart** [comment] 2019-11-02 04:12
Fixed in https://github.com/wstyres/Zebra/commit/76008f30d6d97051a635262576c8f9f8838e09fa

**Closed** 2019-11-02 17:13 UTC
Labels: bug, scheduled
