### ISSUE TITLE
Add an “Add to BlockList” in the tweak depiction screen for quick blocking of tweak dev’s

### ISSUE THREAD

**Issue by Garydunlop00** [wstyres/Zebra#1088] opened 2020-04-15 03:22 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wstyres** [comment] 2020-04-15 16:28
Duplicate of #1037

**Closed by wstyres** 2020-04-15 16:28 UTC
Labels: suggestion
