### ISSUE TITLE
Community News missing

### ISSUE THREAD

**Issue by mainhathao** [wstyres/Zebra#1072] opened 2020-04-13 20:06 UTC
**Describe the bug**
The feature packages in Changes tab are just black

**Screenshots**
![27E6BDC8-0F62-4309-BA1A-90BBF188E23D](https://user-images.githubusercontent.com/48293860/79156338-e676d700-7dfc-11ea-988f-f3b705b65874.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1beta5
 - Device Type [e.g. iPhone or iPad]: iPhone XS Max
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by Greigh** [comment] 2020-04-13 21:12
Same on XS Max, unc0ver, 1.1 beta 5. 

https://cdn.discordapp.com/attachments/572784833714192395/699366298705985576/image0.png

**Comment by worldlydev** [comment] 2020-04-13 21:14
Can replicate this issue as well. 
iPhone 11 Pro, uncover, iOS 13.3

**Comment by wstyres** [comment] 2020-04-14 00:23
So this occurred because the reddit mods of /r/jailbreak appear to be testing out a new flair system which causes post parsing in Zebra to error and return no posts. I've contacted them and am waiting for a response so that I can better fix this issue. It looks like the issue is resolved for now but I'll leave the issue open until a fix is in place.

If the mods decide to implement these new flairs long-term I'll push out a new 1.1 beta as well as a 1.0.8 bug fix.

**Comment by wstyres** [comment] 2020-04-15 16:51
Fixed in 1.0.8 and 1.1~beta5-2

**Closed by wstyres** 2020-04-15 16:51 UTC
Labels: bug, changes, medium
