### ISSUE TITLE
Showing indicators for available updates but there aren’t any.

### ISSUE THREAD

**Issue by JonSingleton** [wstyres/Zebra#172] opened 2019-06-13 20:55 UTC
**Describe the bug**
Badge on zebra icon indicates available updates. When I open zebra, I see indication of available updates on the updates tab. These updates are not new, they’ve already been installed. 
Refreshing does remove the indicator, but clicking on the updates tab brings the indicator back.
These updates are not ignored (saw mention of this in changelog, different issue I guess).

**To Reproduce**
Steps to reproduce the behavior: mentioned above.

**Expected behavior**
To no longer see indications of updates being available when there are not.

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.2
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: latest
 - Device Type [e.g. iPhone or iPad]: iPhone XR.

**Crash Log or System Log**
no Crashes occurring.

Edit: the additional context from https://github.com/wstyres/Zebra/issues/149 resolves it. Until another update.

**Comment by PoomSmart** [comment] 2019-06-14 01:38
Duplicate of #149

**Closed by PoomSmart** 2019-06-14 01:38 UTC
Labels: bug
