### ISSUE TITLE
When adding a list of multiple repos that contain BigBoss/ZodTTD/ModMyI, these repos do not show up

### ISSUE THREAD

**Issue by captinc** [wstyres/Zebra#320] opened 2019-08-31 03:08 UTC
**Describe the bug**
After doing the "Add Multiple Repos" function with a list that contains BigBoss/ZodTTD/ModMyI AND another 3rd party repo (such as packix), the 3 repos in question do not show up. 

**To Reproduce**
1. Make a list of repos that contains BigBoss, ZodTTD, ModMyI, and Packix
2. Copy said list
3. Go to Zebra and tap "Add Multiple Repos"
4. Paste said list
5. Tap "Add"

**Expected behavior**
It would be amazing if all specified repos were immediately visible to the user after adding them (including BigBoss/ZodTTD/ModMyI). 

**Screenshots**
N/A

**Device Information:**
 - iOS Version: 12.4
 - Zebra Version: 1.0-beta20-3
 - Device Type: iPhone 6s

**Crash Log or System Log**
N/A

**Additional context**
BigBoss does show up after a refresh, but ZodTTD and ModMyI do not show up at all. When I try to re-add any of these 3 repos, it says "this repo has already been added". 

The list must contain any of these 3 repos AND an additional 3rd party repo. When the list is only BigBoss/ZodTTD/ModMyI, everything works as intended.

**Comment by wstyres** [comment] 2019-09-04 20:07
I'm not able to reproduce the issue.

Adding the following in the "Add Multiple" page:

**Comment by wstyres** [comment] 2019-09-04 21:07
Should be fixed as of 1ea558a8bcabf889e734c3dee4f3e2cb1a6b7821.

**Comment by wstyres** [comment] 2019-09-07 16:40
Fixed in beta 21

**Closed by wstyres** 2019-09-07 16:40 UTC
Labels: bug, scheduled
