### ISSUE TITLE
Crash after using FaceID to pay for a tweak

### ISSUE THREAD

**Issue by async1wake** [wstyres/Zebra#1050] opened 2020-04-06 02:23 UTC
**Describe the bug**
Zebra asked me for my FaceID so I could buy the tweak LendMyPhone3 from the geometric software repo. It failed at first then it succeeded, and then crashed after it accepted my FaceID

**To Reproduce**
Steps to reproduce the behavior: Go to any paid (or maybe the same paid tweak) and try letting it authenticate your FaceID

**Expected behavior**
For it to open the web view to the payment processor, so I can pay for the tweak

**Screenshots**
n/a

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: **13.3**
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: **1.1~beta 4**
 - Device Type [e.g. iPhone or iPad]: **iPhone X (iPhone 10,1)**
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: **checkra1n**

**Crash Log or System Log**
https://pastebin.com/xtVHEtKH

**Comment by wstyres** [comment] 2020-04-07 17:01
Looks like a duplicate of #962

**Closed by wstyres** 2020-04-07 17:01 UTC
Labels: bug
