### ISSUE TITLE
[1.1~betas] UI Bugs

### ISSUE THREAD

**Issue by gkeep** [wstyres/Zebra#881] opened 2020-02-22 09:13 UTC
**Sources tab**:
1. ~Clipping with the last source: [video representation](https://i.imgur.com/LRsfHhc.mp4)~
Fixed in early betas.
2. ~Clipping with the last package on the repo: [image](https://user-images.githubusercontent.com/20600053/75089163-2e008580-5567-11ea-89cd-ebbba58e27a5.JPEG)~
Fixed in early betas.
3. ~Weird coloring on the letter space [image](https://user-images.githubusercontent.com/20600053/75089218-bb43da00-5567-11ea-82ce-f0e9fec1c16b.jpeg)~
Fixed in beta4 or beta5.
4. Some UI parts don't change background color when switching from Dark to Light:
![image](https://user-images.githubusercontent.com/20600053/75089402-715bf380-5569-11ea-98c8-f6477ed87891.jpeg)
5. ~UI defaults to Dark Mode with Light Mode enabled on Zebra restart (likely iOS 12 specifically): [video](https://i.imgur.com/Q01oMF7.mp4)~
Fixed in beta6.

**Device info**:
iPhone 5s on iOS 12.4.

**Comment by ENDERZOMBI102** [comment] 2020-02-22 09:36
Happened to me too, but scrolling down caused 3 menus to update and display the normal color, but the “packages” view in the home page didn’t update to light with this

**Comment by TheOnlyJxnas** [comment] 2020-02-22 10:13
Another Bug I found is, that if you want to delete a source it looks weird.
![932F3292-BACF-43DE-A083-37D92626366E](https://user-images.githubusercontent.com/53837207/75090558-4f13a700-5564-11ea-8607-5079eb4172bb.png)

**Comment by TheOnlyJxnas** [comment] 2020-02-22 10:22
> Another Bug I found is, that if you want to delete a source it looks weird.
> 
> Device: iPhone X on iOS 13.3
> Jailbreak: checkra1n Linux
> 
> ![4F74BE04-8F5C-4DE7-BF0A-0360864C3316](https://user-images.githubusercontent.com/53837207/75090598-b16ca780-5564-11ea-898d-37ad62d21615.jpeg)

Well for some reason, the issue is gone. But still look at it. Don‘t really know why that happened.

**Comment by NickJustWill** [comment] 2020-02-22 15:35
Noticed this on iOS 13.2.2, the table cells stay dark when going into light mode, a restart of the app is required to update the cells, it doesn't make it unusable, but it would be convenient to fix

**Comment by gkeep** [comment] 2020-03-01 13:45
Dark mode is not applied to keyboard on iOS 12 and less. 

3D Touch:
* No background blur
* Dark mode isn't applied to buttons


Queue bar is transparent (fine in package depictions, though):
<img src="https://user-images.githubusercontent.com/20600053/75626730-0d75a280-5bdb-11ea-8e29-ea894a94f643.jpeg" width="300px"></img> <img src="https://user-images.githubusercontent.com/20600053/75626734-11092980-5bdb-11ea-8d5d-9306d2775e1b.jpeg" width="300px"></img>

**Comment by CanerKaraca23** [comment] 2020-04-25 21:34
https://cdn.discordapp.com/attachments/572784833714192395/703719492445929542/image1.png
https://cdn.discordapp.com/attachments/572784833714192395/703719492772954172/image2.png
https://cdn.discordapp.com/attachments/572784833714192395/703719491846275112/video0.mov

**Comment by wstyres** [comment] 2020-04-28 01:59
Double check if 1-4 still occur on beta7-1. I can't reproduce them, I briefly saw the last one (occurring on homepage) but I can't see the others.

**Comment by wstyres** [comment] 2020-04-28 02:05
Also believe #5 was fixed in a previous beta

**Comment by gkeep** [comment] 2020-04-28 07:42
Yup 1, 2, 3 and 5 are fixed. Will update the top message shortly. 4 still happens though.

**Comment by CanerKaraca23** [comment] 2020-04-28 11:56
![86DD5977-7CF2-4942-9D5D-D71DA72F89B9](https://user-images.githubusercontent.com/37447503/80484291-26db6680-8960-11ea-8f80-9ef5285a295d.png)
White keyboard and white queue bar also there is a new UI Bug report here, black status bar on dark mode
![10E5E788-888B-41C4-A213-26A56ADEF16A](https://user-images.githubusercontent.com/37447503/80484371-48d4e900-8960-11ea-8279-0b756a78fa7f.jpeg)

**Comment by wstyres** [comment] 2020-04-28 15:29
Just fixed the queue bar

**Comment by wstyres** [comment] 2020-04-28 15:43
Monochrome accent color should be fixed as well

**Comment by wstyres** [comment] 2020-04-28 15:47
Keyboard color should also be fixed

**Comment by CanerKaraca23** [comment] 2020-04-28 15:48
Then 3 issues left (probably for iOS 12):
-Switching dark/light modes problems
-White Keyboard on Dark Mode (Should be dark)
-Black StatusBar on Dark Mode (Should be white)

**Comment by wstyres** [comment] 2020-04-28 15:50
Can't reproduce the status bar problem, is it a one time occurrence or does it happen every time?

**Comment by gkeep** [comment] 2020-04-28 16:01
Can't reproduce this one either.

**Comment by gkeep** [comment] 2020-04-28 16:11
Found another one. 

Not sure about other languages, but in Russian, on the languages page, languages have to start with a capital letter (like in English). We don't have these strings on Crowdin, so it's not a translation issue.

<img src="https://user-images.githubusercontent.com/20600053/80510607-a29ada80-8983-11ea-9392-e5cffc339d7e.jpeg" width=50%>

**Comment by wstyres** [comment] 2020-04-28 16:21
Could you create another issue for that? I've been meaning to correct that as well as actually show the name of the language in the local region like iOS does.

**Comment by gkeep** [comment] 2020-04-28 16:23
Sure.

**Comment by CanerKaraca23** [comment] 2020-04-28 17:00
> Can't reproduce the status bar problem, is it a one time occurrence or does it happen every time?

Yes. It's happen always. But only in searching section while searching something.

**Comment by wstyres** [comment] 2020-04-28 18:02
@CanerKaraca23 Not able to reproduce with the search view on the status bar. Could you take a screen recording so I can see exactly the steps you took?

**Comment by CanerKaraca23** [comment] 2020-04-28 18:05
Unfortunately, on screen recording red section hides status bar. I can only take screenshot.

**Comment by wstyres** [comment] 2020-04-28 18:06
Well then maybe instructions step by step?

**Comment by wstyres** [comment] 2020-04-28 18:07
Ah I see, you have live search off so for me it only happens when I press enter

**Comment by CanerKaraca23** [comment] 2020-04-28 18:08
4 step:
![48FB8932-CBDD-4346-A07A-41D1EA28EDCF](https://user-images.githubusercontent.com/37447503/80521818-54420780-8994-11ea-94cc-401b6d24403b.png)
![F04A47DE-AE8E-4586-BE69-53F29838AB72](https://user-images.githubusercontent.com/37447503/80521826-560bcb00-8994-11ea-9c8c-499c0026733a.png)
![6F135DEE-9E2A-4EB6-9C96-4B2AB58C362D](https://user-images.githubusercontent.com/37447503/80521829-573cf800-8994-11ea-8047-0da037a9edd8.png)
![C1C078D7-F2DF-4E32-BF4D-A43CBDFCB4B4](https://user-images.githubusercontent.com/37447503/80521833-586e2500-8994-11ea-9c07-8d71b36a99aa.png)

**Comment by CanerKaraca23** [comment] 2020-04-28 18:10
> Ah I see, you have live search off so for me it only happens when I press enter

Yeah, because live search slow on my iPhone 5s.
Also another UI bug here:
![6CC6CD5E-3C1A-4501-9190-6343553E0352](https://user-images.githubusercontent.com/37447503/80522040-99663980-8994-11ea-8155-ad9ffcdc4a93.png)
When you scroll very fast on packages section this happens. Wrong icons on wrong packages.

**Comment by wstyres** [comment] 2020-04-28 18:11
Status bar should be fixed as of 4fc7c18037ab2d39599d0ce7cb0af0ae086e4f62.

**Comment by CanerKaraca23** [comment] 2020-04-28 18:14
You're very fast, thanks! Can you look this issue too?

**Comment by wstyres** [comment] 2020-04-28 18:15
The scrolling too fast is a problem with the image library we use, can't do anything about it other than to tell you to stop scrolling so fast :p

**Comment by CanerKaraca23** [comment] 2020-04-28 18:19
No problem for me :D Just notice, I'm not using so fast Zebra. Also sometimes Zebra freezes for 4-5 seconds. I don't know why maybe because I have old device (iPhone 5s)

**Comment by wstyres** [comment] 2020-04-29 15:38
I think all of these should be fixed as of 2924838f4c5a4c542c1ea5b05318e1f1f419e177. If any more arise, please open a new issue as this one is getting kind of long :).

**Closed** 2020-04-30 19:10 UTC
Labels: bug, low, scheduled
