### ISSUE TITLE
[Request] Push Notifications for Tweak Updates

### ISSUE THREAD

**Issue by benharris2510** [wstyres/Zebra#821] opened 2020-01-15 19:46 UTC
I understand that having push notifications would probably require a background daemon to run, but it would be a great feeling to be able to wake up in the morning and see notifications about tweak updates. Let me know if it seems like something that should be added!

**Comment by wstyres** [comment] 2020-01-19 00:57
Duplicate of #595

**Closed by wstyres** 2020-01-19 00:57 UTC
