### ISSUE TITLE
Ability to get notified when a certain tweak gets updated

### ISSUE THREAD

**Issue by kevini15** [wstyres/Zebra#862] opened 2020-02-18 20:16 UTC
On Cydia one could use the feature "Show All Changes" so whenever a subscribed package gets updated it would appear under the "Changes" tab. I have not seen this feature in Zebra yet. Perhaps it already exists, but I'm just not aware of it as I just installed it today (and love everything about it!)

Zebra could take it a step further and additionally send notifications (as a banner or whatever) whenever a subscribed package gets an update. Perhaps create a folder for subscribed packages one could check whenever a notification comes.

This could be - at least for me - incredibly useful as I'm waiting for tweaks such as NoMoreDisabled, System Info, Activator, Apace, CocoaTop to get updated for iOS13.

Thanks in advance!

**Comment by sunmono** [comment] 2020-02-18 21:40
CocoaTop has been updated for iOS 13! Download it here and install with Filza or zebra (you may have to run uicache to get the icon to show up): https://d0m0.github.io/ru.domo.cocoatop64_2.0.2_iphoneos-arm.deb

**Comment by wstyres** [comment] 2020-02-19 21:20
Duplicate of #595

**Closed by wstyres** 2020-02-19 21:20 UTC
Labels: suggestion
