### ISSUE TITLE
Zebra crashes when purchasing a package from packix

### ISSUE THREAD

**Issue by TheTrumpetDude1** [wstyres/Zebra#211] opened 2019-06-30 13:15 UTC
**Describe the bug**
The Zebra app crashes when attempting to visit the Packix purchase page.

**To Reproduce**
Attempt to purchase a paid package from Packix.

**Expected behavior**
I would be taken to the Packix purchase page like on Sileo or Cydia.

**Screenshots**
https://photos.app.goo.gl/fh6kqxgxkCeCJWSs6

**Device Information (please complete the following information):**
 - iOS Version: iOS 12.1.1b3 (16C5050a)
 - Zebra Version: 1.0/ ~b15
 - Device Type: iPhone XS Max (iPhone 11,6)

**Crash Log or System Log**

Date: 2019-06-30 12:46:00 +0000
Process: Zebra
Bundle id: xyz.willy.Zebra
Exception type: NSInvalidArgumentException
Reason: The specified URL has an unsupported scheme. Only HTTP and HTTPS URLs are supported.
Culprit: Unknown
Device: iPhone XS Max, iOS 12.1.1
Call stack:
0   CoreFoundation                      0x00000002345abf68 __exceptionPreprocess
1   libobjc.A.dylib                     0x00000002337a8284 objc_exception_throw
2   CoreFoundation                      0x00000002344ae25c -[NSCache init]
3   SafariServices                      0x000000024a1b09e0 -[SFSafariViewController initWithURL:configuration:]
4   SafariServices                      0x000000024a1728f8 -[SFAuthenticationViewController initWithURL:callbackURLScheme:]
5   SafariServices                      0x000000024a13777c -[SFAuthenticationSession _startRequestingFromWebAuthenticationSession:]
6   Zebra                               0x0000000102b34be8 Zebra + 183272
7   Zebra                               0x0000000102b34ae0 Zebra + 183008
8   CFNetwork                           0x0000000234b8e07c __75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke
9   CFNetwork                           0x0000000234ba3528 __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke
10  Foundation                          0x000000023504dda4 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
11  Foundation                          0x0000000234f4f158 -[NSBlockOperation main]
12  Foundation                          0x0000000234f4e5d8 -[__NSOperationInternal _start:]
13  Foundation                          0x000000023504fcdc __NSOQSchedule_f
14  libdispatch.dylib                   0x0000000233fafd58 _dispatch_call_block_and_release
15  libdispatch.dylib                   0x0000000233fb12f0 _dispatch_client_callout
16  libdispatch.dylib                   0x0000000233fb42c0 _dispatch_continuation_pop
17  libdispatch.dylib                   0x0000000233fb3990 _dispatch_async_redirect_invoke
18  libdispatch.dylib                   0x0000000233fc00d4 _dispatch_root_queue_drain
19  libdispatch.dylib                   0x0000000233fc0940 _dispatch_worker_thread2
20  libsystem_pthread.dylib             0x00000002341b1bc0 _pthread_wqthread
21  libsystem_pthread.dylib             0x00000002341b7dd4 start_wqthread

**Additional context**

**Comment by midnightchip** [comment] 2019-06-30 18:14
Log out and then log back into packix in zebra, this is caused by packix needing a refresh I believe

**Comment by PoomSmart** [comment] 2019-07-13 06:50
Closed in favour of #237

**Closed by PoomSmart** 2019-07-13 06:50 UTC
Labels: bug
