### ISSUE TITLE
Search UI Theme Bug

### ISSUE THREAD

**Issue by Greigh** [wstyres/Zebra#922] opened 2020-02-29 22:22 UTC
**Describe the bug**
When searching, the UI isn’t themed

**To Reproduce**
Search for a package and the UI is white. 

**Screenshots**
![38B284C2-6A8B-437D-919E-BF8A3E399C5D](https://user-images.githubusercontent.com/57759540/75615899-db4f3c80-5b17-11ea-9be4-56312100726b.png)

**Device Information (please complete the following information):**
 - iOS Version: 13.3
 - Zebra Version: 1.1~beta 2 
 - Device Type: XS Max
 - Jailbreak Type: unc0ver

**Comment by absidue** [comment] 2020-02-29 22:24
Duplicate of #912

**Closed** 2020-02-29 23:15 UTC
Labels: bug
