### ISSUE TITLE
[BUG] Updating Tweak stuck on "Performing Actions..."

### ISSUE THREAD

**Issue by JakeValenzuela** [wstyres/Zebra#563] opened 2019-11-13 02:56 UTC
**Describe the bug**
After updating some tweaks, the console is stuck on "Performing actions". In my specific case, "Z Shell" is not able to be updated.

**To Reproduce**
Some tweaks work and update without issue. However, "Z Shell" and several others have issues.

**Expected behavior**
Tweak should update w/o issue.

**Screenshots**
![unnamed](https://user-images.githubusercontent.com/5650707/68729045-f44ad680-0596-11ea-840c-bae7587f7626.jpg)

**Device Information (please complete the following information):**
 - iOS Version: iOS 12.4 
 - Zebra Version: 1.0~beta21-1 
 - Device Type: iPhone Xr

**Additional context**
This seems to be a pretty popular issue. It was apparently fixed over two weeks ago, but it is still occuring fairly often.

**Comment by wstyres** [comment] 2019-11-13 02:58
Could you update to the latest beta? I see that you are on beta 21-1 but 11 betas have been released since that beta came out. Make sure you have our beta repo added at https://getzbra.com/beta/.

**Comment by JakeValenzuela** [comment] 2019-11-13 03:03
Yeah, sorry I didn't update. I just updated to Zebra 1.0~beta26-4 and I am still having the same issues.
![unnamed (1)](https://user-images.githubusercontent.com/5650707/68729542-46d8c280-0598-11ea-99f3-b6f226090884.jpg)

**Comment by wstyres** [comment] 2019-11-13 03:09
Thanks, could you list some other packages that you experience this on? Also, what jailbreak are you using?

**Comment by JakeValenzuela** [comment] 2019-11-13 03:12
I can't really name any off the top of my head, but I feel like the system tools (sam bingner's stuff) gave me a lot more issues with updating. I never have issues with updating normal tweaks.

I'm using the latest unc0ver. (3.7.0~b3)

**Comment by wstyres** [comment] 2019-11-13 03:12
Interesting, and these issues happen every single time that you try to update?

**Comment by JakeValenzuela** [comment] 2019-11-13 03:14
It is either every single time or very, very often. This only ever happens to me with system tools as I said before.

**Comment by PoomSmart** [comment] 2019-11-13 12:26
Fixed as of 4713a13b8572d89be2713824288c933c0b557e12

**Comment by wstyres** [comment] 2019-11-13 20:03
Because of this fix, text from apt no longer shows in the console, we’ll continue to look into this to find a solution.

**Comment by wstyres** [comment] 2019-11-13 23:21
This issue does not appear to be fixed and will require further investigation.

**Comment by wstyres** [comment] 2019-11-14 18:59
I'm not able to reproduce on the latest beta trying to install ZSH Shell. Does it still occur for you?

**Comment by JakeValenzuela** [comment] 2019-11-14 19:01
I was writing this as you sent that - pretty funny.. I have not had any issue with updating ZSH Shell on the latest beta. It worked perfectly.

**Comment by wstyres** [comment] 2019-11-20 15:49
If the bug can't be reproduced anymore I will close the issue. Hopefully it won't come up again.

**Closed** 2019-11-20 16:41 UTC
Labels: bug
