### ISSUE TITLE
Several bugs on iOS 9 (and 10)

### ISSUE THREAD

**Issue by allendude51** [wstyres/Zebra#1112] opened 2020-04-20 19:37 UTC
**Describe the bug**
I get an error ever time I try to install a package. Also there are several visual bugs.

**To Reproduce**
Install a package in is 9 using Zebra.

**Expected behavior**
I expect the packages to install without an error.

**Screenshots**
![8C47FCC6-A605-4C93-B065-4C32D407065C](https://user-images.githubusercontent.com/51012842/79792252-316c7f00-8314-11ea-86fb-677c91e2ba37.png)
![E8957B38-7D82-42E8-AD74-71701C4F656E](https://user-images.githubusercontent.com/51012842/79792253-329dac00-8314-11ea-9931-d11d7995577b.png)
![1346DB13-7852-4885-AAFE-69AFA1F1835D](https://user-images.githubusercontent.com/51012842/79792254-329dac00-8314-11ea-8f11-c5955f42a7d7.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <9.3.6>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <1.1-beta6>
 - Device Type [e.g. iPhone or iPad]: <iPhone 4s>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <Pheonix>

**Crash Log or System Log**
None

**Additional context**
Also the "Restart Springboard" button doesn't work.

**Comment by wstyres** [comment] 2020-04-20 19:44
Unfortunately I don't have a device on iOS 9 to reproduce these problems. Are you able to check the permissions on the file `/usr/libexec/zebra/supersling`?

**Comment by allendude51** [comment] 2020-04-20 20:23
Yes. This is what it said when I opened it
![image](https://user-images.githubusercontent.com/51012842/79796241-d4c09280-831a-11ea-84e0-6323565669af.jpg)

**Comment by wstyres** [comment] 2020-04-20 20:36
View the file's information in iFile or Filza. It should show things like "Read Write Execute" or "File Permissions"

**Comment by allendude51** [comment] 2020-04-20 21:21
That's what it showed when I opened it in filza

**Comment by wstyres** [comment] 2020-04-20 21:40
Don't run the file, click the little "i" button and view the file information. You should see something like this 
![IMG_3397](https://user-images.githubusercontent.com/19736790/79802459-fb3bf900-832d-11ea-9d0b-fb873ab2562c.png)

**Comment by allendude51** [comment] 2020-04-20 22:53
This is what it shows
![image](https://user-images.githubusercontent.com/51012842/79807176-c466e280-832f-11ea-8f62-c54eb5d10fcb.jpg)

**Comment by wstyres** [comment] 2020-04-21 18:58
Ok, is the device stashed? Does Zebra exist at /Applications/Zebra.app or is it somewhere in /var/stash

**Comment by allendude51** [comment] 2020-04-21 19:36
Zebra shows up in /Applications but I don't see it in the stash folder.

**Comment by wstyres** [comment] 2020-04-23 14:05
But is /Applications symlinked? That may be the deciding factor here.

Also, do these issues happen on 1.0.x?

**Comment by allendude51** [comment] 2020-04-23 19:11
it isn't symlinked. And no I didnt have this issue on 1.0.x

**Comment by wstyres** [comment] 2020-04-23 23:33
Hm, very odd that it is not symlinked, I'll do some more investigating and hopefully something will come up hard to do without an iOS 9 device though.

**Comment by allendude51** [comment] 2020-04-24 04:28
Thank you

**Comment by PoomSmart** [comment] 2020-05-06 10:56
- Search bar color bug fixed as of 6d86f2c0dd1aeade688ad7f6a7a91fa2799f83fe
- Broken margins in Console window bug fixed as of 6526e0b93cf7b76f776813dd04d824e9245dc0a9

**Comment by PoomSmart** [comment] 2020-05-06 10:57
Queue bar size is known to be small on iOS 10 and below, but I can't find its zero-opacity bug anymore.

**Comment by allendude51** [comment] 2020-05-07 09:56
The queue bar background is fixed but the search bar is still white in dark mode for me. Also I'm still getting the permissions error.

**Comment by wstyres** [comment] 2020-05-08 15:34
@allendude51 Is it alright if I send you a deb with a debug version of supersling so that you can provide some more information?

**Comment by wstyres** [comment] 2020-05-08 15:52
Here is a link to the deb https://www.dropbox.com/s/dvfhgllf73456kp/xyz.willy.zebra_1.1-6%2Bdebug_iphoneos-arm.deb?dl=0. Install it through Filza or something similar and then try installing something in Zebra.

**Comment by allendude51** [comment] 2020-05-13 08:19
Tried it. Didn't work. I got these errors

![1F1F1363-47DF-478F-840E-8745A1E4D21A](https://user-images.githubusercontent.com/51012842/81788718-960c9b00-94c8-11ea-8154-897a0cfc1fab.png)
![C26DD6D6-2B50-4D42-B1F0-AF3487C5EB97](https://user-images.githubusercontent.com/51012842/81788721-96a53180-94c8-11ea-8d6b-263c6d117312.png)
![902C6640-EE6B-44D6-960E-E476CCBBDCA9](https://user-images.githubusercontent.com/51012842/81788722-96a53180-94c8-11ea-8266-875185e7d158.png)
![82C1189C-19B8-4B05-916D-706FD6A97528](https://user-images.githubusercontent.com/51012842/81788723-973dc800-94c8-11ea-960d-a82a81647099.png)

**Comment by wstyres** [comment] 2020-05-13 14:24
Ok so it looks like Zebra is stashed in `/private/var/db/stash/appsstash/` which is likely why the verification is failing. Here is another deb that should fix the issue (hopefully) https://www.dropbox.com/s/5nobh9xt1yrr893/xyz.willy.zebra_1.1.1-3%2Bdebug_iphoneos-arm.deb?dl=0

**Comment by allendude51** [comment] 2020-05-13 18:25
Installed it and still got the same error

**Comment by allendude51** [comment] 2020-05-18 05:25
I think I'm just gonna remove zebra on my 4s and just use Cydia. Thanks for the help though. Zebra works much better on my newer devices anyway

**Comment by wstyres** [comment] 2020-05-18 20:02
Sorry about that, I think its best to stay on 1.0.8 if you want to continue using it on your 4s.

**Closed by wstyres** 2020-05-18 20:02 UTC
Labels: bug, console, question, queue, search, supersling
