### ISSUE TITLE
Error when downloading/updating packages from Dynastic repo

### ISSUE THREAD

**Issue by allendude51** [wstyres/Zebra#1251] opened 2020-05-17 23:47 UTC
**Describe the bug**

Every time I try to update something from the Dynastic report I get an error for seemingly no reason. I'm signed in to the store on zebra. The package also updates from Cydia just fine with zero issues.

**To Reproduce**

Update a package from Dynastic

**Expected behavior**

I expect the package to download with no issue.
**Screenshots**

![F20DD7CC-0C4C-438F-B461-0CF506371E73](https://user-images.githubusercontent.com/51012842/82163091-872e3b80-986e-11ea-80d5-e52e06183a14.png)

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <13.4.1>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <1.1.4>
 - Device Type [e.g. iPhone or iPad]: <iPhone X and 6s>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <checkra1n>

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

None
**Additional context**

**Comment by wstyres** [comment] 2020-05-18 22:03
Hm, odd. 

- You have the package purchased and are signed into Dynastic correct? Have you tried logging out and back into Dynastic?
- Does this issue occur with any other purchased packages from Dynastic or another repo? 
- How are you upgrading the package? 3D-Touch action, Swipe Action, Upgrade All, Modify->Upgrade? My first thought here is that the problem is with Upgrade All.

**Comment by allendude51** [comment] 2020-05-18 23:12
-Already tried that. Didn't work
-Nope. Just dynastic
-I just press the upgrade all button in zebra

**Comment by wstyres** [comment] 2020-05-19 02:28
Alright, I suspect that the Upgrade All button is the culprit here

**Comment by wstyres** [comment] 2020-05-19 19:07
Should be fixed as of 76ca8b3049486965660157a258090ba824b9299b. Tried my fix out on a few Chariz purchases and they seemed to download ok. Can't try it out on Dynastic unfortunately since they do not offer downgrades for some of their packages.

**Comment by allendude51** [comment] 2020-05-19 20:04
Alright cool. I'll wait until a Dynastic package gets an update to see if it's fixed now.

**Comment by wstyres** [comment] 2020-05-22 01:22
Let me know if it occurs again, I'll reopen if so.

**Closed** 2020-05-22 01:22 UTC
Labels: bug, medium, purchases, scheduled
