### ISSUE TITLE
Can not Remove/Add Installed Tweaks from/to Wishlist

### ISSUE THREAD

**Issue by tdadvocate** [wstyres/Zebra#1362] opened 2020-06-01 16:46 UTC
**Describe the bug**
After installing tweaks you cannot add or remove them to or from the Wishlist. 

**To Reproduce**
Install tweak. Try to add to or remove tweak from wishlist. 

**Expected behavior**
Should be able to instal a tweak and either add it to or remove it from the wishlist without installing it first. 

**Device Information (please complete the following information):**
 - iOS Version: 13.5
 - Zebra Version: 1.2~beta1b
 - Device Type: iPhone X
 - Jailbreak Type: checkra1n

**Comment by wstyres** [comment] 2020-06-22 15:10
Duplicate of #1344

**Closed by wstyres** 2020-06-22 15:10 UTC
