### ISSUE TITLE
Sources list cut off

### ISSUE THREAD

**Issue by campbellcole** [wstyres/Zebra#22] opened 2019-04-24 07:39 UTC
The last element is cut off when viewing the sources list. It gets placed underneath the navigation bar at the bottom, probably due to some missing padding or mis-sized table view

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by campbellcole** [comment] 2019-04-24 07:47
Update: the issue resolved itself after a short while, not sure what I did but I believe it happens when new sources are added and fixes itself when restarted. I'll test this now

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wstyres** [comment] 2019-04-24 12:54
Thanks for the detailed steps! I'm able to reproduce this and I hope to get a fix out soon.

**Comment by wstyres** [comment] 2019-04-24 19:23
This issue _should_ be fixed as of 81ce4ed. I cannot reproduce it anymore on the homepage or the sources view. The fix will be in beta 5 but I will leave this issue open for you to try it out and see if the issue still occurs.

**Comment by campbellcole** [comment] 2019-04-25 18:40
The issue still occurs on the sources page but not the homepage on beta 5

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed** 2019-05-02 23:08 UTC
Labels: bug
