### ISSUE TITLE
Zebra sometime displaying all the packages of a repo when resfresing sources 

### ISSUE THREAD

**Issue by metyl2945** [wstyres/Zebra#1213] opened 2020-05-10 14:11 UTC
As I mentioned in the title. Zebra sometime act strange, when refresing sources is done, the Changes tab is fill with all the packages of some repo, although it isn't recieving any update.

**To Reproduce**
There is no ways to do this effectively, it happen randomly

**Expected behavior**
I expected it to show only packages that are recieving updates but no.

**Screenshots**
I haven't got it recently
**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version: <12.4.6>
 - Zebra Version: <1.1>
 - Device Type: <Iphone>
 - Jailbreak Type: <checkra1n>

**Crash Log or System Log**
It didn't crash anything so there is no crash log

**Additional context**

**Comment by PoomSmart** [comment] 2020-05-10 15:23
Duplicate of #996

**Closed by PoomSmart** 2020-05-10 15:23 UTC
Labels: bug
