### ISSUE TITLE
Darkmode in Source tab doesnt work well

### ISSUE THREAD

**Issue by qnblackcat** [wstyres/Zebra#1224] opened 2020-05-13 02:36 UTC
**Describe the bug**
- Sources tab isnt completely dark

**To Reproduce**
- when I switch from Changes tab to Sources tab. But It happens randomly. Im not sure about it 

**Expected behavior**
- just make it like normal

**Screenshots**
https://imgur.com/MDPBp25
https://imgur.com/Z8jcqWy

**Device Information (please complete the following information): 

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: iOS 12.2
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1.1
 - Device Type [e.g. iPhone or iPad]: iPhone 6s
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <checkra1n>

**Crash Log or System Log**

**Additional context**

**Comment by wstyres** [comment] 2020-05-13 14:10
Duplicate of #1173

**Closed by wstyres** 2020-05-13 14:10 UTC
Labels: bug
