### ISSUE TITLE
Packages take me straight  to package website

### ISSUE THREAD

**Issue by beerad1228** [wstyres/Zebra#920] opened 2020-02-29 15:46 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by absidue** [comment] 2020-02-29 16:11
Duplicate of #906

**Comment by absidue** [comment] 2020-02-29 16:11
In the future please fill in more information and provide screenshots / screen recordings when reporting bugs

**Closed** 2020-02-29 16:18 UTC
Labels: bug
