### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by kelvin1306** [wstyres/Zebra#202] opened 2019-06-20 14:58 UTC
Date: 2019-06-20 14:47:44 +0000
Process: Zebra
Bundle id: xyz.willy.Zebra
Exception type: NSRangeException
Reason: *** -[__NSArrayM objectAtIndex:]: index 10 beyond bounds [0 .. 0]
Culprit: Unknown
Device: iPhone 8 Plus, iOS 12.1.1
Call stack:
0   CoreFoundation                      0x00000001c112cedc __exceptionPreprocess
1   libobjc.A.dylib                     0x00000001c02fda40 objc_exception_throw
2   CoreFoundation                      0x00000001c10a4494 _CFArgv
3   CoreFoundation                      0x00000001c1014698 _CFDataInit
4   Zebra                               0x0000000102de28d4 Zebra + 26836
5   UIKitCore                           0x00000001ee66cf74 -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:]
6   UIKitCore                           0x00000001ee66d4bc -[UITableView _createPreparedCellForGlobalRow:willDisplay:]
7   UIKitCore                           0x00000001ee638b94 -[UITableView _updateVisibleCellsNow:isRecursive:]
8   UIKitCore                           0x00000001ee6370b8 -[UITableView _setNeedsVisibleCellsUpdate:withFrames:updateImmediatelyIfPossible:]
9   UIKitCore                           0x00000001ee657a94 -[UITableView _rectChangedWithNewSize:oldSize:]
10  UIKitCore                           0x00000001ee65817c -[UITableView setBounds:]
11  UIKitCore                           0x00000001ee86dfd0 -[UIScrollView setContentOffset:]
12  UIKitCore                           0x00000001ee659340 -[UITableView setContentOffset:]
13  UIKitCore                           0x00000001ee887f90 _UIScrollViewAdjustForOverlayInsetsChangeIfNecessary
14  UIKitCore                           0x00000001ee888224 -[UIScrollView(UIScrollViewInternal) setSafeAreaInsets:]
15  UIKitCore                           0x00000001ede71258 -[UIViewController _updateViewSafeAreaInsetsAndEagerlyUpdateContentScrollView:]
16  UIKitCore                           0x00000001ede719b0 -[UIViewController _setContentOverlayInsets:andLeftMargin:rightMargin:]
17  UIKitCore                           0x00000001ede73450 __121-[UIViewController __updateContentOverlayInsetsWithOurRect:inBoundsOfAncestorViewController:viaImmediateChildOfAncestor:]_block_invoke
18  UIKitCore                           0x00000001ede73248 -[UIViewController __updateContentOverlayInsetsWithOurRect:inBoundsOfAncestorViewController:viaImmediateChildOfAncestor:]
19  UIKitCore                           0x00000001ede72410 -[UIViewController _updateContentOverlayInsetsFromParentIfNecessary]
20  UIKitCore                           0x00000001ede71c28 -[UIViewController _updateContentOverlayInsetsForSelfAndChildren]
21  UIKitCore                           0x00000001edde8008 -[UINavigationController _layoutViewController:]
22  UIKitCore                           0x00000001edde2b80 -[UINavigationController _layoutTopViewController]
23  UIKitCore                           0x00000001eddd8db4 __105-[UINavigationController _repositionPaletteWithNavigationBarHidden:duration:shouldUpdateNavigationItems:]_block_invoke
24  UIKitCore                           0x00000001ee8df37c +[UIView(UIViewAnimationWithBlocks) _setupAnimationWithDuration:delay:view:options:factory:animations:start:animationStateGenerator:completion:]
25  UIKitCore                           0x00000001ee8df940 +[UIView(UIViewAnimationWithBlocks) animateWithDuration:animations:completion:]
26  UIKitCore                           0x00000001eddd8aa0 -[UINavigationController _repositionPaletteWithNavigationBarHidden:duration:shouldUpdateNavigationItems:]
27  UIKitCore                           0x00000001eddd912c -[UINavigationController _setNavigationBarHidden:edgeIfNotNavigating:duration:]
28  UIKitCore                           0x00000001ee4a15a8 __63-[_UISearchPresentationController dismissalTransitionWillBegin]_block_invoke.186
29  UIKitCore                           0x00000001edea9fe0 -[_UIViewControllerTransitionCoordinator _applyBlocks:releaseBlocks:]
30  UIKitCore                           0x00000001edea63d8 -[_UIViewControllerTransitionContext __runAlongsideAnimations]
31  UIKitCore                           0x00000001ee8b41fc -[UIViewAnimationState _runAlongsideAnimations]
32  UIKitCore                           0x00000001ee8b2d90 -[UIViewAnimationState pop]
33  UIKitCore                           0x00000001ee8b040c +[UIViewAnimationState popAnimationState]
34  UIKitCore                           0x00000001ee8df404 +[UIView(UIViewAnimationWithBlocks) _setupAnimationWithDuration:delay:view:options:factory:animations:start:animationStateGenerator:completion:]
35  UIKitCore                           0x00000001ee8df8c0 +[UIView(UIViewAnimationWithBlocks) animateWithDuration:delay:options:animations:completion:]
36  UIKitCore                           0x00000001ee499c3c -[_UISearchControllerInPlaceSearchBarAnimator animateTransition:]
37  UIKitCore                           0x00000001edda7894 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke
38  UIKitCore                           0x00000001ee44f13c _runAfterCACommitDeferredBlocks
39  UIKitCore                           0x00000001ee43d138 _cleanUpAfterCAFlushAndRunDeferredBlocks
40  UIKitCore                           0x00000001ee46c140 _afterCACommitHandler
41  CoreFoundation                      0x00000001c10bc7cc __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
42  CoreFoundation                      0x00000001c10b7460 __CFRunLoopDoObservers
43  CoreFoundation                      0x00000001c10b7a00 __CFRunLoopRun
44  CoreFoundation                      0x00000001c10b71f0 CFRunLoopRunSpecific
45  GraphicsServices                    0x00000001c3330584 GSEventRunModal
46  UIKitCore                           0x00000001ee4434c0 UIApplicationMain
47  Zebra                               0x0000000102df4950 Zebra + 100688
48  libdyld.dylib                       0x00000001c0b76bb4 start

**Comment by PoomSmart** [comment] 2019-06-21 02:05
Possibly a duplicate of #197, please confirm.

**Closed** 2019-06-29 02:34 UTC
Labels: bug
