### ISSUE TITLE
Zebra crashes when trying to reinstall a tweak.

### ISSUE THREAD

**Issue by iAppleLuvr** [wstyres/Zebra#83] opened 2019-05-14 01:01 UTC
**Describe the bug**
Went to reinstall the tweak UnSub from Nepeta's repo. I pressed "Reinstall," then "Confirm," and then it just crashed. Same happens with other tweaks. iPhone X, 12.1.1, unc0ver

**To Reproduce**
1. Open Zebra
2. Allow sources to refresh
3. Go to any tweak's page
4. Click "Modify"
5. Click "Reinstall"
6. Click "Confirm"
7. Profit (??)

**Expected behavior**
I expected the tweak to reinstall.

**Screenshots**
N/A

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0~beta 10
 - Device Type [e.g. iPhone or iPad]: iPhone X

**Crash Log or System Log**
https://pastebin.com/m34UvjhM

**Additional context**
N/A

**Comment by wstyres** [comment] 2019-05-14 01:03
Duplicate of #55, the issue is fixed already but I'm leaving #55 open in case people still experience the issue when I release the next beta

**Closed by wstyres** 2019-05-14 01:03 UTC
Labels: bug

**Comment by iAppleLuvr** [comment] 2019-05-14 01:04
Oh ok, didn't see that, thanks!
