### ISSUE TITLE
Some package updates not showing up

### ISSUE THREAD

**Issue by rubrdcky** [wstyres/Zebra#31] opened 2019-04-30 22:35 UTC
**Describe the bug**
Maybe this has to do with an issue of a repo not refreshing properly but it seems that sometimes not all available updates are showing up. This particular issue was Cephei from the Chariz repo. The below screenshots are Cydia's available updates vs Zebra's within less than a minute (I even went back to Zebra after the Cydia refresh to double check).

**To Reproduce**
Steps to reproduce the behavior: Not too sure

**Expected behavior**

All updates would show but again maybe the repo isn't refreshing?

**Screenshots**

![IMG_0599](https://user-images.githubusercontent.com/15958822/56997642-800a9180-6b76-11e9-8b45-d81e86dd8a73.PNG)

![Actual Updates](https://user-images.githubusercontent.com/15958822/56997658-8dc01700-6b76-11e9-879c-309d462326e1.PNG)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.1
 - AUPM Version [e.g. 1.0~beta1 or beta1]: bete 5 
 - Device Type [e.g. iPhone or iPad]: iPhone 8

**Comment by wstyres** [comment] 2019-05-01 01:38
I'll look at Cephei and see what is the problem.

**Comment by rubrdcky** [comment] 2019-05-01 23:05
FWIW this morning on was on my iPad and the cephei package showed up as an update. I can open another issue if you would like but some other strange things happened after I updated all packages (which were Zebra beta 6, cephei and Dune). Here is what happened:

1. I did not get a 'Reload/Restart springboard' button, only a done button
2. after hitting Done it brought me back to the packages view
3. I thought it was kind of strange but went over to the sources tab and attempted to refresh sources and Zebra crashed.
4. Re-opened Zebra and I was in fact on beta 6 at that point (still no respring and also no new icon)
5. resprung manually via an activator assignment, still no new Zebra icon.
6. opened cydia and according to cydia I still needed to update cephei, so I did and was greeted with a 'restart springboard' so, well, I did. After that everything seemed fine AND Zebra had the new icon!

iPad Mini 4
iOS 12.1.1
Zebra beta 5 at the time

**Comment by wstyres** [comment] 2019-05-03 16:36
I'm able to see an update for Cephei in Zebra so I'm not sure what the issue is here. Is it possible that your sources in Zebra were not up to date?

**Comment by rubrdcky** [comment] 2019-05-03 21:12
I suppose it's possible but I'm kind of crazy about that sort of thing. I'll keep an eye on it.

**Comment by wstyres** [comment] 2019-05-04 00:17
Alright, I'm going to close this issue for now but if you see it come up again let me know.

**Closed by wstyres** 2019-05-04 00:17 UTC
Labels: bug
