### ISSUE TITLE
Stick at action performance 

### ISSUE THREAD

**Issue by xi7i6** [wstyres/Zebra#432] opened 2019-10-26 08:27 UTC
**Describe the bug**
While reinstalling 3 themes sometimes while updating also i got stick with Action performance for a long time.  

**To Reproduce**
Update themes or reinstall them. 

**Expected behavior**

**Screenshots**
![4C9CAB6F-E8FF-4539-B79D-682A0697A713](https://user-images.githubusercontent.com/55637002/67616570-4a6ff980-f7e3-11e9-950e-7e766ac1b383.png)

**Device Information (please complete the following information):**
 - iOS Version [12.4]: 
 - Zebra Version [1.0\~beta 23-1]: 
 - Device Type [iPhone 11.6]: 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment] 2019-10-26 14:53
Duplicate of #260

**Closed by wstyres** 2019-10-26 14:53 UTC
Labels: bug
