### ISSUE TITLE
Live Search doesn’t work

### ISSUE THREAD

**Issue by crivera2712** [wstyres/Zebra#1320] opened 2020-05-28 00:22 UTC
**Describe the bug**
When searching nothing shows up until you tap “Search”

**To Reproduce**
Just search a tweak without tapping search

**Expected behavior**
When I’m typing, is expected that the search is constantly searching for the tweak I’m looking for, so I don’t have to type the full name of the tweak

**Screenshots**

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
13.5
 - Zebra Version [e.g. 1.0\~beta1 or beta1]:
1.2~beta1a
 - Device Type [e.g. iPhone or iPad]:
iPhone XS
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]:
unc0ver 5.0.1

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by eve0415** [comment] 2020-05-28 00:23
Duplicate of #1313

**Comment by aabosh** [comment] 2020-05-28 03:13
Duplicate, closing.

**Closed by aabosh** 2020-05-28 03:13 UTC
