### ISSUE TITLE
Duplicate repos 

### ISSUE THREAD

**Issue by romeo1186** [wstyres/Zebra#352] opened 2019-09-08 21:35 UTC
![C98F0BCA-69CD-4EA5-B273-6C5382F66403](https://user-images.githubusercontent.com/24795894/64494775-57677680-d291-11e9-9726-6dc22f4b8d90.png)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

**Additional context**

**Comment by wstyres** [comment] 2019-09-08 21:41
Duplicate of #346

**Closed by wstyres** 2019-09-08 21:41 UTC
Labels: bug
