### ISSUE TITLE
Try to install Flex Beta3 

### ISSUE THREAD

**Issue by kelvin1300** [wstyres/Zebra#884] opened 2020-02-22 15:40 UTC
**Describe the bug**
I cannot download Flex 3 Beta for this repo http://getdelta.co/

**To Reproduce**
I try twice download, nothing happen 

**Expected behavior**
I expect to download correctly 

**Screenshots**
I has a video to show the issue 

**Device Information (please complete the following information):**
 - iOS Version: 13.3
 - Zebra Version: 1.1~beta1-1
 - Device Type: iPhone 6s. ([iPhone8,1])
- Jailbreak Type: Checkra1n. 

**Additional context** https://www.dropbox.com/s/s68f735s7l5xodt/Video%20Feb%2022%2C%2010%2030%2049%20AM.mp4?dl=0

**Comment by wstyres** [comment] 2020-02-22 15:44
Duplicate of #867

**Closed by wstyres** 2020-02-22 15:44 UTC
Labels: bug
