### ISSUE TITLE
Changes tab showing old tweaks

### ISSUE THREAD

**Issue by brkr1** [wstyres/Zebra#1257] opened 2020-05-18 23:19 UTC
**Describe the bug**
Changes tab shows old tweaks

**To Reproduce**
Update sources then go to changes tab

**Expected Behavior**
Changes tab show only updated tweaks

**Screenshots**

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <13.2.3>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <1.1.4>
 - Device Type [e.g. iPhone or iPad]: <iPhone X>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <Checkra1n>

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by eve0415** [comment] 2020-05-19 00:36
Duplicate of #996

**Closed** 2020-05-19 02:27 UTC
Labels: bug
