### ISSUE TITLE
Crash with https://apt.bingner.com/

### ISSUE THREAD

**Issue by Grisu70** [wstyres/Zebra#1129] opened 2020-04-23 05:55 UTC
**Describe the bug**
Repo 
https://apt.bingner.com/
Is added without problem, but if i tap on it to see the content. Zebra crash.

**To Reproduce**
Tap on repi

**Expected behavior**
Show repo content

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.4.1

 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1 beta6
 - Device Type [e.g. iPhone or iPad]: IphoneX
 - Jailbreak Type checkrain

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by eve0415** [comment] 2020-04-23 06:33
Duplicate of #1123

**Closed** 2020-04-23 13:55 UTC
Labels: bug
