### ISSUE TITLE
Can we get the feature from Cydia where you can select “User|Expert|Recent” in the packages section?

### ISSUE THREAD

**Issue by Garydunlop00** [wstyres/Zebra#1118] opened 2020-04-21 03:19 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by worldlydev** [comment] 2020-04-21 10:32
Duplicate of #678

**Closed** 2020-04-21 18:52 UTC
Labels: suggestion
