### ISSUE TITLE
Stuck on home page

### ISSUE THREAD

**Issue by walkerbagley** [wstyres/Zebra#1228] opened 2020-05-13 21:03 UTC
**Describe the bug**
When I open zebra, I get stuck on the home page and can’t navigate anywhere in the app. When I open using 3D Touch I can use all the other pages except home.

**To Reproduce**
Open zebra

**Expected behavior**
It should let me switch pages but it isn’t

**Screenshots**
If applicable, add screenshots to help explain your problem. N/A

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.4.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1.12
 - Device Type [e.g. iPhone or iPad]: iPhone 7
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue. Don’t have one

**Additional context**

**Comment by wstyres** [comment] 2020-05-13 21:40
Duplicate of #1211

**Closed by wstyres** 2020-05-13 21:40 UTC
