### ISSUE TITLE
Live search not working.

### ISSUE THREAD

**Issue by Pjryes** [wstyres/Zebra#1314] opened 2020-05-27 23:37 UTC
**Describe the bug**
Live Search is not showing tweaks/themes while typing. 

**To Reproduce**
Steps to reproduce the behavior: open Search tab, type for any tweak/theme name

**Expected behavior**
Tweaks/themes available showing while typing on search bar 

**Screenshots**
![44F7701C-21B5-4C3C-BA7D-FFA44DDA7B35](https://user-images.githubusercontent.com/34846407/83082339-244c5980-a051-11ea-897e-2efce7a595dd.png)
![2DEAEAA0-90EB-4479-97AD-1EFC88C25FCB](https://user-images.githubusercontent.com/34846407/83082342-257d8680-a051-11ea-81fd-ef1f3a057ef0.png)

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.5
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.2 beta1
 - Device Type [e.g. iPhone or iPad]: IPhoneX
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Unc0ver

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by aabosh** [comment] 2020-05-27 23:38
Duplicate of https://github.com/wstyres/Zebra/issues/1313, closing this issue.

**Closed by aabosh** 2020-05-27 23:38 UTC
Labels: bug
