### ISSUE TITLE
Buggg versão 17

### ISSUE THREAD

**Issue by mitsuoliver** [wstyres/Zebra#235] opened 2019-07-11 13:48 UTC
Date: 2019-07-11 13:46:05 +0000
Process: Zebra
Bundle id: xyz.willy.Zebra
Exception type: NSInvalidArgumentException
Reason: task already launched
Culprit: Unknown
Device: iPhone X, iOS 12.1.1
Call stack:
0   CoreFoundation                      0x00000001f2228edc __exceptionPreprocess
1   libobjc.A.dylib                     0x00000001f13f9a40 objc_exception_throw
2   CoreFoundation                      0x00000001f212f594 -[NSCache init]
3   Foundation                          0x00000001f2cf60f0 COPY_SETTER_IMPL
4   Zebra                               0x0000000100753e44 Zebra + 130628
5   UIKitCore                           0x000000021f340cc8 -[UIApplication sendAction:to:from:forEvent:]
6   UIKitCore                           0x000000021edce700 -[UIControl sendAction:to:forEvent:]
7   UIKitCore                           0x000000021edcea20 -[UIControl _sendActionsForEvents:withEvent:]
8   UIKitCore                           0x000000021edcda20 -[UIControl touchesEnded:withEvent:]
9   UIKitCore                           0x000000021f37a420 -[UIWindow _sendTouchesForEvent:]
10  UIKitCore                           0x000000021f37b684 -[UIWindow sendEvent:]
11  UIKitCore                           0x000000021f35a980 -[UIApplication sendEvent:]
12  UIKitCore                           0x000000021f4291ec __dispatchPreprocessedEventFromEventQueue
13  UIKitCore                           0x000000021f42bbe4 __handleEventQueueInternal
14  UIKitCore                           0x000000021f4246d4 __handleHIDEventFetcherDrain
15  CoreFoundation                      0x00000001f21b91f0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
16  CoreFoundation                      0x00000001f21b9170 __CFRunLoopDoSource0
17  CoreFoundation                      0x00000001f21b8a54 __CFRunLoopDoSources0
18  CoreFoundation                      0x00000001f21b3920 __CFRunLoopRun
19  CoreFoundation                      0x00000001f21b31f0 CFRunLoopRunSpecific
20  GraphicsServices                    0x00000001f442c584 GSEventRunModal
21  UIKitCore                           0x000000021f33f5b4 UIApplicationMain
22  Zebra                               0x0000000100751654 Zebra + 120404
23  libdyld.dylib                       0x00000001f1c72bb4 start

**Comment by PoomSmart** [comment] 2019-07-13 02:19
Duplicate of #234

**Closed by PoomSmart** 2019-07-13 02:19 UTC
Labels: bug
