### ISSUE TITLE
Zebra 1.1.7 not working

### ISSUE THREAD

**Issue by Golfboy69** [wstyres/Zebra#1279] opened 2020-05-23 14:51 UTC
When I install a tweak the loading screen gets stuck on “downloading packages”.
**To Reproduce**

**Expected behavior**

I expected the package to download and to respring.

**Screenshots**

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.4.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1.6 (the bug is on 1.1.7, I downgraded to avoid this bug)
 - Device Type [e.g. iPhone or iPad]: iPhone 6s
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by eve0415** [comment] 2020-05-23 15:01
Duplicate of #1273

**Comment by wstyres** [comment] 2020-05-23 19:52
This is a duplicate of #1273, try Zebra 1.1.8 and see if the issue is resolved.

**Closed by wstyres** 2020-05-23 19:52 UTC
Labels: bug
