### ISSUE TITLE
New Packages Tab

### ISSUE THREAD

**Issue by eleksploded** [wstyres/Zebra#117] opened 2019-05-24 18:42 UTC
**Is your feature request related to a problem? Please describe.**
Its hard to find new packages to install. 

**Describe the solution you'd like**
Add a tab that shows the newly added packages to the installed repos.

**Describe alternatives you've considered**
Add a list in the packages tab, but I feel like that would be to cluttered.

**Comment by wstyres** [comment] 2019-05-25 02:05
Duplicate of #25

**Closed by wstyres** 2019-05-25 02:05 UTC
Labels: enhancement
