### ISSUE TITLE
Zebra fails to ignore updates for the ` essential` package from the Bingner/Elucubratus repo.

### ISSUE THREAD

**Issue by mwoolweaver** [wstyres/Zebra#1029] opened 2020-04-02 05:41 UTC
**Describe the bug**

Zebra fails to ignore updates for the ` essential` package from the Bingner/Elucubratus repo.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1~beta4
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment] 2020-04-03 02:45
Duplicate of #972

**Closed by wstyres** 2020-04-03 02:45 UTC
Labels: bug, medium, packages

**Comment by mwoolweaver** [comment] 2020-04-07 07:02
Created a work around of my own for this issue

https://github.com/mwoolweaver/essential4all

Just created a “new” essential package with updated dependencies to include Zebra and Installer 5. Now I no longer have to ignore upgrades for the essential package from https://apt.bingner.com/

**Comment by mwoolweaver** [comment] 2020-04-15 18:13
@wstyres not sure this is a duplicate of #972 

This video demonstrates that ignore updates works for other packages but not the essential package I mentioned 


Couldn’t upload video here as it’s too long but I tweeted here 

https://twitter.com/mwooiweaver/status/1250486988614053890
