### ISSUE TITLE
Description of some tweaks are cut off

### ISSUE THREAD

**Issue by baobaoit** [wstyres/Zebra#667] opened 2019-12-08 10:46 UTC
**Describe the bug**

Depiction of some individuals are cutting off 

**To Reproduce**

Views the depiction of SiriUnlock and Supple

**Expected behavior**

**Screenshots**

Zebra
![542632CB-52B4-4D72-A0B8-06FF8060FCBD](https://user-images.githubusercontent.com/31947091/70388299-5e159f00-19e2-11ea-8f3e-7ab1d5069e27.png)
![A73D712B-4FF8-46F4-9173-F35429AA821B](https://user-images.githubusercontent.com/31947091/70388300-5e159f00-19e2-11ea-97b1-e8dfb67849af.png)

Cydia
![C132F035-ED04-45B3-8FA3-B5B951026788](https://user-images.githubusercontent.com/31947091/70388314-856c6c00-19e2-11ea-92f6-fc7c93bac27f.png)
![31E7FE2E-2ACB-4FA7-AF28-AF8AA9EBD47C](https://user-images.githubusercontent.com/31947091/70388305-6a016100-19e2-11ea-9b67-543a6a9ddbcd.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta31
 - Device Type [e.g. iPhone or iPad]: iPhone 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment] 2019-12-08 15:15
Is this only for packages with no actual depiction link?

**Comment by baobaoit** [comment] 2019-12-08 15:18
I’m not sure. Could you please check these tweaks.

**Comment by wstyres** [comment] 2019-12-08 17:50
What repo are they from?

**Comment by baobaoit** [comment] 2019-12-08 19:51
They come from https://cokepokes.github.io

**Comment by relisiuol** [comment] 2019-12-09 11:14
@wstyres That's caused by multi-lines descriptions. Good luck to fix that with C functions.

**Comment by wstyres** [comment] 2019-12-09 20:42
Fixed as of 4af55e488ad680595f3031a0a965c80101b928ee

**Closed** 2019-12-09 23:28 UTC
Labels: bug, scheduled

**Comment by baobaoit** [comment] 2019-12-10 06:36
@wstyres It still cut off with package SiriUnlock and Supple on the beta32-1.
