### ISSUE TITLE
Pressing “Open Documents Directory” in the Settings menu causes app crash.

### ISSUE THREAD

**Issue by mwoolweaver** [wstyres/Zebra#1066] opened 2020-04-13 04:59 UTC
**Describe the bug**

Pressing “Open Documents Directory” at the bottom of the Settings menu causes app crash.

**To Reproduce**

Press “Open Documents Directory” at the bottom of the Settings menu causes app crash.

![9D26A8D4-40AC-483B-998D-FA9D969729D2](https://user-images.githubusercontent.com/5729320/79093228-3bd9b800-7d19-11ea-91c2-924e2c3525a6.jpeg)

**Expected behavior**
Open Filza to Documents directory.

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <13.4>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <1.1-beta4>
 - Device Type [e.g. iPhone or iPad]: <iPhone 8 Plus>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <checkra1n>

**Crash Log or System Log**
[crash log as reported by cr4shed](https://github.com/wstyres/Zebra/files/4468063/text.txt)

**Additional context**

**Comment by eve0415** [comment] 2020-04-13 04:59
Duplicate of #1015

**Closed** 2020-04-13 05:00 UTC
Labels: bug
