### ISSUE TITLE
crashing when i added all repos from cydia

### ISSUE THREAD

**Issue by KurdishBoy93** [wstyres/Zebra#9] opened 2019-04-11 22:33 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - AUPM Version [e.g. 1.0~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

**Additional context**

Date: 2019-04-11 22:31:01 +0000
Process: Zebra
Bundle id: xyz.willy.Zebra
Exception type: NSInvalidArgumentException
Reason: *** -[NSPlaceholderString initWithUTF8String:]: NULL cString
Culprit: Unknown
Device: iPhone 8 Plus, iOS 12.1.1
Call stack:
0   CoreFoundation                      0x00000001b3094edc __exceptionPreprocess
1   libobjc.A.dylib                     0x00000001b2265a40 objc_exception_throw
2   CoreFoundation                      0x00000001b2f9b594 -[NSCache init]
3   Foundation                          0x00000001b3a2df88 -[NSString initWithUTF8String:]
4   Zebra                               0x00000001022e1518 Zebra + 21784
5   Zebra                               0x00000001022f43e4 Zebra + 99300
6   Zebra                               0x00000001022fa998 Zebra + 125336
7   Zebra                               0x00000001022fa220 Zebra + 123424
8   UIKitCore                           0x00000001dfd3191c -[UIViewController _setViewAppearState:isAnimating:]
9   UIKitCore                           0x00000001dfd32000 -[UIViewController __viewWillAppear:]
10  UIKitCore                           0x00000001dfc8ec88 -[UINavigationController viewWillAppear:]
11  UIKitCore                           0x00000001dfd3191c -[UIViewController _setViewAppearState:isAnimating:]
12  UIKitCore                           0x00000001dfd32000 -[UIViewController __viewWillAppear:]
13  UIKitCore                           0x00000001dfc6d130 -[UITabBarController transitionFromViewController:toViewController:transition:shouldSetSelected:]
14  UIKitCore                           0x00000001dfc6c38c -[UITabBarController transitionFromViewController:toViewController:]
15  UIKitCore                           0x00000001dfc68a70 -[UITabBarController _setSelectedViewController:]
16  UIKitCore                           0x00000001dfc68840 -[UITabBarController setSelectedViewController:]
17  UIKitCore                           0x00000001dfc6c2a4 -[UITabBarController _tabBarItemClicked:]
18  UIKitCore                           0x00000001e02f4cc8 -[UIApplication sendAction:to:from:forEvent:]
19  UIKitCore                           0x00000001dfb5f9d4 -[UITabBar _sendAction:withEvent:]
20  UIKitCore                           0x00000001e02f4cc8 -[UIApplication sendAction:to:from:forEvent:]
21  UIKitCore                           0x00000001dfd82700 -[UIControl sendAction:to:forEvent:]
22  UIKitCore                           0x00000001dfd82a20 -[UIControl _sendActionsForEvents:withEvent:]
23  UIKitCore                           0x00000001dfb62368 -[UITabBar _buttonUp:]
24  UIKitCore                           0x00000001e02f4cc8 -[UIApplication sendAction:to:from:forEvent:]
25  UIKitCore                           0x00000001dfd82700 -[UIControl sendAction:to:forEvent:]
26  UIKitCore                           0x00000001dfd82a20 -[UIControl _sendActionsForEvents:withEvent:]
27  UIKitCore                           0x00000001dfd81a20 -[UIControl touchesEnded:withEvent:]
28  UIKitCore                           0x00000001dff0949c _UIGestureEnvironmentSortAndSendDelayedTouches
29  UIKitCore                           0x00000001dff04198 _UIGestureEnvironmentUpdate
30  CoreFoundation                      0x00000001b30247cc __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
31  CoreFoundation                      0x00000001b301f460 __CFRunLoopDoObservers
32  CoreFoundation                      0x00000001b301fa00 __CFRunLoopRun
33  CoreFoundation                      0x00000001b301f1f0 CFRunLoopRunSpecific
34  GraphicsServices                    0x00000001b5298584 GSEventRunModal
35  UIKitCore                           0x00000001e02f35b4 UIApplicationMain
36  Zebra                               0x00000001022e7340 Zebra + 45888
37  libdyld.dylib                       0x00000001b2adebb4 start

**Comment by wstyres** [comment] 2019-04-11 23:30
Duplicate of #8, see feedback in that issue.

**Closed by wstyres** 2019-04-11 23:30 UTC
Labels: bug, duplicate
