### ISSUE TITLE
Crash when adding repo URL from clipboard

### ISSUE THREAD

**Issue by Aditya245850** [wstyres/Zebra#552] opened 2019-11-12 01:24 UTC
Basically when you copy a repo from safari or something and then open zebra. Zebra finds a repo in your clipboard and then tries to install it, but it crashes when that happens. 

Basically what you have to do is copy a repo from safari. Open zebra. Go to sources. Zebra will recognize the repo, so press ok. Then the crash happens. It doesn’t even install it.

 - iOS Version: 13.2.2
 - Zebra Version: 26-4
 - Device Type: iPhone X(10,3)

**Comment by wstyres** [comment] 2019-11-12 01:34
Are you able to reproduce this with every URL or just certain ones? I'm not able to reproduce it.

**Comment by Aditya245850** [comment] 2019-11-12 01:42
It happens to all for me.

**Comment by wstyres** [comment] 2019-11-12 01:54
Could I get a list of repos that you have already added?

**Comment by Aditya245850** [comment] 2019-11-12 01:58
https://apt.bingner.com/ https://repo.midnightchips.me/ http://cydia.zodttd.com/repo/cydia/ http://rpetri.ch/repo/ 
http://apt.modmyi.com/ https://getzbra.com/beta/ 
https://ib-soft.net/cydia/ http://tigisoftware.com/cydia/ http://repo.packix.com/ https://esquillidev.github.io/ http://repo.pixelomer.com/ http://junesiphone.com/supersecret/ https://cydia.ichitaso.com/ https://samgisaninja.github.io/ https://diatr.us/sileo/ http://apt.thebigboss.org/repofiles/cydia/ https://getzbra.com/repo/ http://gmoran.me/repo/ https://creaturecoding.com/repo/ http://skylerk99.github.io/
https://skitty.xyz/repo/ 
https://repo.dynastic.co/ http://cydia.angelxwind.net/ https://maybeme.fr/ 
https://sparkdev.me/ https://dpkg9510.github.io/ https://idevicehacked.com/ http://limneos.net/repo/ https://shiftcmdk.github.io/repo/ https://cokepokes.github.io/ http://getdelta.co/ https://dunkston.github.io/repo/ https://repo.chariz.io/ http://coolstar.org/publicrepo/ http://exqusic.github.io/ https://creaturesurvive.github.io/ http://repo.incendo.ws/ https://checkra.in/assets/mobilesubstrate/

**Comment by wstyres** [comment] 2019-11-12 02:12
Ok, thank you, I will investigate this issue a little more.

**Comment by Aditya245850** [comment] 2019-11-12 02:14
Glad I could help! Also if you don’t mind me asking, will zebra have a ui overhaul in the future. The current ui is good but there is so much potential with this great package manager. I can consider this the best package manager as of right now.

**Comment by wstyres** [comment] 2019-11-12 02:15
Yes, a redesign of Zebra is planned after its initial release.

**Comment by worldlydev** [comment] 2019-11-12 07:34
> Yes, a redesign of Zebra is planned after its initial release.

Looking forward to it but I hope it isn't a step backwards. The current UI is incredibly functional and easy to use compared to something like Installer.

**Comment by Aditya245850** [comment] 2019-11-12 19:42
Of course, that’s why zebra is really good. Installer is way to much feature packed that it isn’t rlly good imo.

**Comment by wstyres** [comment] 2019-11-14 00:04
This should be fixed in beta27, I will leave the issue open in case you still experience it.

**Closed** 2019-11-14 14:17 UTC
Labels: bug, scheduled
