### ISSUE TITLE
Search Bar doesn’t load anything

### ISSUE THREAD

**Issue by gerbil-snot** [wstyres/Zebra#1322] opened 2020-05-28 02:23 UTC
**Describe the bug**
When searching for tweaks, nothing will appear, even after doing a full source refresh

**To Reproduce**
Search for a tweak, or just type a single letter into the search bar, nothing will appear

**Screenshots**
![A757AAE2-DA51-434F-BB8B-7457AA169A75](https://user-images.githubusercontent.com/29874563/83091111-0e926080-a060-11ea-9047-7456a9102818.png)

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: iOS 13.5
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.2~beta1a
 - Device Type [e.g. iPhone or iPad]: iPhone XS Max
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver v5.0.1

**Comment by eve0415** [comment] 2020-05-28 02:24
Duplicate of #1313 
Also, you have to at least type two letters to live search.

**Comment by aabosh** [comment] 2020-05-28 03:13
Duplicate of #1313, closing.

**Closed by aabosh** 2020-05-28 03:13 UTC
Labels: bug
