### ISSUE TITLE
Swipe to right in package depiction to filter developer

### ISSUE THREAD

**Issue by Greigh** [wstyres/Zebra#1305] opened 2020-05-27 00:12 UTC
**Is your feature request related to a problem? Please describe.**
It is difficult to have to remember the name of the developer of a repo when I see a developer I never want to see again, especially when their name is in an eastern language such as Chinese, Korean, etc.

**Describe the solution you'd like**
Possibly an option to swipe on the developer's name and have a filter button for you to click to add a filter. 

**Describe alternatives you've considered**
Possibly another way to do it is to give us the option of copying the email and/or name associated with the developer to be able to paste into the filter option but out of convenience, I think the option above is more viable.

**Comment by wstyres** [comment] 2020-05-27 00:13
Duplicate of #1037

**Closed by wstyres** 2020-05-27 00:13 UTC
Labels: suggestion
