### ISSUE TITLE
Appearance settings being reset on launch

### ISSUE THREAD

**Issue by MTACS** [wstyres/Zebra#976] opened 2020-03-25 19:15 UTC
**Describe the bug**

Selecting light mode in settings applies, although some interface elements do not update. When closing and relaunching Zebra the interface defaults back to dark mode

**To Reproduce**

Set Zebra to light mode, close and relaunch app

**Expected behavior**

Settings values to remain set. 

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [13.2.2]: 
 - Zebra Version [1.1~beta3-1]: 
 - Device Type [iPhone X]: 
 - Jailbreak Type [Checkra1n]: 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment] 2020-03-25 19:55
To be clear, this is with "Use System Appearance" turned off?

**Comment by wstyres** [comment] 2020-03-25 20:06
I'm not able to reproduce this which makes me think that you might have some left over settings that were in Zebra 1.0.x that keep getting reset when transferring over to 1.1.

**Comment by wstyres** [comment] 2020-03-25 20:09
Could I also see the contents of the file `/var/mobile/Library/Preferences/xyz.willy.Zebra.plist`?

**Comment by MTACS** [comment] 2020-03-25 20:10
Didn’t even think to reset preferences, that worked for me, do you still want to see that file?

**Comment by wstyres** [comment] 2020-03-25 20:12
Well now that the file is reset it isn't so useful anymore :p I assume I was correct in that there were some leftover preferences in 1.0.x but without the old file I have no way in knowing which ones were there.

**Comment by MTACS** [comment] 2020-03-25 20:14
I can downgrade if needed, wondering if it’s a user defaults issue

**Comment by wstyres** [comment] 2020-03-25 20:25
Looks like a mistake on my part, I transferred the old settings but did not remove the key once I set the new ones. Fixed in af340f5bdaf6a71ee8d47bac5d927e9ee6f99679 and will be in the next beta.

**Closed** 2020-04-01 15:48 UTC
Labels: bug, medium, scheduled, settings
