### ISSUE TITLE
[BUG] Zebra doesn't identify sources with storefronts until clearing cache

### ISSUE THREAD

**Issue by SeMoOoR** [wstyres/Zebra#1157] opened 2020-04-27 19:49 UTC
**Describe the bug**
Title. After installing beta 7, Zebra wasn't showing any storefronts in Store page. I did a cache reset of sources and it worked fine but appeared again after a while. I don't know how to reproduce it. Currently, the issue is consistent and won’t go even with a source cache reset.

**To Reproduce**
- it happened after installing Zebra 1.1~beta 7

**Expected behavior**
Zebra shall properly identify sources with storefronts.

**Screenshots**
![0515C0E3-0EA7-4A3D-B273-38748DFE9CE4](https://user-images.githubusercontent.com/25428973/80414105-2d72cb00-88d9-11ea-8d81-8677518195c5.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1~beta 7
 - Device Type [e.g. iPhone or iPad]: 12,5
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.
N/A

**Additional context**
N/A

**Comment by wstyres** [comment] 2020-04-27 23:14
Can't reproduce this issue, are you able to see the banner that appears when going into a source? Try Chariz or Dynastic for example.

**Comment by SeMoOoR** [comment] 2020-04-27 23:24
I am able to see the source and features packages. All sources load properly yet Zebra is not allowing to log in into these sources.

![89427D9C-4341-4FA0-895B-3B8686196B18](https://user-images.githubusercontent.com/25428973/80430463-599d4480-88f7-11ea-96a0-6ba5e80b565c.png)
![0B764BCB-CA4D-46BA-ADEA-E859DD561760](https://user-images.githubusercontent.com/25428973/80430470-5dc96200-88f7-11ea-9b04-99c9b776a389.png)

**Comment by wstyres** [comment] 2020-04-27 23:26
Could you send your database file? Go to settings and open Zebra's Documents Directory and get the file named zebra.db

**Comment by SeMoOoR** [comment] 2020-04-27 23:39
https://mega.nz/file/1vJ3AYDS#v8sEgobX2xV4vauwxrXNdvuOKPtHxWTc34Z-XSLPBIs

**Comment by wstyres** [comment] 2020-04-27 23:42
Hm, could you remove Chariz and re-add it as https://repo.chariz.com? In your sources file it is listed as `http://repo.chariz.io` which isn't using `https://` and is using the old sources URL. Just want to make sure that isn't the problem.

**Comment by SeMoOoR** [comment] 2020-04-27 23:45
After deleting and regarding the source it appears in Store. But I have Dynastic repo in https:// and yet it doesn't show up.

**Comment by SeMoOoR** [comment] 2020-04-27 23:59
Resetting the sources cache again solved the issue. I still don't know the cause of it and I still can't reproduce it.

**Comment by wstyres** [comment] 2020-04-28 00:16
I'm thinking that this might've been a fluke when refreshing your sources for the first time, I'll leave the issue open for a bit in case it happens again though.

**Comment by SeMoOoR** [comment] 2020-04-28 21:41
I managed to reproduce the big (hopefully). The bug occurs when a source refresh gets interrupted. NoStorefronts will be consistent even after a successful source refresh and sources cache reset.

**Comment by wstyres** [comment] 2020-04-28 22:00
Thats what I suspected, how did you interrupt the source refresh?

**Comment by SeMoOoR** [comment] 2020-04-28 22:01
By canceling the refresh action before it finishes.

**Comment by wstyres** [comment] 2020-04-28 22:11
I'll see what I can do about this. A bit tricky because the payment API requires us to repeatedly query for the payment URL, Zebra tries to download it the first time so it never has to again.

**Comment by SeMoOoR** [comment] 2020-04-28 22:19
In addition, Zebra will crash once you click or try to refresh the Store page.

This is the crashlog from Cr4shed
https://pastebin.com/U7x1TLzc

**Comment by wstyres** [comment] 2020-04-28 22:33
Just fixed that crash

**Comment by SeMoOoR** [comment] 2020-04-28 22:47
Thanks.

**Comment by wstyres** [comment] 2020-04-29 23:02
Looked into this a little bit, are you sure a simple source refresh does not fix this problem? I reproduced by deleting Chariz's vendor URL from the database and simply pulling to refresh on the sources page and the payment info came back.

**Comment by SeMoOoR** [comment] 2020-04-29 23:06
I am not able to resolve it. Even after a full Zebra reset (sources delete an settings). Nothing seems to solve. I tried removing and adding Chariz’s repo alone but the payment information won't show up.

I am happy to diagnose the issue further to help preventing it.

**Comment by wstyres** [comment] 2020-04-29 23:07
If you downgrade to beta 6 does that fix the issue?

**Comment by SeMoOoR** [comment] 2020-04-29 23:08
I will try it now and I will edit this comment to confirm.

**Comment by wstyres** [comment] 2020-04-29 23:21
I don't think any payment information was changed between beta 6 and beta 7 so I have no idea why you are experiencing this issue. The bug with those sources not verifying was fixed on beta 7 though so that's why there were some issues. Does upgrading back to 7-1 fix it?

If I can't reproduce the issue on my end there is little I can do to fix it. There are a number of things that could be going on here but I can't track them down without more information which is difficult without the device in front of me. I'll leave the issue open for a few more days but might have to close this as don't reproduce.

**Comment by SeMoOoR** [comment] 2020-04-29 23:25
Zebra beta7-1 now functions properly. I guess I had something faulty going with Zebra db/files that was consistent even after a full reset on my end. 

Thanks for your trouble. Much appreciated.

**Comment by wstyres** [comment] 2020-04-29 23:30
No problem at all, glad that it started working again.

**Closed by wstyres** 2020-04-29 23:30 UTC
Labels: bug, medium, sources
