### ISSUE TITLE
Can't purchase package from Chariz

### ISSUE THREAD

**Issue by yur1xpp** [wstyres/Zebra#1121] opened 2020-04-21 15:12 UTC
**Describe the bug**
No window pop-up/nothing happens after tapped the price on top right for Chariz repo, that's when you're on the "Changes" tab. When you're on the "Search" tab, the top right button is "Install" instead of the price, and authorization failed (as expected because I haven't purchase yet). Tested tweak is SwipeExtenderX.

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.4.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: latest, beta6
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Comment by wstyres** [comment] 2020-04-21 15:24
Could you post more information? Screen recordings? Package names?

**Comment by yur1xpp** [comment] 2020-04-21 16:17
It seems like the underlying issue should probably be because it requires FaceID authentication. I repeatedly get faceid prompt appears and disappear in very amount short time, and this issue occur pretty randomly. I'll let you know once I got it captured. Ah the package name is SwipeExtenderX. It occurs for another package too, like iDunnoU.

**Comment by wstyres** [comment] 2020-04-21 16:56
Have you denied Zebra access to Face ID?

**Comment by wstyres** [comment] 2020-04-28 21:33
Will close the issue if you cannot reproduce anymore.

**Closed by wstyres** 2020-04-28 21:33 UTC
Labels: bug, purchases, question
