### ISSUE TITLE
[bug] keeps showing updates for bettersettings and shuffle

### ISSUE THREAD

**Issue by Amplespencer** [wstyres/Zebra#153] opened 2019-06-04 17:55 UTC
**Describe the bug**
I see bettersettings and shuffle updates, I can’t install bettersettings because of libcolorpicker conflicting with the a12 version and shuffle doesn’t have an update
**To Reproduce**
No idea? maybe install an old bettersettings then remove it?
**Screenshots**
ok
**Device Information (please complete the following information):**
 - 12.1.1
 - Zebra Version B13
 - Device Type iPhone XR-A12
**Additional context**
may be related to ghost update issue

**Comment by Amplespencer** [comment] 2019-06-04 17:57
well shit now I don’t see the add screenshot button :/ sorry I might try and add them on pc later

**Comment by wstyres** [comment] 2019-06-05 00:50
Does this update show in Cydia? Also, what version do you have installed and what version is Zebra trying to update to?

**Comment by Amplespencer** [comment] 2019-06-05 00:52
Shuffle - 1.04
updating to version already updated

BetterSettings - max version even though it’s uninstalled and I keep
presisng ignore updates

it doesn’t show up in Sileo and probably wouldn’t in Cydia-Dark either

**Comment by Muirey03** [comment] 2019-06-05 06:48
This was fixed by PoomSmart in a later commit. Please close this issue @wstyres

**Comment by PoomSmart** [comment] 2019-06-05 11:49
Duplicate of #149

**Closed by PoomSmart** 2019-06-05 11:49 UTC
Labels: bug
