### ISSUE TITLE
Zebra was unable to complete this commed - iOS 12.1 Chimera

### ISSUE THREAD

**Issue by AhmedAlNeaimy** [wstyres/Zebra#934] opened 2020-03-06 03:32 UTC
Hi, 

I used Zebra for 2 days normally without any issues, today i can’t install/upgrade/remove anything apps/tweaks using Zebra!

I got this error every time:
Zebra was unable to complete this commend because it does not have the proper permissions. Please verify the permissions located at /usr/libexec/zebra/supersling

I checked the “Supersling” permissions it’s set to: 06755

— 

My iPhone informations:
- iPhone XS Max
- iOS 12.1
- Chimera Jailbreak
- Zebra version 1.1~beta2-1 from offical Zebra repo

Any suggestions please?

Screenshots:
[1-](https://i.imgur.com/35ISkwb.png) 
[2-](https://i.imgur.com/o3zpU0J.png) 
[3-](https://i.imgur.com/kOsEeD0.png) 
[4-](https://i.imgur.com/0NKeE1O.png)

**Comment by wstyres** [comment] 2020-03-06 17:48
Looks like a duplicate of #888 please check that out for more information. You can downgrade to Zebra 1.0.7 to have a functioning version while I develop a better fix.

**Closed by wstyres** 2020-03-06 17:48 UTC
Labels: bug
