### ISSUE TITLE
Zebra crashes if you click a suggested tweak while it first opens/loads sources

### ISSUE THREAD

**Issue by shadowscott** [wstyres/Zebra#1182] opened 2020-05-03 22:14 UTC
**Describe the bug**
Title^

**To Reproduce**
Not 100% but open Zebra and click the first suggested app as soon as the app loads

**Expected behavior**
It doesn't crash 

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: latest beta
 - Device Type [e.g. iPhone or iPad]: iPhone 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Checkra1n 

**Crash Log or System Log**
https://pastebin.com/EqVxZchy

**Comment by wstyres** [comment] 2020-05-08 00:02
Can't reproduce this issue, was it a one time problem or does it happen every time?

**Comment by shadowscott** [comment] 2020-05-08 00:35
Just was able to reproduce. Open zebra and if your sources are syncing, repeatedly click on a suggested tweak and then home and repeat. I had to refresh sources from the changes tab, switch back to home, and then click a suggested tweak and go back. This is just the way I was able to force it, but it happens sometimes when I open zebra fresh.

**Comment by wstyres** [comment] 2020-05-14 20:04
Might be fixed as of 28d81af1ea7c644fae8d677c9a5d03d072d1499c. Please check to see if this still occurs when 1.1.4 is released.

**Comment by wstyres** [comment] 2020-05-20 19:42
Closed due to inactivity.

**Closed by wstyres** 2020-05-20 19:42 UTC
Labels: bug, question
