### ISSUE TITLE
Conflicting tweak installation/removal queue issue

### ISSUE THREAD

**Issue by yur1xpp** [wstyres/Zebra#710] opened 2019-12-19 11:53 UTC
**Describe the bug**
It seems like zebra didn’t manage conflicting tweak very well when trying to install or uninstall them. Removing the one that have conflict in it control file didn’t create any issue, however, if you queue the conflicted tweak to be removed, and trying to install a new tweak that conflict with it, the queue shows 3 packages, instead of only two.

**To Reproduce**
Remove flexing or flexall if your have it installed so that you can reproduce what I’m facing.

Download flexall from here https://level3tjg.xyz/com.dgh0st.flexall_0.0.1-10_iphoneos-arm.deb and install via zebra

Next, open zebra and queue flexall to uninstall

Proceed with installing flexing in queue.
Tap and see the queue.

If you don’t add flexall into queue, but instead directly queue flexing into installation, this issue will not happens.

**Expected behavior**
Zebra should mange the conflicts automatically, without queuing duplicating packages

**Screenshots**
https://imgur.com/a/o0uxyiu

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: latest non-beta
 - Device Type [e.g. iPhone or iPad]: iPhone 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by eve0415** [comment] 2019-12-19 12:49
How did you install two FREXall?

**Comment by eve0415** [comment] 2019-12-19 14:01
https://cdn.discordapp.com/attachments/572784833714192395/657219528966668309/video0.mp4
I tested and the issue is not about conflicting I think.
I guess that it is the issue that I can queue two packages that is same, just the version is different. I can queue the package that is not upgraded and the one with the latest package that is not installed at all. If you can watch the video, I am queuing the packaged with the one Zebra tells me to upgrade to the latest.
![9DAE2E9B-ABD1-4BA1-9AD2-B144242A6558](https://user-images.githubusercontent.com/40632436/71179356-5643dd80-22b3-11ea-86f1-f0b7d51e4a42.png)

**Comment by eve0415** [comment] 2019-12-19 14:10
I think it is almost the same as #705 
I can queue anything with the one that is not the latest and the one that Zebra is offering to upgrade

**Comment by wstyres** [comment] 2019-12-19 16:03
Fixed as of 7ae50e4caf758241bef31154d84790226fbf5f98.

**Closed** 2019-12-19 22:28 UTC
Labels: bug, dependency, queue, scheduled
