### ISSUE TITLE
Does not install packages sometimes

### ISSUE THREAD

**Issue by Aditya245850** [wstyres/Zebra#586] opened 2019-11-17 03:18 UTC
This bug is really weird. It happens sometimes and doesn't happen sometimes. It bascially does not install the package even though it shows the package already installed(within the console, it shows "finished").

It will not install the package, and you will end up with a restart springboard or done button. When you open zebra and check if the package is installed, it is not.

 - iOS Version 13.2.2
 - Zebra Version :27-1
 - Device Type: iPhone X(10,3)
 - Jailbreak Type: Checkra1n 9.5.0

**Comment by wstyres** [comment] 2019-11-17 18:47
Is there a screenshot of the console that you can provide? It would be helpful in debugging this issue.

**Comment by Aditya245850** [comment] 2019-11-17 18:48
I really don’t know what to take a screenshot of. The console or after the console to show the package hasn’t been installed?

**Comment by Aditya245850** [comment] 2019-11-17 18:50
It is also very random, I don’t think I can replicate it until I randomly install some tweaks. I will try to get a screenshot when it happens.

**Comment by wstyres** [comment] 2019-11-17 19:04
Take a screenshot of the console if you can.

**Comment by Aditya245850** [comment] 2019-11-17 19:09
How would I post one onto the comments? I’m really new to github sorry.

**Comment by LuaDeathGame** [comment] 2019-11-20 14:09
I think is the same problem that happens to me. ¿Do you remember?

**Comment by LuaDeathGame** [comment] 2019-11-20 14:09
The problem you solve for me.

**Comment by wstyres** [comment] 2019-11-20 14:53
It is possible that it could be related to that but I would need confirmation about the repos and the packages that the user is trying to download from in order for me to confirm that.

**Comment by wstyres** [comment] 2019-11-22 15:19
@Aditya245850 have you noticed the issue on the latest beta?

**Comment by Aditya245850** [comment] 2019-11-22 16:15
Yea it’s the same, but I’m usually using dark mode, so it doesn’t bother me much.

**Comment by Aditya245850** [comment] 2019-11-22 16:19
Yea it sometimes happens and what I noticed is that even if it is a package that is supposed to say restart springboard, it says done instead

**Comment by wstyres** [comment] 2019-11-22 16:20
And did you get a video or a screen recording of the package when it doesn't install properly?

**Comment by Aditya245850** [comment] 2019-11-22 16:23
That’s actually the weird thing. Now it actually freezes when it does that, so I can’t do anything until I restart my phone. So I’m unable to get any kind of screenshot or screen recording.

**Comment by wstyres** [comment] 2019-11-22 16:28
Any details about packages that you're trying to install or repos that the packages are from would be very helpful. Otherwise I am afraid we can't reproduce this issue and we'll have to close it.

**Comment by Aditya245850** [comment] 2019-11-22 16:41
I’ve noticed it only comes from packages you are installing for the first time.

**Comment by wstyres** [comment] 2019-11-26 19:44
If we can't reliably reproduce the issue then theres no way for us to fix it unfortunately. I've added some extra logging when in the console in the latest Zebra beta. See if you notice any new messages when installing packages or if you can reproduce the error again. If you experience the issue again, _please_ take a screenshot of the console output. Otherwise I will have to close the issue as "cannot reproduce".

**Closed** 2019-11-28 22:28 UTC
Labels: bug, outdated, question
