### ISSUE TITLE
Refresh control icon is not being colored correctly

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#620] opened 2019-11-23 23:53 UTC
#599 and #603 weren't properly fixed. I can still reproduce them in beta 29-3.

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.1 b3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
Beta 29-3
 - Device Type [e.g. iPhone or iPad]: iPhone Xs
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Chimera

**Comment by PoomSmart** [comment] 2019-11-27 14:14
How about beta 29-4?

**Comment by worldlydev** [comment] 2019-11-27 14:44
> How about beta 29-4?

Neither of the bugs seem to be fixed in beta 29-4.

**Comment by PoomSmart** [comment] 2019-12-01 01:29
And now beta 30-1?

**Comment by worldlydev** [comment] 2019-12-01 13:58
> And now beta 30-1?

Neither of the bugs are fixed in the latest beta. 
![08352A26-7B89-4D81-914A-A9FBB8A0E487](https://user-images.githubusercontent.com/51668635/69915056-15427100-144b-11ea-82d7-e4e8f59e9de7.jpeg)

**Comment by relisiuol** [comment] 2019-12-09 02:29
You're using a beta iOS versions, that's why I think.

**Comment by worldlydev** [comment] 2019-12-15 10:21
> You're using a beta iOS versions, that's why I think.

Don't have access to my jailbroken Xs anymore. @eve0415 you have a Xs on 12.4 right? Since you aren't on a beta could you check to see if both these issues are fixed?

**Comment by eve0415** [comment] 2019-12-15 12:33
I think #603 is fixed.
I have a little issue with #599 though.
Sometime it is black when in dark mode.
I will try to reproduce and take videos

**Comment by eve0415** [comment] 2019-12-15 13:18
https://cdn.discordapp.com/attachments/572784833714192395/655750240569393154/video0.mov
Looks like it is tinted black in dark mode when the source are refreshing automatically. 
However, refreshing manually is tinted white

**Comment by wstyres** [comment] 2019-12-15 20:43
Not able to reproduce in iOS 13 but I see this issue in 12.4 for appearing the correct color after refreshing once.

**Comment by wstyres** [comment] 2019-12-15 22:04
Tested on 11.4, 12.4 and 13.2 and all of these seem to be working with the "automatic refresh" as of 7fcd872a5d44800ea8c58091026ac6a6c94b3920. It will be in the next beta but I'll leave this issue open just in case.

**Comment by wstyres** [comment] 2019-12-17 22:37
Should be fixed in 1.0~rc1, give it a try.

**Comment by eve0415** [comment] 2019-12-18 06:18
Yes, I think it’s fixed.

**Closed** 2019-12-18 19:58 UTC
Labels: bug, outdated, scheduled
