### ISSUE TITLE
Can’t install more tweaks at the same time

### ISSUE THREAD

**Issue by iMonZ** [wstyres/Zebra#772] opened 2020-01-02 13:34 UTC
**Describe the bug**
When I try to install a few tweaks at the same time I get this error message!

**Screenshots**

![F835773D-B325-484D-A015-0A539FCEE422](https://user-images.githubusercontent.com/11319871/71669370-c0a55500-2d6c-11ea-8c32-b3595f065777.png)

**Device Information (please complete the following information):**
 - iOS Version [13.3.1b1]: 
 - Zebra Version [1.0]: 
 - Device Type [e.g. iPhone10,6]: 
 - Jailbreak Type [checkra1n]:

**Comment by wstyres** [comment] 2020-01-02 15:46
Duplicate of #748

**Closed by wstyres** 2020-01-02 15:46 UTC
Labels: bug
