### ISSUE TITLE
If a package in the queue conflicts with another package and a removal of the conflicting package is added to the queue, Zebra still doesn’t allow the user to continue and install/remove the queued packages

### ISSUE THREAD

**Issue by ctalbot4** [wstyres/Zebra#775] opened 2020-01-02 20:29 UTC
1. Install OnlySmallVolHUD (conflicts with Ultrasound)
2. Add Ultrasound to the queue
3. Zebra says that Ultrasound conflicts with OnlySmallVolHUD
4. Add removal of OnlySmallVolHUD to the queue
5. Zebra still doesn’t allow you to install/remove packages

**Expected behavior**
1. Install OnlySmallVolHUD
2. Add Ultrasound to the queue
3. Zebra automatically adds a removal of OnlySmallVolHUD to the queue since it conflicts
4. Zebra allows the user to proceed with installation

**Screenshots**
![5FDBBA8A-B8ED-49A5-9338-D1100FD4F822](https://user-images.githubusercontent.com/11797376/71691090-70ca8c00-2d74-11ea-8151-2efbcf6ae88d.png)
![B328DA36-C82D-4C7B-BA15-6FB004E7A1C1](https://user-images.githubusercontent.com/11797376/71691091-71632280-2d74-11ea-8c94-5d7cf31b3ad4.png)

Device info:
 - iOS Version: 13.3
 - Zebra Version: 1.0
 - Device Type: iPhone X 
 - Jailbreak Type: checkra1n

**Comment by eve0415** [comment] 2020-01-02 23:43
duplicate of #753 ?

**Comment by wstyres** [comment] 2020-01-02 23:47
It does sound like #753 to me.

**Closed** 2020-01-02 23:47 UTC
Labels: bug, duplicate

**Comment by ctalbot4** [comment] 2020-01-02 23:50
I misunderstood #753 when I first read it but now that I look at it again this is a duplicate.
