### ISSUE TITLE
Issues with "Pure Black Mode" when transitioning between light/dark mode

### ISSUE THREAD

**Issue by kelvin1300** [wstyres/Zebra#1020] opened 2020-04-01 16:08 UTC
https://www.dropbox.com/sh/vb1jtb28m36aonh/AABCn6w5xMxL8jDS-SuJA00Ga?dl=0

**Comment by absidue** [comment] 2020-04-01 16:12
@kelvin1330 Can you please provide all information requested in the bug issue template. Also please choose a more helpful title.

**Comment by kelvin1300** [comment] 2020-04-01 16:14
Sorry, but you look the video they has to fix Dark mode and Light Mode with the system wide of iOS 🤷‍♂️

**Comment by absidue** [comment] 2020-04-01 16:17
Fixing the bug is significantly easier if you provide all the necessary information.

**Comment by kelvin1300** [comment] 2020-04-01 16:19
Broth I don’t know 🤷‍♂️ how I can provide more information than that video. One weird question. Are you Developing Zebra or what?

**Comment by absidue** [comment] 2020-04-01 16:23
This is the full bug template (copied directly from: https://github.com/wstyres/Zebra/issues/new?assignees=&labels=bug&template=bug_report.md&title=)

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**
Add any other context about the problem here.

**Comment by eve0415** [comment] 2020-04-01 16:29
You should at least write what iOS are you using. For me, I can’t reproduce that changing light mode to dark mode and vice versa. Using iOS 13.3, beta4 & checkra1n.

**Comment by wstyres** [comment] 2020-04-26 20:01
Seems to be fixed as of 91ab468ca3e3094137d04965ac936244470e913f.

**Closed** 2020-04-28 01:38 UTC
Labels: bug, low, scheduled, settings
