### ISSUE TITLE
Add a history tab so we can see tweak we have had in the past.

### ISSUE THREAD

**Issue by Garydunlop00** [wstyres/Zebra#823] opened 2020-01-16 15:59 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wstyres** [comment] 2020-01-19 03:26
Likely a duplicate of #740

**Closed by wstyres** 2020-01-19 03:26 UTC
Labels: suggestion
