### ISSUE TITLE
Upgrade button is not showing

### ISSUE THREAD

**Issue by Azwaah** [wstyres/Zebra#1544] opened 2020-09-12 08:27 UTC
![184F9AB4-86DF-46DC-94BA-B09C28EAB219](https://user-images.githubusercontent.com/45119460/92991181-15e85780-f4f3-11ea-8b43-a3bb77a95d62.png)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <INSERT-HERE>
 - Zebra Version: <INSERT-HERE>
 - Device Type: <INSERT-HERE>
 - Jailbreak Type: <INSERT-HERE>

**Crash Log or System Log**

**Additional context**

There is no upgrade button at top right if there there is any update for new tweak.

Thank you

**Comment by eve0415** [comment] 2020-09-12 08:27
Duplicate of #1535

**Closed** 2020-09-12 14:06 UTC
Labels: bug
