### ISSUE TITLE
Zebra keeps telling me to update two packages although they are on their latest versions.

### ISSUE THREAD

**Issue by m00zis** [wstyres/Zebra#1327] opened 2020-05-28 09:24 UTC
**Describe the bug**
Zebra keeps telling me that I need to update „diskdev-cmds“ and „system-cmds“ but they already are on their latest versions. See the screenshot below.

**To Reproduce**

**Expected behavior**
That Zebra stops asking me to update :D

**Screenshots**
![F805D2EC-9974-4CEF-AE25-FABDAEFBC5FC](https://user-images.githubusercontent.com/32884148/83123695-864ea280-a0d5-11ea-9c85-b1d61132afb9.png)

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <13.5>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <1.2\~beta1>
 - Device Type [e.g. iPhone or iPad]: <iPhone>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <unc0ver>

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**
I don‘t know if my device type and jailbreak is seen in the above section although I edited it. It is an iPhone XS with unc0ver.

**Comment by absidue** [comment] 2020-05-28 09:41
Duplicate of #1310

**Closed** 2020-05-30 04:17 UTC
Labels: bug
