### ISSUE TITLE
Verified clipboard url issue

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#1016] opened 2020-04-01 15:55 UTC
**Describe the bug**
The popup is still displayed when it is not a source url. #591 

https://github.com/wstyres/Zebra/issues/591#issuecomment-604562142

**Screenshots**
![0F69ACF5-EBBA-451A-897B-7540BF3C44F9](https://user-images.githubusercontent.com/40632436/78158672-838c5400-747c-11ea-9202-1765e30c20dd.png)

**Comment by PoomSmart** [comment] 2020-04-04 11:17
Zebra should do the source verification in background for this issue to be eliminated.

**Comment by wstyres** [comment] 2020-04-11 03:47
Was fixed by #1057. Seemed that the problem was that some sites could report 200 codes for URLs that didn't exist, possibly by design. @absidue's PR checks for a valid MIMEType when verifying repos.

**Comment by worldlydev** [comment] 2020-04-13 22:29
Can confirm that this is fixed

**Closed** 2020-04-14 00:26 UTC
Labels: bug, low, scheduled, sources
