### ISSUE TITLE
Package depictions refuse to display correctly and fully

### ISSUE THREAD

**Issue by TheRealKeto** [wstyres/Zebra#660] opened 2019-12-07 18:27 UTC
**Description**
When opening a package to look at its depiction, the depiction will not load entirely. This excludes the user from being able to see the entire depiction. This bug is most noticable on packages hosted on BigBoss and Packix. 

**How to reproduce**
*There isn't a method to really reproduce this, as it randomly happens.* 

Simply have BigBoss and/or Packix as one of your repos, then enter a package and try to scroll down to view the depiction. If lucky, you'll see that the depiction doesn't show fully. You can find a visual of what I'm taking about [here](https://streamable.com/se0yb). 

*Note: No, this issue isn't caused by a connection error, as even with LTE, the depictions do not display correctly. I have confirmed that Packix and BigBoss depictions display correctly on other devices, so it can't be on their side either.*

**Expected behavior**
Depictions should be able to load and be displayed correctly when viewing a package. In the video provided above, the depictions load, but are not displayed correctly at some point while scrolling down. (However, some were displayed correctly, making this issue entirely random)

**Device Information:**
iOS Version: 12.4 
Zebra Version: 1.0~beta30
Device Type: iPhone 8
Jailbreak Type: unc0ver v3.7.0b4

**Comment by wstyres** [comment] 2019-12-07 18:39
Duplicate of #642

**Closed by wstyres** 2019-12-07 18:39 UTC
Labels: bug
