### ISSUE TITLE
There isn’t any upgrade button on the Packages page

### ISSUE THREAD

**Issue by AndreiWasFound** [wstyres/Zebra#1551] opened 2020-09-14 15:22 UTC
**Describe the bug**
There isn’t any upgrade button on the Packages page

**To Reproduce**
I can’t get to reproduce it, it is constant

**Expected behavior**
There isn’t any upgrade button on the Packages page

**Screenshots**
![5779636E-0DD1-43BD-A2EF-19980DEF60E5](https://user-images.githubusercontent.com/54415861/93104477-90150980-f6b6-11ea-913c-4d3b7ab94765.png)

**Device Information:** 
 - iOS Version: 13.5
 - Zebra Version: 1.2~beta4c
 - Device Type: iPhone XS Max
 - Jailbreak Type: unc0ver

**Crash Log or System Log**
There aren’t any crash logs i can provide

**Additional context**
I don’t have any additional context to give, it just first work

**Comment by eve0415** [comment] 2020-09-14 15:31
Duplicate of #1535

**Closed** 2020-09-14 15:33 UTC
Labels: bug
