### ISSUE TITLE
Changes say all packages are installed

### ISSUE THREAD

**Issue by Greigh** [wstyres/Zebra#1005] opened 2020-03-30 02:40 UTC
XS Max, u0 4.3.1, 13.3, Zebra 1.1 beta 3-1

I just got into the app and reloaded sources. 

https://media.discordapp.net/attachments/572784833714192395/694012992903315466/image0.png

**Comment by absidue** [comment] 2020-03-30 10:02
I think this is related to #996

**Comment by wstyres** [comment] 2020-03-30 13:46
Probably not, this is likely a UI issue.

**Comment by wstyres** [comment] 2020-03-31 17:38
@Greigh If you're still experiencing this issue could you upload your Zebra database file? It is located in `/var/mobile/Library/Application Support/xyz.willy.Zebra`

**Comment by Greigh** [comment] 2020-04-11 01:00
Sorry. I couldn’t reproduce it until now. Not sure how I did it though. https://mega.nz/file/dLIkyKAD#SbO6nrJdQVJ8TsGTSAwu7DA8q-SObwo92HQ-lkak9zs

![A19C30FF-6B73-4A1E-B136-186515A6B5B6](https://user-images.githubusercontent.com/57759540/79031676-56bbf900-7b6e-11ea-9532-09320727e693.png)

**Comment by wstyres** [comment] 2020-04-11 01:21
Very odd, and this only occurs occasionally? If you quit the app does the problem go away?

**Comment by Greigh** [comment] 2020-04-11 01:30
Yes it only occurs very occasionally. And it goes away if you completely close the app but doesn’t go away if you leave it run in the background.

**Comment by aabosh** [comment] 2020-04-11 02:33
Hey there, I think I may know the reason for this... but I'm not 100% certain. I pushed a fix in #1005 and it'll be available in the next beta. See if you can reproduce it once that update is available and let us know. Thanks!

**Comment by worldlydev** [comment] 2020-04-13 22:27
Experienced this in the last beta and haven't in the latest one. Can't confirm that it's fixed since it happens at random but looking good so far.

Last beta:
![7C89FF4B-8A2B-4BED-8793-46A6618C65A0](https://user-images.githubusercontent.com/51668635/79167003-b15f8a00-7de6-11ea-98e9-45f974174216.png)

**Comment by wstyres** [comment] 2020-04-14 00:27
I'll leave the issue open for a few more days in case the issue pops up again

**Comment by eve0415** [comment] 2020-04-16 12:16
Still can reproduce as of the beta 5-1. And yes it is UI bug and I’ll post a video later on discord or imgur. I think I found out the steps to reproduce this.
![7280DD95-AD96-4705-A9F3-2B34C8A276D5](https://user-images.githubusercontent.com/40632436/79455171-697b7580-8027-11ea-9bc6-0a80177c6669.png)

**Comment by eve0415** [comment] 2020-04-16 12:29
@wstyres Found out as I said above. [Video](https://discordapp.com/channels/566255609251364864/572784833714192395/700320407827382372)

Steps to definitely reproduce
1. Add a repo. In this video, I just selected one from community source but I think it's ok by adding it manually via url (haven't test)
2. In console, cancel the operation.
3. Open source tab (I don't know if it should be source tab), and swipe to start refresh.
4. While refreshing, open changes tab (Again, don't know if it should be open), and then open package tab until the refreshing are finished.
5. When refreshing sources are done, open changes tab.
6. You'll see all the package are marked as installed.

**Comment by eve0415** [comment] 2020-04-16 12:44
I don’t know why but UI is wrong in the package depiction page.
![CD981DF1-ADAD-4BD1-839E-C2128FC96EAA](https://user-images.githubusercontent.com/40632436/79457399-21f6e880-802b-11ea-9fd6-aa76c21becef.png)
![5F41F000-155F-4E70-93B5-305AF5E363CD](https://user-images.githubusercontent.com/40632436/79457410-26bb9c80-802b-11ea-8c01-774bafc0cd7e.png)

**Comment by wstyres** [comment] 2020-04-24 21:47
Was able to reproduce, I think I fixed the issue in 85c9973955817ee970356f0e4b649bad5ed8a133. Will require testing when the new beta is out.

**Comment by wstyres** [comment] 2020-04-26 15:45
@eve0415 See if you can reproduce, if not I'll close the issue

**Comment by eve0415** [comment] 2020-04-26 22:35
Cannot reproduce this issue as of beta 7.

This is related, doing the steps above and opening package depiction page, it seems to be missing source information;
![A34B9520-4982-47C1-A65E-408FB09A2F00](https://user-images.githubusercontent.com/40632436/80321647-a599ac00-8859-11ea-9b0a-fdecf2715ae4.jpeg)

**Closed** 2020-04-27 23:34 UTC
Labels: bug, changes, low, scheduled
