### ISSUE TITLE
New options to Zebra

### ISSUE THREAD

**Issue by retrust** [wstyres/Zebra#1510] opened 2020-08-24 19:23 UTC
1- Option to easy copy tweaks bundle.
2- Show dependencies tweak list.
3- Show conflicts tweak list.

**Comment by wstyres** [comment] 2020-08-25 19:08
Suggestion 1 is a duplicate of #1343 and suggestions 2 and 3 are duplicates of https://github.com/wstyres/Zebra/issues/625

**Closed by wstyres** 2020-08-25 19:08 UTC
Labels: suggestion
