### ISSUE TITLE
[BUG] Dependency problem when removing package

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#700] opened 2019-12-17 23:10 UTC
**Describe the bug**
I have “iCleaner” which I believe it depends on any “apt transitional”.
I have “APT 0.7 Transitional” & “APT 1.4 Transitional”. When I try to remove APT 0.7 Transitional which I don’t need, Zebra queue iCleaner to remove too.

**To Reproduce**
Try to remove APT 0.7 Transitional while you have APT 1.4 Transitional.
(I believe iCleaner never install dependency because Cydia Installer depends on APT 1.4 Transitional as well.)

**Expected behavior**
Zebra tries to find other dependencies that is already installed.

**Screenshots**
Queuing APT 0.7 Transitional to remove.
![8A10A741-7BE9-4ED9-B63F-54E87805020D](https://user-images.githubusercontent.com/40632436/71041836-6a7dc280-216d-11ea-8b61-00a414984176.png)

Queuing APT 1.4 Transitional to remove, APT 0.7 Transitional are getting remove as well, that will make iCleaner to be remove because it depends on Transitional.
![90B56BB2-8CD0-4C7F-ABA1-73A64EB02685](https://user-images.githubusercontent.com/40632436/71041904-9dc05180-216d-11ea-877f-7a271c9402cb.png)

When removing only APT 0.7 Transitional. DPKG or APT are not removing iCleaner automatically and it works without that.
![DC58282B-D02B-495E-A860-95F9EBECED16](https://user-images.githubusercontent.com/40632436/71041955-c8aaa580-216d-11ea-8a8e-ad51883493b6.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta up to rc1
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Comment by wstyres** [comment] 2019-12-17 23:24
So the problem is that Zebra is erroneously showing the removal of iCleaner Pro when removing APT 0.7? That is what is happening from what I understand.

**Comment by eve0415** [comment] 2019-12-17 23:26
Yes I think so

**Comment by eve0415** [comment] 2019-12-17 23:31
Because there is no removal of iCleaner when using Cydia
![05DC32AD-B6DD-4B80-AFFA-11236D56CB9F](https://user-images.githubusercontent.com/40632436/71043032-bda54480-2170-11ea-8ade-7821f6827f1c.png)

**Comment by wstyres** [comment] 2019-12-18 03:22
Can you send a dpkg status log for this?

**Comment by wstyres** [comment] 2019-12-18 04:03
Should be fixed as of d78cf403727aead06ff45f74a3ecb76ce7fd1dbe.

**Comment by wstyres** [comment] 2019-12-19 05:02
Found some more problems but they're resolved as of 3168bbe24524c450907a819293b91efbbf562cf9.

**Comment by eve0415** [comment] 2019-12-22 23:10
Same problem for FilzaPlus.
![1A07FEC1-15BB-4390-952B-66FC8040C266](https://user-images.githubusercontent.com/40632436/71328517-b9579d80-255b-11ea-854f-5352f64ccaad.png)
![86733D38-B552-495F-A6F0-3A81A944FF9A](https://user-images.githubusercontent.com/40632436/71328520-bbb9f780-255b-11ea-92e2-2c0f10b02dce.png)

**Comment by wstyres** [comment] 2019-12-26 20:32
The new issue should be fixed as of be94918e7dc0966610ec027182ff3c1f486fd38f.

**Comment by wstyres** [comment] 2019-12-26 20:32
![Simulator Screen Shot - iPhone 11 Pro - 2019-12-26 at 15 32 35](https://user-images.githubusercontent.com/19736790/71489716-f2f70580-27f4-11ea-8892-4cc83648b462.png)

**Closed** 2019-12-29 03:08 UTC
Labels: bug, dependency, scheduled
