### ISSUE TITLE
When pressed on open documents directory it freezes  

### ISSUE THREAD

**Issue by motoissa** [wstyres/Zebra#1028] opened 2020-04-02 02:24 UTC
**Describe the bug**
If u press on open documents directory it will freeze and I’ll have to force close it then reopen it 

**To Reproduce**
Open the zebra settings and go all the way done and press on open documents directory 
**Expected behavior**
Something to open 
**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment] 2020-04-02 03:42
Duplicate of #1015

**Closed by wstyres** 2020-04-02 03:42 UTC
Labels: bug
