### ISSUE TITLE
3D Touch to install packages crashes app

### ISSUE THREAD

**Issue by vignesh2k** [wstyres/Zebra#359] opened 2019-09-10 14:40 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

**Additional context**

**Comment by wstyres** [comment] 2019-09-10 18:50
Duplicate of #358

**Closed by wstyres** 2019-09-10 18:50 UTC
Labels: bug
