### ISSUE TITLE
Page change doesn’t appear 

### ISSUE THREAD

**Issue by hcm77** [wstyres/Zebra#1076] opened 2020-04-13 21:37 UTC
The new zebra update broken the page of change ( see the photo attached) thanks 
![BF730372-6CAD-4B56-A817-FC70572F05D4](https://user-images.githubusercontent.com/63616738/79163606-15368280-7de8-11ea-9806-d871d71d9a1d.jpeg)

**Comment by mwoolweaver** [comment] 2020-04-13 21:39
duplicate of #1072

**Closed** 2020-04-14 00:22 UTC
Labels: bug
