### ISSUE TITLE
The live search is not working

### ISSUE THREAD

**Issue by Digok** [wstyres/Zebra#1345] opened 2020-05-30 05:11 UTC
**Describe the bug**
The results of the search only appears when I hit to search
**To Reproduce**

**Expected behavior**
Show the tweaks before hit to search

**Screenshots**
If applicable, add screenshots to help explain your problem.![image](https://user-images.githubusercontent.com/64342954/83320112-a5a31800-a21a-11ea-8beb-2319a9f45b3e.png)

**Device Information (please complete the following information):**![image](https://user-images.githubusercontent.com/64342954/83320124-bf445f80-a21a-11ea-96b8-9bdc7932d54a.png)

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <INSERT-HERE>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <INSERT-HERE>
 - Device Type [e.g. iPhone or iPad]: <INSERT-HERE>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <unc0ver>

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**
I checked the settings and it was enabled

**Comment by PoomSmart** [comment] 2020-05-30 05:18
Duplicate of #1313

**Closed by PoomSmart** 2020-05-30 05:18 UTC
