### ISSUE TITLE
[UI BUG] The depiction is cut off

### ISSUE THREAD

**Issue by baobaoit** [wstyres/Zebra#650] opened 2019-12-04 00:40 UTC
**Describe the bug**

The depiction of Marina tweak is cut off on the latest version of Zebra 

**To Reproduce**

1. Search the Marina tweak (BigBoss source)
2. Tap on it to view the depiction 

**Expected behavior**

Display the depiction normally 

**Screenshots**

On Zebra 
![A7787855-E69E-4A29-8AED-768E094084C3](https://user-images.githubusercontent.com/31947091/70101839-d25de480-1668-11ea-8050-5afde8497113.png)

On Cydia
![8E11ABE1-CBCE-4AC9-A03B-D35C872D60D8](https://user-images.githubusercontent.com/31947091/70101901-0afdbe00-1669-11ea-83cb-23f2d00b3b45.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta30-4
 - Device Type [e.g. iPhone or iPad]: iPhone 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

N/A

**Additional context**

N/A

**Comment by wstyres** [comment] 2019-12-04 00:51
Duplicate of #642

**Closed by wstyres** 2019-12-04 00:51 UTC
Labels: bug
