### ISSUE TITLE
Can't check tweak depictions after queuing any tweak in Changes tab

### ISSUE THREAD

**Issue by mainhathao** [wstyres/Zebra#704] opened 2019-12-18 01:20 UTC
After queuing any tweaks in Changes tab, I can't tap on other tweaks to see their depictions. I can still navigate through the tabs and check for depictions in Packages, but not for only Changes. 

**To Reproduce**
It happens every time.

**Expected behavior**
I expected to see the tweak depiction but it just doesn't do anything when I tap on the tweaks.

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0~rc1
 - Device Type [e.g. iPhone or iPad]: iPhone Xs Max
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

Video demonstrating the issue:
https://cdn.discordapp.com/attachments/566255609251364867/656664587256594435/video0.mp4

**Comment by wstyres** [comment] 2019-12-18 02:02
Should be fixed in 329c772c7c21596cd8b3608f61cbf949da5adb49. I'm able to view depictions in the changes tab but sometimes it takes two taps on the cell to bring it up. Let me know if this occurs in the next RC because this could just be a simulator issue.

**Comment by eve0415** [comment] 2019-12-19 23:33
I can not open depictions right after I queued the package but after 1 or 2 seconds I can

**Comment by eve0415** [comment] 2019-12-19 23:35
No, I have to press two times to open. The times are not related

**Comment by wstyres** [comment] 2019-12-20 01:46
That’s what I was experiencing too. I’ll see if I can do anything else to fix it.

**Comment by Sa1Beer777** [comment] 2019-12-20 02:02
> Should be fixed in [329c772](https://github.com/wstyres/Zebra/commit/329c772c7c21596cd8b3608f61cbf949da5adb49). I'm able to view depictions in the changes tab but sometimes it takes two taps on the cell to bring it up. Let me know if this occurs in the next RC because this could just be a simulator issue.

**Comment by PoomSmart** [comment] 2020-04-04 06:21
I myself could not reproduce this issue anymore.

**Comment by eve0415** [comment] 2020-04-04 06:28
Me too

**Comment by wstyres** [comment] 2020-04-05 14:24
I can't reproduce anymore either as of beta4, closing the issue.

**Closed by wstyres** 2020-04-05 14:24 UTC
Labels: bug, changes, outdated, question
