### ISSUE TITLE
Swipe for More. From the Seach Bar 

### ISSUE THREAD

**Issue by kelvin1300** [wstyres/Zebra#990] opened 2020-03-27 02:18 UTC
![C9A39DEC-A223-4341-B811-01A546A4D0EA](https://user-images.githubusercontent.com/55414105/77714452-6b659200-6faf-11ea-9ef5-0fee04ac4881.png)

Can you please make swipe the tweak back in the search bar. I don’t like that option that I had to do 3D Touch

**Comment by eve0415** [comment] 2020-03-27 02:21
If I read it correctly it's duplicate of #955

**Closed** 2020-03-27 02:40 UTC
Labels: bug
