### ISSUE TITLE
Zebra does not work on the latest version.  It hangs on the home screen

### ISSUE THREAD

**Issue by Geniberto** [wstyres/Zebra#1211] opened 2020-05-09 01:32 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <INSERT-HERE>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <INSERT-HERE>
 - Device Type [e.g. iPhone or iPad]: <INSERT-HERE>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <INSERT-HERE>

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by absidue** [comment] 2020-05-09 02:45
Can you please edit your comment and fill in all the information. With the limited you have provided bug can't be reproduced, making it impossible to fix it.

**Comment by CaiMiao** [comment] 2020-05-10 04:54
Same problem
iOS Version [e.g. 12.1.2 or 10.3.3]:13.2.2
Zebra Version [e.g. 1.0~beta1 or beta1]:1.1
Device Type [e.g. iPhone or iPad]:ipad mini5 (a12)
Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]:uncover

**Comment by eve0415** [comment] 2020-05-10 06:42
Can you post video recording? @CaiMiao 
I’m not sure but it might be the problem with loading featured package.

**Comment by wstyres** [comment] 2020-05-10 15:43
A list of sources you have installed is also needed to help debug this, we can't reproduce the issue and would like to be able to replicate the environment you're using Zebra in.

**Comment by wstyres** [comment] 2020-05-10 15:44
Also, featured package setting like whether or not random selection for them is turned on.

**Comment by Geniberto** [comment] 2020-05-11 01:21
iPhone 7plus
iOS 13.4.1
Jailbreak via checkra1n no windows pendrive bootable 
Zebra 1.1 

Enviado do meu iPhone

> Em 10 de mai de 2020, à(s) 01:54, Fumii Chuu <notifications@github.com> escreveu:
> 
> Same problem
> iOS Version [e.g. 12.1.2 or 10.3.3]:13.2.2
> Zebra Version [e.g. 1.0~beta1 or beta1]:1.1
> Device Type [e.g. iPhone or iPad]:ipad mini5 (a12)
> Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]:uncover

**Comment by Geniberto** [comment] 2020-05-12 02:44
O vídeo ficou com mais De 16 megas
Existe outra forma de eu enviar o vídeo ?

Enviado do meu iPhone

Em 11 de mai de 2020, à(s) 23:22, Geniberto Silva <gabrielfaeng@hotmail.com> escreveu:

recording? @CaiMiao<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCaiMiao&data=02%7C01%7C%7C779ba959ec2c49125d6708d7f4ad60e6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637246897794956591&sdata=lDamzbpYUJ%2B0vPAjQloNyUddQC3Kgg8vLGWO5IS1TIQ%3D&reserved=0>
I’m not sure but it might be the problem with loading featured package.

**Comment by absidue** [comment] 2020-05-12 05:34
Machine translation:

>>> The video was over 16 megs 
Is there another way for me to send the video?

**Comment by wstyres** [comment] 2020-05-13 21:41
If anyone still experiencing this issue can zip up the folder at `/var/mobile/Library/Application Support/xyz.willy.zebra` and send it in a link that would help out a lot.

**Comment by wstyres** [comment] 2020-05-14 20:04
Might be fixed as of b492791. Please check if the issue still occurs in 1.1.4 when it is released.

**Comment by Geniberto** [comment] 2020-05-15 11:13
Now yes.  Thank you very much for your attention.
Very very good.

Enviado do meu iPhone

Em 14 de mai de 2020, à(s) 17:04, Wilson Styres <notifications@github.com> escreveu:

﻿

Might be fixed as of b492791<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwstyres%2FZebra%2Fcommit%2Fb492791adddc56b5c0f678a21ea16251e9b6776d&data=02%7C01%7C%7Cf70a5282f8c34dc5019208d7f84202ab%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637250834698077550&sdata=SFKMI5UlpRtc%2FqkHWiY5n0eZPfs5ITFViWVF7c%2FN0II%3D&reserved=0>. Please check if the issue still occurs in 1.1.4 when it is released.

**Comment by PoomSmart** [comment] 2020-05-17 14:44
Closed since it’s fixed.

**Closed by PoomSmart** 2020-05-17 14:44 UTC
Labels: bug, scheduled

**Comment by Geniberto** [comment] 2020-05-17 14:52
Now yes.  Thank you very much for your attention.

forgive the delay in responding

Enviado do meu iPhone

Em 17 de mai de 2020, à(s) 11:44, Thatchapon Unprasert <notifications@github.com> escreveu:

﻿

Closed #1211<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwstyres%2FZebra%2Fissues%2F1211&data=02%7C01%7C%7C1118d10db90b40d5cead08d7fa70d13e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637253234753250991&sdata=1AMzJMPnWoKX9whe86oRTmNvVPiHDryXTE0%2FirCfEuk%3D&reserved=0>.
