### ISSUE TITLE
[BUG] tweak depictions don't fully load if you scroll down before they fully finish loading

### ISSUE THREAD

**Issue by allendude51** [wstyres/Zebra#659] opened 2019-12-05 22:25 UTC
If I open a page for a tweak and start scrolling down before the orange bar at the top finishes, then I can't view the bottom half of tweak depictions. It only loads fully if I wait for it to finish before I start scrolling
![24D9C18F-B60C-47A4-8521-30672D99095C](https://user-images.githubusercontent.com/51012842/70279312-d2023e00-177b-11ea-8d40-71739a0384b1.png)

**Comment by wstyres** [comment] 2019-12-05 22:26
Duplicate of #642

**Closed by wstyres** 2019-12-05 22:26 UTC
Labels: bug
