### ISSUE TITLE
4 Tweak updates are not showing in zebra

### ISSUE THREAD

**Issue by AAgamesnl** [wstyres/Zebra#771] opened 2020-01-02 12:48 UTC
**Describe the bug**
zebra doesn’t show me all the updates of certain repos. While cydia does

**To Reproduce**
/

**Expected behavior**
i expected a working package manager that can look for updates 

**Screenshots**
![799DC16F-72AF-4F49-9EFF-34BC19F75B1B](https://user-images.githubusercontent.com/19744374/71667641-42de4b00-2d66-11ea-9ccb-4e08d47f70fe.png)
![DF99EACA-3B30-4739-A4D5-0B00D04B029B](https://user-images.githubusercontent.com/19744374/71667642-4376e180-2d66-11ea-9d39-436a62379ad9.png)

**Device Information (please complete the following information):**
 - iOS Version : 13.2.2
 - Zebra Version : 1.0 
 - Device Type : iPhone X
 - Jailbreak Type : checkra1n

**Crash Log or System Log**
/

**Additional context**
i tried refreshing my repos on zebra 7x

**Comment by AAgamesnl** [comment] 2020-01-02 12:49
Twitter: @Ayoub_elyaakoub

**Comment by absidue** [comment] 2020-01-02 13:16
Have you transferred all your sources from Cydia? If not, here's how:

Zebra => Thuis => Community Bronnen => Overdracht bronnen van Cydia naar Zebra

**Comment by AAgamesnl** [comment] 2020-01-02 13:18
thank u, but I already did that from the beginning.

**Comment by absidue** [comment] 2020-01-02 13:22
Try "Tabellen verwijderen" in Zebra's settings. That will reset all of Zebra's data, it won't affect any of your settings, tweaks or repos.

**Comment by AAgamesnl** [comment] 2020-01-02 13:23
oke will try that.

**Comment by AAgamesnl** [comment] 2020-01-02 13:27
it's still not showing up. I am using Watusi 2 for WhatsApp as a fail check.

**Comment by absidue** [comment] 2020-01-02 13:32
Which version of Watusi are you on?

**Comment by AAgamesnl** [comment] 2020-01-02 13:35
1.2.22 - version 1.2.25 is available. I am using the original repo: https://apt.fouadraheb.com

**Comment by absidue** [comment] 2020-01-02 13:36
For me their repo is empty so it is probably a problem at their end

**Comment by AAgamesnl** [comment] 2020-01-02 13:37
can you ping it?

**Comment by AAgamesnl** [comment] 2020-01-02 13:39
but the repo is up, I can ping. I just downgraded watusi ?

**Comment by AAgamesnl** [comment] 2020-01-02 13:40
but remember, watusi was not the only tweak that was not showing

**Comment by absidue** [comment] 2020-01-02 13:42
I managed to download Watusi version  from BigBoss but not from Fouad's Repo

**Comment by AAgamesnl** [comment] 2020-01-02 13:43
could you try and downgrade watusi and see if the update shows up in zebra?

**Comment by absidue** [comment] 2020-01-02 13:50
After dropping the tables in Zebra's settings Fouad's repo is no longer empty

After downgrading to the version you have it shows the update on my end

**Comment by AAgamesnl** [comment] 2020-01-02 13:52
weird

**Comment by absidue** [comment] 2020-01-02 14:07
Try running the following commands and then wait about 10 seconds before dropping the tables on Zebra again:

1. `su`
    1. Enter your root password (default: alpine)
2. `/usr/libexec/zebra/startup`

That will regenerate Zebra's virtual dependencies

**Comment by AAgamesnl** [comment] 2020-01-02 14:12
I still don't see any updates. sorry and thanks for helping me out here btw. my other 2 friends have the same problem with other tweaks btw

**Comment by absidue** [comment] 2020-01-02 14:14
Sorry I couldn't help you fix it easily 😢

**Comment by AAgamesnl** [comment] 2020-01-02 14:15
no. thanks for trying to fix this problem for me ;)

**Comment by absidue** [comment] 2020-01-02 14:16
You're welcome

**Comment by eve0415** [comment] 2020-01-02 14:36
Maybe it is something to do with duplicate package on different repos
Does Zebra reloaded the packages from repo? Search for any of the package you are missing to update and find the version

**Comment by wstyres** [comment] 2020-01-02 15:48
Could you send a dpkg status file? It is located at `/var/lib/dpkg/status` and you can upload it to a site like https://ghostbin.co/ and then share a link here. It would also be helpful for you to export a sources.list from Zebra (press edit -> share in Zebra's sources tab) and upload that to ghostbin as well.

**Comment by AAgamesnl** [comment] 2020-01-02 16:08
here is my "Status" https://ghostbin.co/paste/ajqy9

and here is my repo list https://ghostbin.co/paste/qrnk2

**Comment by wstyres** [comment] 2020-01-02 16:21
Could you tell me what version of WatusiTools Cydia is trying to upgrade too? I see you have 2.1.11 installed and that is the latest version from Fouad's repo. 

As for the other packages, I'm able to see 3 upgrades for Watusi 2, Barmoji, and Safari Plus. The other packages (CallBar XS and SimpleActivationActions) are appearing due to a Cydia bug that shows an upgrade when two of the same version of a package are provided by two different repos (in this case, BigBoss and Limneo's repo) this is a Cydia bug and there is no real "Upgrade" available and Zebra is working as intended. 

![Simulator Screen Shot - iPhone 11 Pro - 2020-01-02 at 11 19 42](https://user-images.githubusercontent.com/19736790/71677840-c8a3cb80-2d51-11ea-8e13-f79df7e63b0a.png)

I suspect the Watusi 2 upgrade not showing in your Zebra is the actual bug here but I am not sure why it is occurring. You said that you tried the "Drop Tables" option in settings?

**Comment by absidue** [comment] 2020-01-02 16:28
Yes we tried dropping the tables.

Sorry I used the translation files to translate the options to AAgamesnl's language, to simplify it on there end

**Comment by AAgamesnl** [comment] 2020-01-02 17:15
There should not be a safari plus update...

**Comment by wstyres** [comment] 2020-01-02 17:18
SafariPlus showed in your Cydia screenshot you’re saying it shouldn’t show up in Zebra?

**Comment by AAgamesnl** [comment] 2020-01-02 17:18
Yes but I upgraded via cydia.. what version is that?

**Comment by AAgamesnl** [comment] 2020-01-02 17:19
Oh never mind. the update just dropped

**Comment by wstyres** [comment] 2020-01-02 17:26
SafariPlus showed in your Cydia screenshot you’re saying it shouldn’t show up in Zebra?

**Closed** 2020-01-05 01:05 UTC
Labels: bug, outdated, packages, question
