### ISSUE TITLE
Zebra fail to match bootstrap dependency for upgrade

### ISSUE THREAD

**Issue by xi7i6** [wstyres/Zebra#938] opened 2020-03-07 05:00 UTC
**Describe the bug**
I have the veriosn 2.1.3 of Translomatic installed  when i want to upgrade it to version 2.1.4 it required an old version of RocketBootstrap (1.0.6)while i already have the latest version of it installed (1.0.7beta3) , it is fine with other package managers

**To Reproduce**
Steps to reproduce the behavior: install/ upgrade Translomatic via Zebra

**Expected behavior**
Install/upgrade correctly without any conflict 

**Screenshots**
![3E6C15FB-0A67-449B-9526-ADF5856D5A92](https://user-images.githubusercontent.com/55637002/76137053-98c2be00-6049-11ea-90b7-be9b41d416d4.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: latest beta
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Unc0ver

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment] 2020-03-07 13:12
This isn’t a bug, it is an intentional design of Debian. See here: https://www.debian.org/doc/debian-policy/ch-relationships.html

![image](https://user-images.githubusercontent.com/19736790/76144118-23f08380-604b-11ea-9b37-6c01ae9486b5.jpeg)

Mainly you’re setting `>` as the dependency but it should really be `>>`

I am able to add an exception but I’d rather not, the quicker solution would be for you to fix your dependency line.

**Comment by wstyres** [comment] 2020-03-07 17:57
Closing as it is not a bug. Contact the developer of the package to fix this.

**Closed by wstyres** 2020-03-07 17:57 UTC
Labels: bug
