### ISSUE TITLE
Tweak has been uninstalled (checked cydia and sileo) but still said installed on zebra. Tweak: (Animpods 2)

### ISSUE THREAD

**Issue by CogCreationsLab** [wstyres/Zebra#1459] opened 2020-07-12 05:24 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <INSERT-HERE>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <INSERT-HERE>
 - Device Type [e.g. iPhone or iPad]: <INSERT-HERE>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <INSERT-HERE>

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by PoomSmart** [comment] 2020-07-12 06:51
What if you refresh the sources?

**Comment by CogCreationsLab** [comment] 2020-07-12 07:10
Ive tried. Its still there. Its on the packix repo

**Comment by PoomSmart** [comment] 2020-07-12 07:49
As well as going to Settings > Reset then Clear Sources Cache?

**Comment by CogCreationsLab** [comment] 2020-07-12 07:52
Just tried, its still there. I also checked ‘mobilesubstrate’ tweak wasn't
there either. Makes me wonder if its installed or not installed

**Comment by CogCreationsLab** [comment] 2020-07-12 21:25
Have you found the problem?

Also is this red line supposed to show?

**Comment by wstyres** [comment] 2020-08-06 18:33
Any images you attached in your email do not show up on the website. You must log in to GitHub in order to upload images.

By "on the packix repo" do you mean installed or just visible? We need some more information to be able to reproduce the bug.

**Comment by CogCreationsLab** [comment] 2020-08-06 18:50
The tweak was installed from the packix repo. The tweak has been
uninstalled multiple times but still shows on Zebra. I’ve checked other
installers (cydia, Sileo) and the package didn’t exist. The tweak is
“Animpods 2”. I’m not sure if the package may be offline or cause by
another issue. As the tweak does not work properly and is having a hard
time installing.

**Comment by wstyres** [comment] 2020-08-06 18:51
Could you take a screen recording and upload it to a site like imgur.com so that I can better understand the problem you are experiencing?

**Comment by CogCreationsLab** [comment] 2020-08-06 19:06
https://imgur.com/a/Pypzxnb

**Comment by wstyres** [comment] 2020-08-06 19:07
Could you upload the file located at `/var/lib/dpkg/status` to ghostbin.com and paste a link here?

**Comment by CogCreationsLab** [comment] 2020-08-06 19:07
Reinstalling then cause this issue
https://imgur.com/a/q8e2J5z

**Comment by CogCreationsLab** [comment] 2020-08-06 19:10
How do I upload to ghostbin? Link seems to be invalid or something

**Comment by wstyres** [comment] 2020-08-06 19:11
Sorry, the link is https://ghostbin.co/

**Comment by CogCreationsLab** [comment] 2020-08-06 19:14
https://ghostbin.co/paste/pcpy4

**Comment by wstyres** [comment] 2020-08-06 19:17
Ok, it looks like there was an error processing the package when trying to install (which is what is shown in the screenshot you sent) so it was never fully installed (which is why you can't uninstall it). You're correct in that Zebra should not show this package so I'll fix that bug now.

Try running `sudo apt-get remove --purge com.lkarkaletsis.animpodsnew` in order to remove the files.

**Comment by CogCreationsLab** [comment] 2020-08-06 19:20
Cmd is for terminal su right? sudo doesn’t seems to work there

**Comment by wstyres** [comment] 2020-08-06 19:21
Yes, sudo just indicates you should run the command as the root user in this case.

**Comment by CogCreationsLab** [comment] 2020-08-06 19:24
Got it. Should try installing the package again? One more question, how do
I check if a package is online or offline before installation?

**Comment by wstyres** [comment] 2020-08-06 19:28
You don't need to install the package again if you do not want it. I've fixed the problem in 73c706c5f09f8e8371ff7a6a639ab6a3b62a60cf so a fix will be in Zebra 1.1.11.

Packages should list their source before installing so that is your indication on where they are from.

**Closed** 2020-08-10 00:00 UTC
Labels: bug, low, packages, scheduled

**Comment by CogCreationsLab** [comment] 2020-08-19 00:27
Hey, sorry to bother you.

Not sure if this is zebra issue or something else but I’m having this error
code every time I installing stuff. Do you happen to know a fix?

or what this is and how to use it?

ln -s /usr/local/lib/libncurses.6.dylib /usr/lib/libncurses.6.dylib
