### ISSUE TITLE
Light mode screwed up

### ISSUE THREAD

**Issue by Aditya245850** [wstyres/Zebra#588] opened 2019-11-17 03:34 UTC
Light mode is really screwed up lmao. It looks broken. Dark mode is okay though.

(https://user-images.githubusercontent.com/55038679/69002629-e56e6780-08a7-11ea-98f2-22239ccd4017.png)

 - iOS Version: 13.2.2
 - Zebra Version: 27-1
 - Device Type: iPhone X(10,3)
 - Jailbreak Type: Checkra1n 0.9.5

**Comment by wstyres** [comment] 2019-11-17 18:46
Are there steps to reproduce this? Light mode by itself is fine. Does this occur on iOS 13 with the system dark mode on?

**Comment by Aditya245850** [comment] 2019-11-17 18:47
It happens after I turn on oled dark mode, and then switch back to light mode.

**Comment by wstyres** [comment] 2019-11-17 19:04
Could you record a video to reproduce this?

**Comment by Aditya245850** [comment] 2019-11-17 19:10
How can I post a video? It only allows me to post screenshots.

**Comment by Aditya245850** [comment] 2019-11-17 19:18
https://imgur.com/gallery/juWbq1p

I got it

**Comment by wstyres** [comment] 2019-11-17 19:20
Is the iOS dark mode on or off?

**Comment by Aditya245850** [comment] 2019-11-17 19:20
Dark mode off.

**Comment by Aditya245850** [comment] 2019-11-17 19:20
Dark mode off.

**Comment by MTACS** [comment] 2019-11-21 02:52
This is caused by iOS 13's overrideUserInterfaceStyle on UIViews. This can be fixed by adding the key `UIUserInterfaceStyle,` with string `Light` to Info.plist, or add it to Zebra's appDelegate method `[[[UIApplication sharedApplication] delegate].window setOverrideUserInterfaceStyle:1];`

**Comment by wstyres** [comment] 2019-11-22 02:36
@MTACS Thanks! I'll add this to Zebra for now and when I implement true light/dark mode switching to respect iOS 13's preferences I can remove it.

**Closed** 2019-11-23 02:14 UTC
Labels: UI, bug, scheduled
