### ISSUE TITLE
Try to open packages inside of Zebra take me to developers website for package instead

### ISSUE THREAD

**Issue by beerad1228** [wstyres/Zebra#921] opened 2020-02-29 16:14 UTC
**Describe the bug**
Whenever I click on a package, to try to install it, it starts to take me to the install page (the same page with the Add To Wishlist button) but before it can finish loading it takes me to the developers website for that package.

**To Reproduce**
Click on any package inside of Zebra and try to go to install page

**Expected behavior**
For the install page to finish loading (the same page with the Add To Wishlist button), so I can install packages

**Screenshots**
![DFCB2290-1B38-40E7-959E-97A14170BEC6](https://user-images.githubusercontent.com/48443188/75611019-8d6d1100-5ae4-11ea-9f98-c6f8c46f3b3e.png)
![66304837-BA21-4E98-939C-C6EFD61ACFC1](https://user-images.githubusercontent.com/48443188/75611020-8fcf6b00-5ae4-11ea-8a8e-f604d082fe38.png)

**Device Information (please complete the following information):**
 - iOS Version 13.3: 
 - Zebra Version 1.1~beta2: 
 - Device Type iPhone X: 
 - Jailbreak Type unc0ver:

**Comment by absidue** [comment] 2020-02-29 16:17
Duplicate of #906

**Closed** 2020-02-29 16:18 UTC
Labels: bug
