### ISSUE TITLE
Support For sileo depictions

### ISSUE THREAD

**Issue by ThinkDifferentunc0ver** [wstyres/Zebra#75] opened 2019-05-13 03:49 UTC
Support sileo depictions because it is fast and much more modern looking.But also leave Java and others enabled.Enabling sileo depictions will lead to a more modern and consistent UI for the users due to transfer from sileo to zebra.Replace place stock home page with sileo featured page and also inject into the page your own links of community repo’s and changelogs can be shown as a pop-up after updates instead of an actual tab/cell.

**Comment by wstyres** [comment] 2019-05-13 04:24
Duplicate of #7

**Closed by wstyres** 2019-05-13 04:24 UTC
Labels: bug

**Comment by ThinkDifferentunc0ver** [comment] 2019-05-13 04:26
Native support 😐 merge pixelomers modern depictions with zebra
