### ISSUE TITLE
Missing upgrade label on package tab when choose upgrade from the swipe action

### ISSUE THREAD

**Issue by baobaoit** [wstyres/Zebra#732] opened 2019-12-22 06:50 UTC
**Describe the bug**
Missing the `upgrade` label when choose `Upgrade` button from the swipe action of the tweak.

**To Reproduce**
1. The tweak has a version upgradable
2. On the `pakage` tab, swipe left on the line of the tweak want to upgrade
3. Tap on the `Upgrade` button

**Expected behavior**
Displays the `upgrade` label like when we tap on the tweak, then tap on the `Modify` button, then tap on the `Upgrade` section.

**Screenshots**
![3982C980-E9E9-493D-B403-BE7DA671AC0A](https://user-images.githubusercontent.com/31947091/71318211-87ddc400-24c0-11ea-8115-0c4e802b1f2c.png)
![E9E85F02-A6D8-400C-82F1-2844CF45B96E](https://user-images.githubusercontent.com/31947091/71318212-89a78780-24c0-11ea-9cbe-7f8f1f05af08.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.2.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0~rc2-1
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment] 2019-12-22 18:00
Duplicate of #722

**Closed by wstyres** 2019-12-22 18:00 UTC
Labels: bug, duplicate
