### ISSUE TITLE
Duplicate Packages in the "Packages" tab.

### ISSUE THREAD

**Issue by NickJustWill** [wstyres/Zebra#1099] opened 2020-04-17 11:08 UTC
**Describe the bug**
See Screenshot
**To Reproduce**
Steps to reproduce the behavior: Not Sure

**Expected behavior**
should only be one of each package
**Screenshots**
![IMG_4084](https://user-images.githubusercontent.com/47925864/79563107-0e3b9880-80a4-11ea-847b-632ba6705da7.png)
**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.2.2
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1 ~beta5-2
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Checkra1n

**Crash Log or System Log**
Application Didn't Crash

**Additional context**
Probably Some issue with the UITableView

**Comment by wstyres** [comment] 2020-04-18 15:45
I'll leave this issue open for a few days to see ice you can get some steps to reproduce. If you can't reproduce then we'll have to close the issue.

**Comment by wstyres** [comment] 2020-04-25 02:44
Closing due to inactivity.

**Closed by wstyres** 2020-04-25 02:44 UTC
Labels: bug, packages, question
