### ISSUE TITLE
Notification bubble

### ISSUE THREAD

**Issue by Yolokung** [wstyres/Zebra#150] opened 2019-06-03 09:23 UTC
**Describe the bug**
There are 8 notification bubbles on the app and on the homescreen and they don’t go away.

**To Reproduce**
I just updated Zebra and that’s it.

**Expected behavior**
No notification bubble

**Screenshots**
Until I get hands on my computer

**Device Information (please complete the following information):**
 - iOS Version : 11.3.1 
 - Zebra Version : beta13
 - Device Type : iPhone 5S

**Comment by PoomSmart** [comment] 2019-06-03 10:23
Duplicate of #149

**Closed by PoomSmart** 2019-06-03 10:23 UTC
Labels: bug
