### ISSUE TITLE
Get zebra to detect errors

### ISSUE THREAD

**Issue by F0lkl0re** [wstyres/Zebra#1530] opened 2020-09-08 12:59 UTC
Zebra cant detect half-installed packages and dpkg errors, which usually happens when zebra or ur phone dies during package install. Cydia and Sileo can detect and fix but zebra cant. This is something you should implement if people use zebra as their main package manager.

**Comment by eve0415** [comment] 2020-09-08 14:30
Duplicate of #985

**Closed** 2020-09-08 18:55 UTC
Labels: suggestion
