### ISSUE TITLE
Swiping from reinstall to upgrade doesn't work

### ISSUE THREAD

**Issue by Telesphoreo** [wstyres/Zebra#728] opened 2019-12-21 16:56 UTC
**Describe the bug**
On the packages tab, you are able to swipe and select an action (upgrade / uninstall / reinstall). When swiping to reinstall, and then swiping again to upgrade, the label doesn't update.

**To Reproduce**
1. Go to the packages tab
2. Swipe and select reinstall
3. Swipe again and click update. Won't change.

**Expected behavior**

The label should change to the upgrade label. Intended behavior works from reinstall to delete.

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0-rc2-1
 - Device Type [e.g. iPhone or iPad]: iPhone Xs
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by eve0415** [comment] 2019-12-21 17:45
I think it’s same as #722

**Comment by wstyres** [comment] 2019-12-21 18:24
Duplicate of #722

**Closed by wstyres** 2019-12-21 18:24 UTC
Labels: bug, duplicate
