### ISSUE TITLE
 Respring Button issue (IOS 10)

### ISSUE THREAD

**Issue by Jynx175** [wstyres/Zebra#781] opened 2020-01-03 01:09 UTC
The respring button after installing/removing tweak does not work on ios 10.
You press it and it freezes. It never actually resprings.
It just hangs when i run sbreload.

**Comment by wstyres** [comment] 2020-01-05 04:30
Should be fixed as of 728db4f32804e256c560cfa13f7f0a9ef9c5869d and will be included in 1.0.3.

**Comment by Jynx175** [comment] 2020-01-05 05:41
sweet! I will let you know when 1.0.3 is out.

**Comment by wstyres** [comment] 2020-01-05 18:34
1.0.3 is out now, let me know if the issue is fixed

**Comment by Jynx175** [comment] 2020-01-06 21:09
it did not, every time i try to install a tweak or remove a tweak, it doesn't even show a respring button anymore. It just shows a done button.

**Comment by wstyres** [comment] 2020-01-08 19:34
Hmm ok, that issue shouldn't be isolated to iOS 10 then, I will see if I can reproduce it.

**Comment by Jynx175** [comment] 2020-01-09 01:49
ok, thanks!

**Comment by wstyres** [comment] 2020-01-10 20:44
Could you verify that `/Library/dkpg/info` exists on your device?

**Comment by wstyres** [comment] 2020-01-10 20:49
I ask because `/Library/dpkg/info` might not exist on iOS 10 and lower while `/var/lib/dpkg/info` should exist everywhere. On iOS 13 (at least) the latter directory is symlinked to the former directory but I think that might have been a change in more modern jailbreaks.

**Comment by wstyres** [comment] 2020-01-10 21:57
1.0.5 is out now, let me know

**Comment by Jynx175** [comment] 2020-01-10 23:04
nope, 1.0.5 did not fix it. When i press respring, nothing happens at all.

**Comment by wstyres** [comment] 2020-01-10 23:07
Ok so respring shows up again? This is different from 1.0.4, yes?

**Comment by Jynx175** [comment] 2020-01-10 23:59
Yes, the respring button show up again but it still does nothing when pressed.

**Comment by wstyres** [comment] 2020-01-11 00:26
Ok, does it hang still?

**Comment by Jynx175** [comment] 2020-01-11 04:23
yep

**Comment by wstyres** [comment] 2020-01-11 05:22
Alright, I’ll have to wait until I get my hands on an iOS 10 device to figure this out

**Comment by Jynx175** [comment] 2020-01-11 07:15
why dont you just have it do "killall SpringBoard -9" on ios 10 and 9?

**Comment by DFNCTSC** [comment] 2020-01-11 10:36
On iOS 10.3.4 JB with AFC2. For me it doesn't "hang". The Reset Springboard button just doesn't do anything, can press Done and continue on. Manually respringing works. This doesn't break anything just makes users have to manually respring -- at least on my end.

**Comment by wstyres** [comment] 2020-01-11 15:53
There are safer ways of respringing on more modern iOS versions that don’t involve killing the springboard. Killing the springboard is the last resort but I’m not quite sure why it isn’t running.

**Comment by Jynx175** [comment] 2020-01-12 05:21
well i mean using killing springboard could just be a quick fix until you get your hands on an ios 10 device.

**Comment by wstyres** [comment] 2020-01-17 15:45
Should be fixed as of f00da7bbfb7d5e33280f0c9a8a89cdf4a5c43a9d. Tested myself on an iPhone 5 running 10.3.4.

**Comment by Jynx175** [comment] 2020-01-19 21:06
1.0.6 fixed it. Thank you.

**Closed** 2020-01-19 21:06 UTC
Labels: bug, console, scheduled
